### ISSUE TITLE
Cannot create alias with targetKeyIdSelector

### ISSUE THREAD

**Issue by p53** [crossplane/provider-aws#1001]
### What happened?
I am getting this error when trying to create kms alias

```
2021-12-10T22:07:41.984Z        DEBUG   provider-aws    Cannot create external resource {"controller": "managed/alias.kms.aws.crossplane.io", "request": "/bubucluster-vrxm8", "uid": "bf04e8c6-d12a-4801-ad37-e2313053990b", "version": "1408638", "external-name": "bubuclust
er-vrxm8", "error": "cannot create Alias in AWS: NotFoundException: Invalid keyId bubucluster-9xbng", "errorVerbose": "NotFoundException: Invalid keyId bubucluster-9xbng\ngithub.com/crossplane/provider-aws/pkg/clients.Wrap\n\t/home/runner/work/provider-aws/provider-aws/p
kg/clients/aws.go:810\ngithub.com/crossplane/provider-aws/pkg/controller/kms/alias.(*external).Create\n\t/home/runner/work/provider-aws/provider-aws/pkg/controller/kms/alias/controller.go:119\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).
Reconcile\n\t/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:800\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/provider-aws/prov
ider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/int
ernal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/opt/h
ostedtoolcache/go/1.16.10/x64/src/runtime/asm_amd64.s:1371\ncannot create Alias in AWS\ngithub.com/crossplane/provider-aws/pkg/clients.Wrap\n\t/home/runner/work/provider-aws/provider-aws/pkg/clients/aws.go:810\ngithub.com/crossplane/provider-aws/pkg/controller/kms/alias.
(*external).Create\n\t/home/runner/work/provider-aws/provider-aws/pkg/controller/kms/alias/controller.go:119\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\t/home/runner/work/provider-aws/provider-aws/vendor/github.com/crosspla
ne/crossplane-runtime/pkg/reconciler/managed/reconciler.go:800\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.g
o:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/con
troller.(*Controller).Start.func2.2\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/asm_amd64.s:1371"}                       
2021-12-10T22:07:41.985Z        DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"Alias","name":"bubucluster-vrxm8","uid":"bf04e8c6-d12a-4801-ad37-e2313053990b","apiVersion":"kms.aws.crossplane.io/v1alpha1","resourceVersion":"1408638"}, "reason"
: "CannotCreateExternalResource", "message": "cannot create Alias in AWS: NotFoundException: Invalid keyId bubucluster-9xbng"}  
```               

### How can we reproduce it?
```
  - name: eks-kms-key
    base:
      apiVersion: kms.aws.crossplane.io/v1alpha1
      kind: Key
      metadata:
        labels:
          crossplane.io/composition-resource-name: ekskmskey
      spec:
        forProvider:
          description: "KMS key for ekscluster"
          enabled: true
    patches:
      - type: PatchSet
        patchSetName: common
  - name: eks-kms-key-alias
    base:
      apiVersion: kms.aws.crossplane.io/v1alpha1
      kind: Alias
      metadata:
        labels:
          crossplane.io/composition-resource-name: ekskmskeyalias
      spec:
        forProvider:
          targetKeyIDSelector:
            matchLabels:
                crossplane.io/composition-resource-name: ekskmskey
    patches:
      - type: PatchSet
        patchSetName: common
```

### What environment did it happen in?
Crossplane version: 1.4.2
kubernetes: 1.21.2
K8s distro: k3d

seems it might be somewhat related to https://github.com/crossplane/provider-aws/issues/685

i am new to this codebase but shouldn't be https://github.com/crossplane/provider-aws/blob/master/apis/kms/v1alpha1/zz_generated.resolvers.go#L48
be 
```
mg.Spec.ForProvider.TargetKeyID = reference.ExternalName()
```
