### ISSUE TITLE
hostedZoneID not getting synced with the external-name annotations, Instead creating a new HostedZone

### ISSUE THREAD

**Issue by madhureddy08** [crossplane/provider-aws#1057]
```
kubectl apply -f - <<EOF
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  name: route-53
  namespace: default
  annotations: 
    crossplane.io/external-name: XXXXXX
  forProvider:
    config:
      privateZone: false
    name: testingzone.com
  providerConfigRef:
    name: default
EOF
```

**Comment by haarchri** [comment]
can you post complete kubectl describe output ?

**Comment by haarchri** [comment]
can you tell us more about provider-aws version, crossplane version etc?

create first hostedZone:

```
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  name: crossplane.io
spec:
  forProvider:
    name: crossplane.io
  deletionPolicy: Orphan
  providerConfigRef:
    name: example
```

```
kubectl describe hostedzone.route53.aws.crossplane.io/crossplane.io 
Name:         crossplane.io
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2022-01-07T22:04:41+01:00
              crossplane.io/external-create-succeeded: 2022-01-07T22:04:42+01:00
              crossplane.io/external-name: Z06066312LZM8HQ39WXT6
API Version:  route53.aws.crossplane.io/v1alpha1
Kind:         HostedZone
Metadata:
  Creation Timestamp:  2022-01-07T21:04:41Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  3
  Resource Version:  2902912
  UID:               f30993f1-cd87-4f8c-b7a6-eab6e5a970a3
Spec:
  Deletion Policy:  Orphan
  For Provider:
    Config:
      Private Zone:  false
    Name:            crossplane.io
  Provider Config Ref:
    Name:  example
Status:
  At Provider:
    Delegation Set:
      Name Servers:
        ns-15.awsdns-01.com
        ns-1510.awsdns-60.org
        ns-1661.awsdns-15.co.uk
        ns-691.awsdns-22.net
    Hosted Zone:
      Caller Reference:  2902582
      Id:                /hostedzone/Z06066312LZM8HQ39WXT6
      Linked Service:
      Resource Record Set Count:  2
  Conditions:
    Last Transition Time:  2022-01-07T21:04:43Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-01-07T21:04:42Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
```

```
kubectl delete hostedzone.route53.aws.crossplane.io/crossplane.io 
hostedzone.route53.aws.crossplane.io "crossplane.io" deleted
```

create hostedZone with external-name:

```
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  annotations:
    crossplane.io/external-name: Z06066312LZM8HQ39WXT6
  name: test-reimport
spec:
  forProvider:
    name: crossplane.io
  deletionPolicy: Orphan
  providerConfigRef:
    name: example
```

```
kubectl describe hostedzone.route53.aws.crossplane.io/test-reimport
Name:         test-reimport
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-name: Z06066312LZM8HQ39WXT6
API Version:  route53.aws.crossplane.io/v1alpha1
Kind:         HostedZone
Metadata:
  Creation Timestamp:  2022-01-07T21:09:03Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  2
  Resource Version:  2903310
  UID:               4b85cbd4-8030-492d-97ad-de4ff06621fb
Spec:
  Deletion Policy:  Orphan
  For Provider:
    Config:
      Private Zone:  false
    Name:            crossplane.io
  Provider Config Ref:
    Name:  example
Status:
  At Provider:
    Delegation Set:
      Name Servers:
        ns-15.awsdns-01.com
        ns-1510.awsdns-60.org
        ns-1661.awsdns-15.co.uk
        ns-691.awsdns-22.net
    Hosted Zone:
      Caller Reference:  2902582
      Id:                /hostedzone/Z06066312LZM8HQ39WXT6
      Linked Service:
      Resource Record Set Count:  2
  Conditions:
    Last Transition Time:  2022-01-07T21:09:04Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-01-07T21:09:04Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:                    <none>

```
