### ISSUE TITLE
Add InstanceProfile CRD

### ISSUE THREAD

**Issue by mariobris** [crossplane/provider-aws#1064]
### What resource do you need?
AWS cli parameter is:
`create-instance-profile` and `add-role-to-instance-profile`

### What is your use case?

We are building VM which runs multiple commands against multiple endpoints where credentials are needed. Instead of passing these secrets directly into userdata field we can use `Instance Profile` to read credentials from `AWS SecretManager`.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
Sure, but might take some time at this point as we just started to use crossplane.

**Comment by haarchri** [comment]
we also interested in instanceProfile since karpenter needs one ;)

```
  KarpenterNodeInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: !Sub "KarpenterNodeInstanceProfile-${ClusterName}"
      Path: "/"
      Roles:
        - Ref: "KarpenterNodeRole"
```
