### ISSUE TITLE
AWS IAM Role default tags differ from desired manifest, result in sync loop in ArgoCD

### ISSUE THREAD

**Issue by ayeks** [crossplane/provider-aws#1072]
### What happened?

I am creating an AWS IAM Role with crossplane. Role gets created and tags get set. However, the role resource switches in 1 sec frequency between `Synced`and `OutOfSync` in Argo because the default tags are not included in the desired manifest. Seems to be related to merge request: #1000 The expected behavior is that Argo CD does not try to sync the manifest to delete the default tags all the time.

Here is the diff in Argo. Left side is the `Live Manifest`, right side the `Desired Manifest`.

![image](https://user-images.githubusercontent.com/4247399/150089107-38ba23ee-41b2-4090-b0f9-4c8124c163ae.png)

In AWS the default tags are set to the role:

![image](https://user-images.githubusercontent.com/4247399/150089336-ed3fad4c-7868-4ded-8395-5866af05acb3.png)

When I delete the tags in the AWS console, the tags will be automatically set again by crossplane.

The role:

```yaml
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.backupIamRole }}
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    tags:
      - key: InvoiceTo
        value: {{ .Values.sanitized_tags.InvoiceTo }}
      - key: Name
        value: {{ .Values.clusterName }}-{{ .Values.nameOverride }}
      - key: app:name
        value: {{ .Values.clusterName }}-{{ .Values.nameOverride }}
      - key: org:region
        value: {{ .Values.sanitized_tags.orgregion }}
      - key: org:unit
        value: {{ .Values.sanitized_tags.orgunit }}
      - key: url:deployment-repository
        value: {{ .Values.sanitized_tags.urldeploymentrepository }}
      - key: org:project
        value: {{ .Values.clusterName }}-{{ .Values.nameOverride }}
      - key: owner
        value: {{ .Values.sanitized_tags.owner }}
      - key: contact
        value: {{ .Values.sanitized_tags.contact }}
  providerConfigRef:
    name: aws-provider
```

The `provider-aws` logs:

```bash
2022-01-19T07:54:37.743Z	DEBUG	provider-aws	External resource differs from desired state	{"controller": "managed/role.iam.aws.crossplane.io", "request": "/k8s-timescaledb-test-backup-iam-role", "uid": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX", "version": "32408244", "external-name": "k8s-timescaledb-test-backup-iam-role", "diff": "Found observed difference in IAM role\n  &types.Role{\n  \t... // 1 ignored and 7 identical fields\n  \tPermissionsBoundary: nil,\n  \tRoleLastUsed:        &{LastUsedDate: &s\"2022-01-19 07:12:15 +0000 UTC\", Region: &\"eu-central-1\"},\n  \tTags: []types.Tag{\n  \t\t... // 7 identical elements\n  \t\t{Key: &\"owner\", Value: &\"XXXXXXXXXXXXXXXXXXXXXXX\"},\n  \t\t{Key: &\"contact\", Value: &\"XXXXXXXXXXXXXXXXXXXXXXXXXXXX\"},\n+ \t\t{Key: &\"crossplane-providerconfig\", Value: &\"aws-provider\"},\n  \t\t{Key: &\"crossplane-kind\", Value: &\"role.iam.aws.crossplane.io\"},\n  \t\t{Key: &\"crossplane-name\", Value: &\"k8s-timescaledb-test-backup-iam-role\"},\n- \t\t{Key: &\"crossplane-providerconfig\", Value: &\"aws-provider\"},\n  \t},\n  \t... // 1 ignored field\n  }\n\ndesired assume role policy: INLINEJSONBLOB"}
```

The problem does not exist for the IAM policy which I also create with Crossplane. Probably because no default tags are set there.

### How can we reproduce it?

Create a role with the template above, see how the default tags are added by crossplane and watch how Argo tries to sync the tags away because they are not defined in the desired manifest.

### What environment did it happen in?

Crossplane version: crossplane/crossplane:v1.6.1
provider-aws: crossplane/provider-aws-controller:v0.23.0

**Comment by ayeks** [comment]
I added the default tags to the crossplane resource as a work around, which solves the ArgoCD sync issues.

```yaml
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: {{ .Values.backupIamRole }}
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    tags:
      - key: InvoiceTo
        value: {{ .Values.sanitized_tags.InvoiceTo }}
      - key: Name
        value: {{ .Values.clusterName }}-{{ .Values.nameOverride }}
      - key: app:name
        value: {{ .Values.clusterName }}-{{ .Values.nameOverride }}
      - key: org:region
        value: {{ .Values.sanitized_tags.orgregion }}
      - key: org:unit
        value: {{ .Values.sanitized_tags.orgunit }}
      - key: url:deployment-repository
        value: {{ .Values.sanitized_tags.urldeploymentrepository }}
      - key: org:project
        value: {{ .Values.clusterName }}-{{ .Values.nameOverride }}
      - key: owner
        value: {{ .Values.sanitized_tags.owner }}
      - key: contact
        value: {{ .Values.sanitized_tags.contact }}
      - key: crossplane-kind
        value: role.iam.aws.crossplane.io
      - key: crossplane-name
        value: {{ .Values.crossplaneName }}
      - key: crossplane-providerconfig
        value: aws-provider
  providerConfigRef:
    name: aws-provider
```

I am not sure if the combination of the crossplane default tags and the sync from ArgoCD is a bug or a feature. If you think everything works as defined, feel free to close it. Otherwise I am open for discussion and other solutions.
