### ISSUE TITLE
KMS Alias invalid resource name when containing /

### ISSUE THREAD

**Issue by scornelius1** [crossplane/provider-aws#1078]
### What happened?

When I try to apply a KMS alias with a name that contains a `/` I get an  `invalid resource name` error returned

### How can we reproduce it?

Applying the following:

```yaml
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Alias
metadata:
  name: "alias/test3"
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-west-2
    targetKeyIdRef:
      name: test-key3
---
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: test-key3
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-west-2
    pendingWindowInDays: 21
```

Returns:

```
key.kms.aws.crossplane.io/test-key3 created
error: error when retrieving current configuration of:
Resource: "kms.aws.crossplane.io/v1alpha1, Resource=aliases", GroupVersionKind: "kms.aws.crossplane.io/v1alpha1, Kind=Alias"
Name: "alias/test3", Namespace: ""
from server for: "kms.yaml": invalid resource name "alias/test3": [may not contain '/']
```

This is however a valid KMS Alias name

### What environment did it happen in?
Crossplane: v1.6.1
AWS Provider: v0.23.0
