### ISSUE TITLE
New instance requires fields for EBS which are not mandatory

### ISSUE THREAD

**Issue by mariobris** [crossplane/provider-aws#1088]
### What happened?
Instance resource has an option for EBS device mapping however it requires fields which are not mandatory (e.g. `snapshotID`) which prevents user to create instnace with additional Volume. 
I've tried to use `volume` resource as well but we are missing `volumeAttachment` and cannot attach newly created volume to an instance.

I'd like to see new EBS volume attached to an instance if it's provided via manifest,
```
spec:
  forProvider:
    ...
    blockDeviceMappings:
    - deviceName: /dev/sdx
      ebs:
        volumeSize: 100
    ..
```

### How can we reproduce it?

You can create new instance with provided stanza and you will get error with missing parameters.

### What environment did it happen in?
Crossplane version: 
`image: crossplane/crossplane:v1.5.1`
`image: crossplane/provider-aws-controller:v0.22.0`
