### ISSUE TITLE
Improve experience of configuring cloudfront distributions

### ISSUE THREAD

**Issue by samidbb** [crossplane/provider-aws#1108]
### What happened?
Configuring cloudfront distribution seems to be a bit buggy. Some fields that are under `defaultCacheBehavior` are not required but once I introduced `cacheBehaviors `section then suddenly almost all fields become required and specifying `quantity` does not help on the experience.

Another issue is that the resource never goes into Ready state:
```
NAME                         READY   SYNCED   EXTERNAL-NAME
somedomain                   False   True     E1U92C17PI1M42
```
It seems like the provider has entered an infinite loop with reconciling the updates to the resource. This is maybe related to this issue https://github.com/crossplane/provider-aws/issues/894

### How can we reproduce it?
Here is the distribution that I was testing:

```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: somedomain
spec:
  providerConfigRef:
    name: my-namespace-aws
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution 3
      priceClass: PriceClass_100
      origins:
        items:
          - domainName: app.my.cloud
            id: customOrigin
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "https-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1.2
                quantity: 1
      cacheBehaviors:
        quantity: 1
        items:
        - pathPattern: /*/services-email-validation-api/*          
          smoothStreaming: false # Why is it required??
          targetOriginID: customOrigin
          compress: false
          viewerProtocolPolicy: https-only
          allowedMethods:        
            cachedMethods: # Why is it required??
              items:
              - HEAD
              - GET
              quantity: 2
            items:
            - GET 
            - HEAD 
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
            quantity: 7
          minTTL: 0
          maxTTL: 0
          defaultTTL: 0
          fieldLevelEncryptionID: "" # Why is this required ?
          forwardedValues:
            queryString: true 
            queryStringCacheKeys:  # Why is this required ?
              quantity: 0          # Why is this required ?              
            cookies:
              forward: all
            headers:
              items:
              - Accept
              - Accept-Charset
              - Accept-Encoding
              - Accept-Language
              - Authorization
              - Accept-Datetime
              - Referer
              - Origin
              quantity: 8  
          lambdaFunctionAssociations: # Why is this required ?
            quantity: 0
      defaultCacheBehavior:
        targetOriginID: customOrigin
        compress: false
        viewerProtocolPolicy: https-only
        allowedMethods:
          cachedMethods: # is not required before adding cacheBehaviors section!
            items:
            - HEAD
            - GET        
            quantity: 2            
          items:
          - GET 
          - HEAD 
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
          quantity: 7
        minTTL: 0
        maxTTL: 0
        defaultTTL: 0
        forwardedValues:
          queryString: true
          cookies:
            forward: all
          headers:
            items:
            - Accept
            - Accept-Charset
            - Accept-Encoding
            - Accept-Language
            - Authorization
            - Accept-Datetime
            - Referer
            - Origin
            quantity: 8
        lambdaFunctionAssociations: # is not required before adding cacheBehaviors section!
          quantity: 0
```
