### ISSUE TITLE
writeConnectionSecretToRef is not working for IAM User

### ISSUE THREAD

**Issue by lum-DannyK** [crossplane/provider-aws#1114]
### What happened?
I am trying to create a IAM User and write the connection to a secret with `writeConnectionSecretToRef`. The IAM user gets created correctly, but the secret is not created.

### How can we reproduce it?
You can reproduce it by using UXP or other K8S cluster and AWS provider 0.23.0

With this deployment file:
```
apiVersion: iam.aws.crossplane.io/v1beta1
kind: User
metadata:
  name: testuser
spec:
  forProvider: {}
  providerConfigRef:
    name: aws-provider
  deletionPolicy: Delete
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: iamuser-cp
```

### What environment did it happen in?
Crossplane version: 1.6.2
AWS provider version: 0.23.0
Kubernetes version: 1.22.3
Kubernetes distribution: AWS EKS and also tested on Minikube cluster
