### ISSUE TITLE
S3 replication metrics requires eventThreshold

### ISSUE THREAD

**Issue by AlexLast** [crossplane/provider-aws#1117]
### What happened?
When trying to configure an S3 bucket with the following replication spec, we encounter an error from the AWS API.

```yaml
replicationConfiguration:
  role: arn:aws:iam::<redacted>:role/<redacted>
  rules:
  - status: Enabled
     destination:
       bucket: arn:aws:s3:::<redacted>
       account: "<redacted>"
       replicationTime:
         status: Disabled
         time:
           minutes: 15
       accessControlTranslation:
         ownerOverride: Destination
       metrics:
         status: Enabled
         eventThreshold:
           minutes: 15
```

As far as I understand it, enabling `metrics`, with `replicationTime` disabled is valid configuration, the above configuration gives us the following error:

`cannot create or update: api error InvalidArgument: Metrics cannot contain an event threshold when ReplicationTime is not specified or Disabled`

However, `metrics.eventThreshold` cannot be omitted since this is a field required by the provider. 

### What environment did it happen in?
Crossplane version: `v1.6.1`
Provider version: `v0.23.0`
