### ISSUE TITLE
Extend the RouteTable CR to include RouteTableIDRef and RouteTableIDSelector

### ISSUE THREAD

**Issue by linuxbsdfreak** [crossplane/provider-aws#1137]
### What happened?
We are trying to create a composition with RouteTableIDSelector/ RouteTableIDRef  in a composition and we need to manually set the RouteTableID. I would like to use RouteTableIDSelector and also set RouteTableID as optional 

### How can we reproduce it?
```
    - name: cp-route-table-public-base
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          deletionPolicy: Delete
          forProvider:
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchControllerRef: true
            associations:
              - subnetIdSelector:
                   matchControllerRef: true
                   matchLabels:
                     vpcs.aws.platform.dmi.sap.com/access: public
              - subnetIdSelector:
                   matchControllerRef: true
                   matchLabels:
                     vpcs.aws.platform.dmi.sap.com/access: public
              - subnetIdSelector:
                   matchControllerRef: true
                   matchLabels:
                     vpcs.aws.platform.dmi.sap.com/access: public
            tags:
             - key: Environment
               value: ""
             - key: Owner
               value: ""
             - key: Name
               value: ""
            vpcIdSelector:
              matchControllerRef: true
          providerRef:
            name: aws-provider
          providerConfigRef:
            name: aws-provider-config
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[vpcs.aws.platform.dmi.sap.com/vpc-id]
        - fromFieldPath: spec.parameters.vpc.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.parameters.vpc.environment
          toFieldPath: spec.forProvider.tags[0].value
        - fromFieldPath: spec.parameters.vpc.owner
          toFieldPath: spec.forProvider.tags[1].value
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.tags[2].value
          transforms:
            - type: string
              string:
                fmt: "cp-pub-rtb-%s"
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels.role
          transforms:
            - type: string
              string:
                fmt: "cp-pub-rtb-%s"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.associations[0].subnetIdSelector.matchLabels.role
          transforms:
            - type: string
              string:
                fmt: "cp-pub-az1-%s"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.associations[1].subnetIdSelector.matchLabels.role
          transforms:
            - type: string
              string:
                fmt: "cp-pub-az2-%s"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.associations[2].subnetIdSelector.matchLabels.role
          transforms:
            - type: string
              string:
                fmt: "cp-pub-az3-%s"
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "cp-pub-rtb-%s"
    - name: cp-route-table-public-igw
      base:
        apiVersion: ec2.aws.crossplane.io/v1alpha1
        kind: Route
        spec:
          deletionPolicy: Delete
          forProvider:
            destinationCidrBlock: 8.8.8.8/32
            gatewayIdSelector:
              matchControllerRef: true
          providerRef:
            name: aws-provider
          providerConfigRef:
            name: aws-provider-config
      patches:
        - fromFieldPath: spec.parameters.vpc.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels.role
          transforms:
            - type: string
              string:
                fmt: "cp-pub-rt-%s"
        - fromFieldPath: spec.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "cp-pub-rt-igw-%s"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.routeTableIdSelector.matchLabels.role
          transforms:
            - type: string
              string:
                fmt: "cp-pub-rtb-%s"
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.gatewayIdSelector.matchLabels.role
          transforms:
            - type: string
              string:
                fmt: "cp-igw-%s"

```

I am unable to properly validate the change, since the CRDs are getting reverted by crossplane core after install. 

I cloned the aws-provider code and did the following 

```
+++ w/apis/ec2/v1alpha1/custom_types.go
@@ -280,8 +280,19 @@ type CustomRouteParameters struct {
        // in conjunction with any Route resources.
        // Doing so will cause a conflict of rule settings and will overwrite rules.
        // +optional
+       // +crossplane:generate:reference:type=github.com/crossplane/provider-aws/apis/ec2/v1beta1.RouteTable
        RouteTableID *string `json:"routeTableId,omitempty"`

+       // RouteTableIDRef is a reference to an API used to set
+       // the RouteTableID.
+       // +optional
+       RouteTableIDRef *xpv1.Reference `json:"routeTableIdRef,omitempty"`
+
+       // RouteTableIDSelector selects references to API used
+       // to set the RouteTableID.
+       // +optional
+       RouteTableIDSelector *xpv1.Selector `json:"routeTableIdSelector,omitempty"`
+
        // The ID of a NAT instance in your VPC. The operation fails if you specify
        // an instance ID unless exactly one network interface is attached.
        // +optional

```

make generate 
make services SERVICES=ec2

We are unable to correctly validate the setup.

### What environment did it happen in?
Crossplane version: 1.6.2
