### ISSUE TITLE
Secrets for existing AWS resources not being loaded in cross plane

### ISSUE THREAD

**Issue by rohitasva** [crossplane/provider-aws#1151]
### What happened?
I am trying to import an existing s3 bucket into cross plane & use it. The secrets for the s3 bucket are not being imported after successfully importing the s3 bucket. The secrets get created in the k8 secrets, but has no data.
 
### How can we reproduce it?
Example manifest which I'm using for import 
```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-s3-existing
  annotations:
    crossplane.io/external-name: crossplane-s3-existing
spec:
  deletionPolicy: Orphan
  forProvider:
    acl: private
    locationConstraint: us-west-2
    versioningConfiguration:
      status: Suspended
    publicAccessBlockConfiguration:
      blockPublicPolicy: TRUE
      restrictPublicBuckets: TRUE
  providerConfigRef:
    name: aws-provider
  writeConnectionSecretToRef:
    name: crossplane-s3-existing-details
    namespace: default
```

### What environment did it happen in?
Crossplane version: 
v1.4.1

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud provider: **AWS**
Kubernetes distribution: **Minikube**
```
minikube version: v1.23.0
commit: 5931455374810b1bbeb222a9713ae2c756daee10
```

Kernel:
```
uname -a                                                    
Darwin C02C835DMD6T 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```
