### ISSUE TITLE
Race Condition when referencing KMS Key in Filesystem composite

### ISSUE THREAD

**Issue by mithie** [crossplane/provider-aws#1152]
### What happened?

I am trying to create a composite crossplane resource consisting of an EFS filesystem component that references a KMS key. The key will be created in advance, so that I can reference it in my EFS filesystem for encryption. On first sight, this works as expected. The key is created and its ARN is added to the status field of the composite resource. But when I look into the AWS Management console, then I see that the EFS filesystem is created with a reference to the default `aws/elasticfilesystem` KMS key instead of the one that is created by crossplane. When I then delete the filesystem with `kubectl delete`, the filesystem will be recreated with the correct KMS key reference. It seems as if there is some sort of timing issue when the KMS key is initially created. Could you please evaluate this?

### How can we reproduce it?

The below snippet shows the composition yaml:

```yaml

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: sample-efs
  labels:
    crossplane.io/xrd: elasticfilesystems.some.api.group
spec:
  compositeTypeRef:
    apiVersion: some.api.group/v1alpha1
    kind: ElasticFilesystem
  resources:
    - name: key
      base:
        apiVersion: kms.aws.crossplane.io/v1alpha1
        kind: Key
        spec:
          forProvider:
            region:
            policy:
          providerConfigRef:
            name: aws-provider
      patches:
        - type: ToCompositeFieldPath
           fromFieldPath: "status.atProvider.arn"
           toFieldPath: "status.kmsKeyArn"
    - name: filesystem
      base:
        apiVersion: efs.aws.crossplane.io/v1alpha1
        kind: FileSystem
        spec:
          forProvider:
            encrypted: true
            kmsKeyID:
            performanceMode:
            region:
          providerConfigRef:
            name: aws-provider
      patches:
        - fromFieldPath: "status.kmsKeyArn"
          toFieldPath: "spec.forProvider.kmsKeyID"
```

This is the code of the corresponding resource definition:

```yaml

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: elasticfilesystems.some.api.group
spec:
  group: some.api.group
  names:
    kind: ElasticFilesystem
    plural: elasticfilesystems
  claimNames:
    kind: ElasticFilesystemClaim
    plural: elasticfilesystemclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      enum: ["eu-west-1", "eu-central-1", "us-east-1"]
                    performanceMode:
                      type: string
                      enum: ["generalPurpose", "maxIO"]
                  required:
                    - region
                    - performanceMode
              required:
                - parameters
            status:
              type: object
              properties:
                kmsKeyArn:
                  type: string

```

### What environment did it happen in?

Crossplane version: 1.6.2
AWS provider version: 0.24.1
Kubernetes version: 1.21

**Comment by janwillies** [comment]
Some parts of the KMS API are eventual consistent: https://docs.aws.amazon.com/kms/latest/developerguide/grants.html#terms-eventual-consistency

Maybe that's the issue here?

**Comment by haarchri** [comment]
@mithie did you tested to use Ref/Selectors for kmsKeyId ? In our setup can't see the issue when using:
https://doc.crds.dev/github.com/crossplane/provider-aws/efs.aws.crossplane.io/FileSystem/v1alpha1@v0.24.1#spec-forProvider-kmsKeyIdRef 
or
https://doc.crds.dev/github.com/crossplane/provider-aws/efs.aws.crossplane.io/FileSystem/v1alpha1@v0.24.1#spec-forProvider-kmsKeyIdSelector

**Comment by mithie** [comment]
Hi @haarchri , yes I tried that (`kmsKeyIdRef`) out and it works as expected. Though, shouldn't it work as well when I am  using `kmsKeyID`? If there is any sort of restriction when using this property I think it should at least be documented.

**Comment by haarchri** [comment]
with Ref/Selector we waiting till the KMS Key is available thing this does the trink - and saved you the patch

**Comment by haarchri** [comment]
Think for EFS and KMS the stuff is working - @babilen i will have a look for your referenced issue for sqs

**Comment by mithie** [comment]
> with Ref/Selector we waiting till the KMS Key is available thing this does the trink - and saved you the patch

Yes, that is true. but it is not documented that using the Id instead won't work and why. Maybe this is a general issue and if so I would expect that it is documented in the spec. Or maybe I just overlooked something. But adding a short comment/explanation to this property might save a lot of time doing trial and error. Also, why are you waiting when you are using the Ref/Selector attributes and why not when using the component Id?

**Comment by mithie** [comment]
> I'm running into a similar issue when trying to create an encrypted [Queue](https://doc.crds.dev/github.com/crossplane/provider-aws/sqs.aws.crossplane.io/Queue/v1beta1@v0.24.1).
> 
> Just out of curiosity, how did you make `kmsKeyIdRef` work, @mithie ?

@babilen , in the filesystem composition I am defining the kmsKeyIdRef:

```
    - name: filesystem
      base:
        apiVersion: efs.aws.crossplane.io/v1alpha1
        kind: FileSystem
        spec:
          forProvider:
            encrypted: true
            kmsKeyIdRef:
              name:
      ...
      patches:
        - fromFieldPath: "status.kmsKeyName"
          toFieldPath: "spec.forProvider.kmsKeyIdRef[name]"
```

After the key is created I write the key name into the `status.kmsKeyName` field of my custom component, so that I can reference it within the patch above.

```
  resources:
    - name: key
      base:
        apiVersion: kms.aws.crossplane.io/v1alpha1
        kind: Key
       ...
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: "metadata.name"
          toFieldPath: "status.kmsKeyName"
```
