### ISSUE TITLE
S3 websiteConfiguration is not working

### ISSUE THREAD

**Issue by BhavyaSree** [crossplane/provider-aws#1155]
Slack thread: https://crossplane.slack.com/archives/CEG3T90A1/p1645139809042389

### What happened?
When we are creating the s3 bucket with websiteConfiguration, bucket is being created in the console without website config and the bucket is in NOT READY status on the cluster stating `cannot create or update: api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema`.
We are trying to convert s3 bucket from cloudformation to crossplane.
CloudFormation
```
      WebsiteConfiguration:
        ErrorDocument: bb-test-docs/error.html
        IndexDocument: index.html
```
Crossplane
```
    websiteConfiguration:
      errorDocument: 
        key: 'bb-test-docs/error.html'
      indexDocument: 
        suffix: 'index.html'
```

### How can we reproduce it?

Create a bucket with the following
```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: bb-test-bucket-temp
spec:
  forProvider:
    acl: private
    locationConstraint: us-west-2
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    tagging:
      tagSet:
        - key: Application
          value: value
    websiteConfiguration:
      errorDocument: 
       key: bb-test-docs/error.html
      indexDocument: 
       suffix: index.html
  providerConfigRef:
    name: crossplane-provider-config
```
Bucket is in NOT READY status
```
NAME                           READY   SYNCED   AGE
bb-test-bucket-temp             False   False   7m8s
```
with `Warning  CannotUpdateExternalResource  41s (x16 over 12m)  managed/bucket.s3.aws.crossplane.io  cannot create or update: api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema`

### What environment did it happen in?
Crossplane version: 
DockerImage: v1.5.0
