### ISSUE TITLE
Cannot create encrypted SQS queue via Claim

### ISSUE THREAD

**Issue by babilen** [crossplane/provider-aws#1162]
### What happened?

It appears to be impossible to create a suitable`XRD` and `Composition` that is the equivalent of the following managed resources:

```
---
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: sqs-key
spec:
  forProvider:
    region: eu-west-2
---
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Alias
metadata:
  name: sqs-key-alias
spec:
  forProvider:
    region: eu-west-2
    targetKeyIdRef:
      name: sqs-key
---
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: sqs-test
spec:
  forProvider:
    region: eu-west-2
    kmsMasterKeyId: sqs-key-alias
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: sqs-connection
```

### How can we reproduce it?

The issue can be reproduced by defining this `XRD`:

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xqueues.some-base.tld
spec:
  group: some-base.tld
  names:
    kind: XQueue
    plural: xqueues
  claimNames:
    kind: QueueClaim
    plural: queueclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      enum: ["uk"]
                  required:
                    - region
              required:
                - parameters
```
and the following `Composition`:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: queue
  labels:
    crossplane.io/xrd: xqueue.some-base.tld
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: some-base.tld/v1alpha1
    kind: XQueue
  resources:
    - name: sqs-key
      base:
        apiVersion: kms.aws.crossplane.io/v1alpha1
        kind: Key
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: "metadata.name"
          toFieldPath: "status.kmsKeyName"
        - type: PatchSet
          patchSetName: region
    - name: sqs-key-alias
      base:
        apiVersion: kms.aws.crossplane.io/v1alpha1
        kind: Alias
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "status.kmsKeyName"
          toFieldPath: "spec.forProvider.targetKeyIdRef.name"
        - type: ToCompositeFieldPath
          fromFieldPath: "metadata.name"
          toFieldPath: "status.kmsAliasName"
        - type: PatchSet
          patchSetName: region
    - name: sqs-queue
      base:
        apiVersion: sqs.aws.crossplane.io/v1beta1
        kind: Queue
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "status.kmsAliasName"
          toFieldPath: "spec.forProvider.kmsMasterKeyId"
        - type: PatchSet
          patchSetName: region
  patchSets:
    - name: region
      patches:
       - type: FromCompositeFieldPath
         fromFieldPath: spec.parameters.region
         toFieldPath: spec.forProvider.region
         transforms:
           - type: map
             map:
               uk: eu-west-2
```
With this I see the following problems:

```
$ kubectl get managed
NAME                                         READY   SYNCED   EXTERNAL-NAME
alias.kms.aws.crossplane.io/my-queue-wf685   False   False    my-queue-wf685
...
$ kubectl describe alias.kms.aws.crossplane.io/my-queue-wf685
Name:         my-queue-wf685
Namespace:    
Labels:       crossplane.io/claim-name=
              crossplane.io/claim-namespace=
              crossplane.io/composite=my-queue
Annotations:  crossplane.io/composition-resource-name: sqs-key-alias
              crossplane.io/external-create-failed: 2022-02-21T16:54:13Z
              crossplane.io/external-create-pending: 2022-02-21T16:54:13Z
              crossplane.io/external-name: my-queue-wf685
API Version:  kms.aws.crossplane.io/v1alpha1
Kind:         Alias
...
Spec:
  Deletion Policy:  Delete
  For Provider:
    Region:  eu-west-2
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2022-02-21T16:53:32Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-02-21T16:53:32Z
    Message:               create failed: cannot create Alias in AWS: InvalidParameter: 1 validation error(s) found.
- missing required field, CreateAliasInput.TargetKeyId.

    Reason:  ReconcileError
    Status:  False
    Type:    Synced
Events:
  Type     Reason                        Age                From                                 Message
  ----     ------                        ----               ----                                 -------
  Warning  CannotCreateExternalResource  34s (x9 over 75s)  managed/alias.kms.aws.crossplane.io  cannot create Alias in AWS: InvalidParameter: 1 validation error(s) found.
- missing required field, CreateAliasInput.TargetKeyId.
```
And - even more importantly - the created queue is not encrypted, which is similar to the behaviour seen in #1152.

What's is the best way to define a `Composition` that mirrors the managed resources above? Thanks!

### What environment did it happen in?

Crossplane version:  v1.6.3
Provider AWS: v0.24.1
