### ISSUE TITLE
dbInstnace and rdsinstance do not join dbcluster

### ISSUE THREAD

**Issue by hosseinkassaei** [crossplane/provider-aws#1164]
### What happened?

When creating a `DBCluster` with a new VPC, Subnets, etc. it's not possible to create a primary/writer replica, using either `RDSInstance` or `DBInstance`  to join the cluster. The error says MasterUsername is blank, but it seems to be due to the fact that the `RDSInstance` is not properly connected to the `DBCluster`.

`2022-02-21T19:02:56.250Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"RDSInstance","name":"postgresql-instance-vgdc9-f9qvr","uid":"438abf21-6545-4cba-afc4-6d3f657f8a48","apiVersion":"database.aws.crossplane.io/v1beta1","resourceVersion":"459622"}, "reason": "CannotCreateExternalResource", "message": "cannot create RDS instance: api error InvalidParameterValue: The parameter MasterUsername must be provided and must not be blank."}`

### How can we reproduce it?

A composition that creates all the needed resources:

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aurora.rds.aws.database.ericsson.com
  labels:
    provider: aws
    vpc: new
    type: amazon-aurora-postgresql
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.ericsson.com/v1alpha1
    kind: XPostgreSQLInstance 
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            region: ca-central-1
            cidrBlock: 172.16.0.0/16
            enableDnsSupport: true
            enableDnsHostNames: true
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-vpc"
          toFieldPath: spec.forProvider.tags[0].value
  
    - name: subnet-a
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: ca-central-1a
        spec:
          forProvider:
            region: ca-central-1
            cidrBlock: 172.16.64.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: ca-central-1a
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-subnet"
          toFieldPath: spec.forProvider.tags[0].value

    - name: subnet-b
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: ca-central-1b
        spec:
          forProvider:
            region: ca-central-1
            cidrBlock: 172.16.128.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: ca-central-1b
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-subnet"
          toFieldPath: spec.forProvider.tags[0].value

    - name: subnet-c
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: ca-central-1d
        spec:
          forProvider:
            region: ca-central-1
            cidrBlock: 172.16.192.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: ca-central-1d
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-subnet"
          toFieldPath: spec.forProvider.tags[0].value

    - name: dbsubnetgroup
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        spec:
          forProvider:
            region: ca-central-1
            description: An excellent formation of subnetworks.
            subnetIdSelector:
              matchControllerRef: true
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-dbsubnetgroup"
          toFieldPath: spec.forProvider.tags[0].value
  
    - name: internetgateway
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            region: ca-central-1
            vpcIdSelector:
              matchControllerRef: true
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-igw"
          toFieldPath: spec.forProvider.tags[0].value

  
    - name: routetable
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: ca-central-1
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchControllerRef: true
            associations:
              - subnetIdSelector:
                  matchLabels:
                    zone: ca-central-1a
              - subnetIdSelector:
                  matchLabels:
                    zone: ca-central-1b
              - subnetIdSelector:
                  matchLabels:
                    zone: ca-central-1d
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-rt"
          toFieldPath: spec.forProvider.tags[0].value


    - name: securitygroup
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            region: ca-central-1
            vpcIdSelector:
              matchControllerRef: true
            groupName: postgresql-sg
            description: Allow access to PostgreSQL
            ingress:
              - fromPort: 5432
                toPort: 5432
                ipProtocol: tcp
                ipRanges:
                  - cidrIp: 0.0.0.0/0
                    description: Everywhere
            tags:
              - key: Name
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.parameters.instanceName"
            strategy: string
            string:
              fmt: "%s-sg"
          toFieldPath: spec.forProvider.tags[0].value

    - name: dbcluster
      base:
        apiVersion: rds.aws.crossplane.io/v1alpha1
        kind: DBCluster
        spec:
          forProvider:
            region: ca-central-1
            engine: aurora-postgresql
            vpcSecurityGroupIDSelector:
              matchControllerRef: true
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            masterUsername: masteruser
            masterUserPasswordSecretRef:
              namespace: crossplane-system
              name: auroradb-creds
              key: password
            skipFinalSnapshot: true
            applyImmediately: true
            publiclyAccessible: true
            storageEncrypted: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.version"
          toFieldPath: "spec.forProvider.engineVersion"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port

    # - name: dbInstance
    #   base:
    #     apiVersion: rds.aws.crossplane.io/v1alpha1
    #     kind: DBInstance
    #     spec:
    #       forProvider:
    #         region: ca-central-1
    #         dbClusterIdentifierSelector:
    #           matchControllerRef: true
    #         dbSubnetGroupNameSelector:
    #           matchControllerRef: true
    #         engine: aurora-postgresql
    #         publiclyAccessible: true
    #       writeConnectionSecretToRef:
    #         namespace: crossplane-system
    #   patches:
    #     - fromFieldPath: "metadata.uid"
    #       toFieldPath: "spec.writeConnectionSecretToRef.name"
    #       transforms:
    #         - type: string
    #           string:
    #             fmt: "%s-postgresql"
    #     - fromFieldPath: "spec.parameters.version"
    #       toFieldPath: "spec.forProvider.engineVersion"
    #     - fromFieldPath: "spec.parameters.flavor"
    #       toFieldPath: "spec.forProvider.dbInstanceClass"
    #     - fromFieldPath: "spec.parameters.autoMinorVersionUpgrade"
    #       toFieldPath: "spec.forProvider.autoMinorVersionUpgrade"
    #   connectionDetails:
    #     - fromConnectionSecretKey: username
    #     - fromConnectionSecretKey: password
    #     - fromConnectionSecretKey: endpoint
    #     - fromConnectionSecretKey: port

    
    - name: rdsinstance
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            region: ca-central-1
            dbClusterIdentifierSelector:
              matchControllerRef: true
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            engine: aurora-postgresql
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: true
            storageEncrypted: true
            enablePerformanceInsights: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.version"
          toFieldPath: "spec.forProvider.engineVersion"
        - fromFieldPath: "spec.parameters.flavor"
          toFieldPath: "spec.forProvider.dbInstanceClass"
        - fromFieldPath: "spec.parameters.dbName"
          toFieldPath: "spec.forProvider.dbName"
        - fromFieldPath: "spec.parameters.autoMinorVersionUpgrade"
          toFieldPath: "spec.forProvider.autoMinorVersionUpgrade"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port

```
I have checked with aurora-mysql and seen the same issue. Looking at examples such as the one in the repo (https://github.com/crossplane/provider-aws/tree/master/examples/rds), could the difference be in the explicit creation of VPC, Subnets, etc.?

### What environment did it happen in?
Crossplane version: 

$kubectl get pkgrev
NAME                                                           HEALTHY   REVISION   IMAGE                             STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/provider-aws-f78664a342f1   True      1          crossplane/provider-aws:v0.24.1   Active                               2d21h
