### ISSUE TITLE
unable to recognize "instance.yaml": no matches for kind "Instance" in version "ec2.aws.crossplane.io/v1alpha1"

### ISSUE THREAD

**Issue by dipendrachaudhary** [crossplane/provider-aws#1173]
Getting this issue while applying the file
`unable to recognize "instance.yaml": no matches for kind "Instance" in version "ec2.aws.crossplane.io/v1alpha1"
unable to recognize "instance.yaml": no matches for kind "Instance" in version "ec2.aws.crossplane.io/v1alpha1"`

This is my yaml file
```
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: public-instance
spec:
  forProvider:
    region: us-east-1
    imageId: ami-0dc2d3e4c0f9ebd18
    keyName: landingZone
    blockDeviceMappings:
     - deviceName: /dev/sdx
       ebs:
         volumeSize: 100
    securityGroupRefs:
      - name: sample-securitygroup
    subnetIdRef:
      name: sample-subnet1  
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: private-instance
spec:
  forProvider:
    region: us-east-1
    imageId: ami-0dc2d3e4c0f9ebd18
    keyName: landingZone
    blockDeviceMappings:
     - deviceName: /dev/sdx
       ebs:
         volumeSize: 100
    securityGroupRefs:
      - name: sample-securitygroup
    subnetIdRef:
      name: sample-subnet
  providerConfigRef:
    name: default
```

following this `https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/Instance/v1alpha1@v0.24.1` and `https://github.com/crossplane/provider-aws/blob/master/examples/ec2/instance.yaml`
