### ISSUE TITLE
Cloudfront Looping into Deploying State when using cache behaviors

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#1174]
### What happened?

I have a cloudfront composition which will put the distribution in a constant loop into deploying. Everything was working fine until I added a key for `cacheBehaviors` in the CompositeDefinition which in turn would add to the same key in the `Distribution` which is created by the Composition. This was easier said than done.

Every single key in every object in the array of the incredibly detailed `cacheBehaviors` needed to be filled. No defaults at all. 

It all seems to kinda work but it also seems every time Crossplane reconciles the resource, the Distribution will go back to deploying. 

Here is what I had to do to get a single cache behavior as it defaults in the web console.  
```yaml
    cacheBehaviors:
      quantity: 1
      items:

      # so it seems all of these are required . . . 
      - pathPattern: /images/*
        targetOriginID: s3Origin
        viewerProtocolPolicy: allow-all
        smoothStreaming: false
        compress: false
        minTTL: 100
        maxTTL: 900
        defaultTTL: 100
        fieldLevelEncryptionID: ""
        lambdaFunctionAssociations:
          quantity: 0
          items: []
        trustedKeyGroups:
          enabled: false
          quantity: 0
        trustedSigners:
          enabled: false
          quantity: 0
        forwardedValues: 
          queryString: false
          cookies: 
            # all, whitelist, none
            forward: all
            whitelistedNames:
              quantity: 0
              items: []
          headers: 
            quantity: 0
            items: []
          queryStringCacheKeys:
            quantity: 0
            items: []
        allowedMethods:
          cachedMethods:
            items:
              - HEAD
              - GET
            quantity: 2
          items:
            - HEAD
            - GET
          quantity: 2
```

### How can we reproduce it?

Here is what I wanted to do:  
```yaml
    cacheBehaviors:
      items:
      - pathPattern: /images/*
        targetOriginID: s3Origin
```
Use this snippet with a Cloudfront Distribution resource and see what happens. 

I have shared the repo with @haarchri and other Crossplane members. 
This one: https://github.com/Cubizoid/crosshook

To get the composition and xrd up from that project:
```
kubectl apply -k compositions/website
```

Use this as the example:
```yaml
apiVersion: cubizoid.com/v1
kind: Website
metadata:
  name: cool-stack
spec:
  parameters:
    domain: app.example.com
    zone: example.com
    enabled: true
    description: |
      This directs static and dynamic 
      content to s3 bucket and ALB respectively.
    defaultRootObject: index.html
    bucket:
      path: /web
    loadBalancer:
      endpoint: foo-bar.us-west-2.elb.amazonaws.com
    cacheBehaviors:
      quantity: 1
      items:

      # i put defaults on all the keys in the definitions openapi schema
      - pathPattern: /images/*
        targetOriginID: s3Origin

```
