### ISSUE TITLE
It is not possible to import securitygroup which is created previously by composition with same claim. 

### ISSUE THREAD

**Issue by peterbosalliandercom** [crossplane/provider-aws#1175]
This problem is best described with an example: 

1. Create a composition with a securitygroup with deletionPolicy: Orphan
2. Create a claim for that composition and deploy. 
3. Remove the claim
4. Now the securitygroup stays behind in AWS which is as expected. 
5. Create the same claim again. 
6. Now the security will have a reconcile error and cannot create a duplicate groupname. 

We expect that it can reconcile the existing securitygroup.

We used the following composition for the securitygroup and we set the following annotation
  annotations:
    crossplane.io/external-name: sg-0002 **# we don't know the id that is created by the composition so we try to use our own 
this part does not work, aws creates its own ID.** 

Import resources is described here: https://github.com/crossplane/crossplane/issues/1093

```
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        spec:
          deletionPolicy: Orphan
          forProvider:
            groupName: crossplane-test-sg
            ingress:
              - fromPort: 5432
                ipProtocol: tcp
                ipRanges:
                  - cidrIp: 0.0.0.0/0
                    description: Everywhere
                toPort: 5432
            region: eu-central-1
            vpcId: vpc-xxxxxxxx
          providerConfigRef:
            name: aws-provider
      name: securitygroup-whitelist
      patches:
        - fromFieldPath: 'metadata.annotations[crossplane.io/external-name]'
          toFieldPath: 'metadata.annotations[crossplane.io/external-name]'
```

We want to import this created securitygroup but this is not possible this way.
