### ISSUE TITLE
ResourceRecordSet fails to create on acm certificate records

### ISSUE THREAD

**Issue by samidbb** [crossplane/provider-aws#1176]
### What happened?

I have this example that creates a record in my hostedzone that should enable DNS validation of my certificate:
```
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: _dsj24j034j80f34j0adpsw.foo.example.com
spec:
  forProvider:
    type: CNAME
    resourceRecords:
    - value: _dfijodfsope9023r.dfsijqwiu.acm-validations.aws
    zoneId: Z051954628PAZ7EXQHR0T
```

But it fails with this message:
```
The ResourceRecordSet "_f4f176f1bab8dc3d6bd08e6e4986c178.customer-iam3.dfds.cloud" is invalid: metadata.name: Invalid value: "_f4f176f1bab8dc3d6bd08e6e4986c178.customer-iam3.dfds.cloud": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

The issue is mentioned here as well: https://github.com/crossplane/provider-aws/issues/804#issuecomment-969267759
Importing using external name works fine as mentioned here https://github.com/crossplane/provider-aws/issues/804#issuecomment-970443911

But this means I have to manually create them before I can start managing them with Crossplane.

### What environment did it happen in?
Resource: [ResourceRecordSet.v1alpha1.route53.aws.crossplane.io](https://doc.crds.dev/github.com/crossplane/provider-aws/route53.aws.crossplane.io/ResourceRecordSet/v1alpha1@v0.24.1#)
Crossplane aws provider: crossplane/provider-aws:v0.24.1

**Comment by haarchri** [comment]
creation with external-name annotation and metadata.name to something else is also working - is this an option ?

**Comment by ezgidemirel** [comment]
Hello @samidbb, did you have a chance to try the suggestion above? You can use following manifest to create the record:

```
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  annotations:
    crossplane.io/external-name: "_dsj24j034j80f34j0adpsw.foo.example.com"
  name: myrecord
spec:
  forProvider:
    type: CNAME
    resourceRecords:
    - value: _dfijodfsope9023r.dfsijqwiu.acm-validations.aws
    zoneId: Z051954628PAZ7EXQHR0T
```

**Comment by kmcarol26** [comment]
I ran into this issue as well and adding annotation helped. Is this how it's supposed to work? If yes, then the documentation should be updated to reflect that

**Comment by samidbb** [comment]
Thank you @ezgidemirel. I had to chance to test your suggestion today and it's working fine for me

**Comment by ezgidemirel** [comment]
@samidbb that's great to hear! 

@kmcarol26 I'll check the appropriate place for updating the documentation. Thanks for your input!

**Comment by ezgidemirel** [comment]
@kmcarol26 just noticed that it's already documented [here](https://crossplane.io/docs/v1.6/concepts/managed-resources.html#external-name) :)

**Comment by project-administrator** [comment]
Tried replacing the "external-name" in a composition but it does not work for me. The patch is silently ignored:
```yaml
  - name: validation-record
    base:
      apiVersion: route53.aws.crossplane.io/v1alpha1
      kind: ResourceRecordSet
      spec:
        forProvider:
          ttl: 300
          description: 'Managed by Crossplane'
        providerConfigRef:
          name: 'aws-provider'
    patches:
    # - type: FromCompositeFieldPath
    #   fromFieldPath: spec.parameters.region
    #   toFieldPath: spec.forProvider.region
    #   policy:
    #     fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: status.zoneID
      toFieldPath: spec.forProvider.zoneId
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: status.domainValidationOptions[0].resourceRecordName
      toFieldPath: "metadata.annotations.crossplane.io/external-name"
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: status.domainValidationOptions[0].resourceRecordType
      toFieldPath: spec.forProvider.type
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: status.domainValidationOptions[0].resourceRecordValue
      toFieldPath: spec.forProvider.resourceRecords[0].value
      policy:
        fromFieldPath: Required
```
The resulting composed managed resource is:
```yaml
Annotations:  crossplane.io/composition-resource-name: validation-record
              crossplane.io/external-create-failed: 2023-05-19T11:20:33Z
              crossplane.io/external-create-pending: 2023-05-19T11:20:33Z
              crossplane.io/external-name: sample-domaincert-c6khz
```
And the obvious error message:
```
failed to create the ResourceRecordSet resource: InvalidChangeBatch: [RRSet with DNS name sample-domaincert-c6khz. is not permitted in zone abcde0.our.domian.co.]
```
