### ISSUE TITLE
Unable to Remove FunctionAssociations

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#1219]
### What happened?

I added a Cloudfront Function to the `defaultCacheBehavior.functionAssociations.items`. Now I cannot remove it and I get this error:

```
The Distribution "my-cdn" is invalid: spec.forProvider.distributionConfig.defaultCacheBehavior.functionAssociations.items.functionARN: Invalid value: "null": spec.forProvider.distributionConfig.defaultCacheBehavior.functionAssociations.items.functionARN in body must be of type string: "null"
```

Once again every issue will cause the Composition to start looping the Distribution into constant `Deploying` state and never becomes ready. Now because I can't remove the function I can't stabilize the distribution. 

### How can we reproduce it?

First create a simple distribution with no Functions. Then add a function to the defaultCacheBehavior like so:
```yaml
        functionAssociations:
          items:
            - eventType: viewer-request
              functionARN: arn:aws:cloudfront::123456789:function/rewriter
          quantity: 1
```
Now try and remove it. 

### What environment did it happen in?
Crossplane version:

**Comment by kferrone** [comment]
Ermm, this is totally blocking me now. I can't update any value in any of the entire Distribution object. I get this error even if I try to add a label. This error is completely preventing the Composition from changing any values at all.

**Comment by haarchri** [comment]
which provider-aws version you using ?

**Comment by kferrone** [comment]
Sorry it was caused by something I did. It was posting the functionAssociations like so:
```yaml
functionAssociations: 
  items: []
  quantity: 0
```
I discovered you must remove the entire key to not have any functions. It can't just be empty like that.
