### ISSUE TITLE
DBCluster doesn't update configuraion

### ISSUE THREAD

**Issue by nik843** [crossplane/provider-aws#1237]
### What happened?

I have an RDS Aurora Serverless cluster, when I change the configuration of the cluster, it doesn't lead to any changes on the AWS side. Update event isn't created.
This is a configuration of the cluster:
````
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: aurora-mysql-cluster-crossplane
spec:
  forProvider:
    region: us-east-1
    engine: aurora-mysql
    engineMode: serverless
    masterUsername: admin
    masterUserPasswordSecretRef:
      name: aurora-mysql-cluster-crossplane
      namespace: crossplane-system
      key: password
    databaseName: app
    skipFinalSnapshot: true
    scalingConfiguration:
      minCapacity: 2
      maxCapacity: 16
      autoPause: true
      secondsUntilAutoPause: 300
    applyImmediately: true
    vpcSecurityGroupIDRefs:
      - name: crossplane-aurora-rds-sg
    tags:
      - key: crossplane-kind
        value: rds.aws.crossplane.io
      - key: crossplane-name
        value: aurora-mysql-cluster-crossplane
      - key: crossplane-api
        value: rds.aws.crossplane.io
  writeConnectionSecretToRef:
    name: example-aurora-mysql-cluster
    namespace: crossplane-system
  providerConfigRef:
    name: provider-aws
 ````

### How can we reproduce it?

- create Serverless DB cluster
- change configuration - tag, scalingConfiguration or so

### What environment did it happen in?
Crossplane version:  1.7.0
Provider-AWS: v0.25.0
k8s: v1.21.4
Cloud provider: AWS
