### ISSUE TITLE
Cannot update imported Cloudfront Distribution resources

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/provider-aws#1260]
### What happened?

After importing an existing Cloudfront distribution resource, trying to updating its fields fails with following error:
```
  Warning  CannotUpdateExternalResource  1s (x5 over 14s)  managed/distribution.cloudfront.aws.crossplane.io  cannot update Distribution in AWS: IllegalUpdate: You cannot update Origin or CallerReference.
```

### How can we reproduce it?

- Create a Cloudfront Distribution from AWS console
- Import it with following manifest
```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  annotations:
    crossplane.io/external-name: <external-name-of-the-distribution>
  name: example-distribution
spec:
  forProvider:
    region: us-east-1
    distributionConfig: {}
```
- Update `spec.forProvider.distributionConfig.comment`

### What environment did it happen in?
Crossplane version: v1.6.3-up.1
provider-aws version: v0.25.0
