### ISSUE TITLE
Cloudfront Distribution resource doesn't become ready when ResponseHeadersPolicyID is set

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/provider-aws#1295]
### What happened?

Setting "ResponseHeadersPolicyID" field caused infinite synching. 

### How can we reproduce it?

Can be reproduced with following manifest:
```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: example-distribution-custom-origin
spec:
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution
      origins:
        items:
          - domainName: crossplane-example.amazon.com
            id: customOrigin
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "http-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1
      defaultCacheBehavior:
        responseHeadersPolicyID: <policyID>
        targetOriginID: customOrigin
        viewerProtocolPolicy: allow-all
        minTTL: 0
        forwardedValues:
          cookies:
            forward: none
          queryString: false
```

### What environment did it happen in?
provider-aws version: v0.26.1
