### ISSUE TITLE
Empty atProvider for loadBalancer

### ISSUE THREAD

**Issue by edemelessessi** [crossplane/provider-aws#1309]
### What happened?
 All sub-resources of loadBalancer such as availabilityZone, dnsName, loadBalncaerARN etc under status.atProvider are empty

```
apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  name: xlb
spec:
  deletionPolicy: Delete
  forProvider:
    loadBalancerType: network
    name: x-lb
    region: us-east-1
    subnets:
    - subnet-02234e0485760df45
  providerConfigRef:
    name: default
status:
  atProvider: {}  <--------
  conditions:
  - lastTransitionTime: "2022-05-16T16:58:48Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-05-16T16:56:46Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced

```

### How can we reproduce it?
 Just create a loadBalancer resource with the provider-aws version v0.25.0

### What environment did it happen in?
Crossplane version: v1.6.4

Cloud provider: AWS
Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
