### ISSUE TITLE
Apigateway method does not seems to work 

### ISSUE THREAD

**Issue by YannickWeScale** [crossplane/provider-aws#1311]
### What happened?
With AWS provider 0.27.0, i am trying to deploy a method on a RestAPI : 
```
apiVersion: apigateway.aws.crossplane.io/v1alpha1
kind: Method
metadata:
  name: test-method
spec:
  deletionPolicy: Delete
  forProvider:
    authorizationType: NONE
    httpMethod: ANY
    region: eu-west-1
    restApiId: <apiID> 
  providerConfigRef:
    name: aws-provider
```
No event are generated, the resource is never deployed, not ready, not synced (no logs in aws provider pod) : 

<img width="322" alt="Capture d’écran 2022-05-17 à 15 47 03" src="https://user-images.githubusercontent.com/97600158/168826009-77ed2f90-74c0-4ace-9c23-78c13e50cc40.png">

This issue happens for domain name as well. 

### How can we reproduce it?
Deploy a method or a domain name on apigateway.aws.crossplane.io group version v1alpha1

### What environment did it happen in?
Crossplane version: 1.6.3 
AWS Provider : 0.27.0
Kubernetes version : v1.21.9-eks-0d102a7
Kubernetes distribution : EKS
