### ISSUE TITLE
securitygroup: Source group ID missing when using groupIdSelector

### ISSUE THREAD

**Issue by petteja** [crossplane/provider-aws#1312]
### What happened?
Reconciling failed when using group id selector in ingress rule on provider-aws-0.27. It is working on provider-aws-0.26.

### How can we reproduce it?
Create a securitygroup with label `sg: sg1`
```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    sg: sg1
  name: sg1
spec:
  deletionPolicy: Delete
  forProvider:
    description: 'sg1'
    egress:
    - fromPort: 443
      ipProtocol: tcp
      prefixListIds:
      - prefixListId: pl-c3aa4faa
      toPort: 443
    groupName: sg1
    region: eu-north-1
    vpcId: vpc-XXXXXXXXXX
  providerConfigRef:
    name: default
```
Create a new securitygroup with selector on the previous securitygroup using label selector on  `sg: sg1` .
```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: sg2
spec:
  deletionPolicy: Delete
  forProvider:
    description: 'sg2'
    groupName: sg2
    ingress:
    - fromPort: 5432
      ipProtocol: tcp
      toPort: 5432
      userIdGroupPairs:
      - description: sg1
        groupIdSelector:
          matchLabels:
            sg: sg1
    region: eu-north-1
    vpcId: vpc-XXXXXXXXXX
  providerConfigRef:
    name: default
```

This results in the following error on `sg2`:
`Message:               update failed: failed to authorize ingress rules: api error MissingParameter: Source group ID missing.`

### What environment did it happen in?
Crossplane version: 1.7.0
provider-aws: 0.27
