### ISSUE TITLE
Cannot create EKS instance or even see Debugging reports

### ISSUE THREAD

**Issue by ChrisJBurns** [crossplane/provider-aws#1318]
### What happened?
Am trying to get an EKS cluster and I am getting nothing showing in the AWS Console in addition to not seeing anything in Kubernetes either. I do a `kubectl get managed` and it gives me nothing but VPC and Subnets I created previously. I cannot even see errors in any of the crossplane controllers which suggests to me the controller config debugging option isn't working either. I cannot tell if it is a permissions issue or not since I cannot see a single log entry in either the crossplane pod, aws provider pod or the crossplane rbac pod.

### How can we reproduce it?
provider.yaml
```yaml
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-controller-config
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
  - '--debug'
  securityContext:
    runAsUser: 0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: "crossplane/provider-aws:v0.27.0"
  controllerConfigRef:
    name: aws-controller-config
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-creds
      key: creds
```

cluster.yaml
```yaml
---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: sample-cluster
  labels:
    example: "true"
spec:
  forProvider:
    region: eu-west-2
    # Defined in examples/iam
    # roleArnRef:
    #   name: somerole
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      # Defined in examples/ec2
      subnetIdRefs:
        - name: subnet-ID1
        - name: subnet-ID2
      # securityGroupIdRefs:
      #   - name: sample-cluster-sg
    version: "1.22"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: crossplane
  providerConfigRef:
    name: aws-provider-config
```

### What environment did it happen in?
Crossplane version: 
Crossplane Helm Chart version 1.7.1
EKS: 1.22
AWS

**Comment by chlunde** [comment]
what is the output of

```bash
kubectl create -f cluster.yaml
kubectl describe -f cluster.yaml
```

**Comment by ChrisJBurns** [comment]
@chlunde 

So, I've destroyed the cluster completely and gone back to my Composition example that is detailed [here](https://www.kloia.com/blog/production-ready-eks-cluster-with-crossplane), however I was hesitant on closing this before I can confirm it all works. I can confirm I see a cluster, but am just waiting for if the nodes are all registered.

I shall close if this is the case.

I've also managed to move towards the declarative provider and providerconfig method - instead of using the Helm chart. As for some reason, the providers kept overwriting my debug arg flag. It seems to be spitting out debug information now.

**Comment by ChrisJBurns** [comment]
I will close this, I'm still not entirely sure why it started working, but I think I can track it back to when I added the following into the Composition

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vpc.prodready.com
spec:
  writeConnectionSecretsToNamespace: crossplane
...
```

And the following into the CRD
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vpc.prodready.com
spec:
  connectionSecretKeys:
  - kubeconfig
....
```


The debug logging problem was solved when I destroyed the cluster and reprovisioned it with new providers that were applied via Git & FluxCD. Previous, it was a mix and match between what I was applying directly with `kubectl` and what I asked FluxCD to apply - so due to this, I think the providers were getting in a bit of a mess. Now it seems to work fine with regards to logging debugging output. The same YAML's that I pasted in the issue description are the same ones that now work. Just needed to wipe the slate clean with a new cluster.
