### ISSUE TITLE
EKS Cluster v1beta1

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#137]
### What problem are you facing?

EKSCluster resource is still v1alpha1.

### How could Crossplane help solve your problem?

Implement v1beta1 version with the following patterns: https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md

**Comment by rajalokan** [comment]
Hi I would like to work on this. My proposal for implementing this is to provide support for below API types:
- EKSCluster
- FargateProfile
- NodeGroup

Out of which EKSCluster is already implementated ( but using deprecated **Reconciler Pattern**). As part of this 

 [ ] I would be re-implementing `EKSCluster` managed resource but using **Managed Resource API Patter** as per this [doc](https://github.com/crossplane/crossplane/blob/55740990903809820f80cd8732db5fb07a565f33/design/one-pager-managed-resource-api-design.md). 
 [ ] Add support for `FargateProfile` managed resource. 
 [ ]  Add support for `NodeGroups` managed resource. Similar to `NodePool` of GKE. 

Please confirm if my understanding is correct or anything else I should care for. I've started with first item from above.

**Comment by rajalokan** [comment]
Adding to above please find each API Types below and review them. These are Parameter APIs. 

## EKS Cluster
```yaml
---
apiVersion: compute.aws.crossplane.io/v1beta1
kind: EKSCluster
metadata:
  name: example-eks-01
spec:
  providerRef:
    name: example

  # arn of cluster. Can this not be stored in Status object?
  arn: <string>

  # Base64-encoded certificate data required to communicate with your cluster.
  certificateAuthorityData: <Base64 encoded string>

  # Unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
  clientRequestToken: <string>

  # Unix epoch timestamp in seconds
  createdAt: <time.time>

  # encryption configuration for the cluster.
  encryptionConfig:
    # AWS KMS master key ARN
    providerARN: <string>
    # Secrets to be encrypted
    resources: <[]string>

  # The endpoint for your Kubernetes API server.
  endpoint: <string>

  # OIDC provider information for cluster
  identityIssuer: <string>

  # The name of the cluster.
  name: <string>

  # The platform version of your Amazon EKS cluster. (eks.1 | eks.2 etc)
  platformVersion: <string>

  # The cluster security group that was created by Amazon EKS for the cluster.
  clusterSecurityGroupID: <string>

  # This parameter indicates whether the Amazon EKS private API server endpoint is enabled.
  endpointPrivateAccess: <bool>

  # This parameter indicates whether the Amazon EKS public API server endpoint is enabled.
  endpointPublicAccess: <bool>

  # The CIDR blocks that are allowed access to your cluster's public Kubernetes API server endpoint.
  publicAccessCidrs: <[]string>

  # Different ways to provider VPC, subnet or securityGroups to your cluster
  securityGroupIDs: <[]string>
  securityGroupIDRefs: <[]string>
  securityGroupSelector: <string>
  subnetIDs: <[]string>
  subnetIDRefs: <[]string>
  subnetSelector: <string>
  vpcID: <string>
  vpcIDRef: <string>
  vpcIDSelector: <string>

  # The Amazon Resource Name (ARN) of the IAM role that provides permissions
  # for the Kubernetes control plane to make calls to AWS API operations on your
  # behalf.
  roleArn: <string>

  # Common key/value tag
  tags: <[]Tag>

  # The Kubernetes server version for the cluster.
  version: <string>
```

**Comment by rajalokan** [comment]
## NodeGroup API Type
```yaml
---
apiVersion: compute.aws.crossplane.io/v1beta1
kind: NodeGroup
metadata:
  name: example-nodegroup
spec:
  providerRef:
    name: aws-provider

  # The AMI type associated with your node group.
  amiType: <string>

  # The name of the eks cluster that the managed node group resides in
  # ??? No need to do referencing and resolving for Eks cluster ARN ?
  clusterName: <string>

  # The Unix epoch timestamp in seconds for when the managed node group was created.
  createdAt: <time.time>

  # The root device disk size (in GiB) for your node group instances.
  diskSize: <int64>

  # The instance types associated with your node group.
  instanceTypes: <[]string>

  # The Kubernetes labels applied to the nodes in the node group.
  lables: <map[string]string>

  # The Unix epoch timestamp in seconds for when the managed node group was last modified.
  modifiedAt: <time.time>

  # The IAM role associated with your node group.
  nodeRole: <string>

  # The Amazon Resource Name (ARN) associated with the managed node group.
  nodeGroupArn: <string>

  # The name associated with an Amazon EKS managed node group.
  nodeGroupName: <string>

  # The AMI version of the managed node group.
  releaseVersion: <string>

  # The remote access (SSH) configuration that is associated with the node group.
  remoteAccess:
    # The Amazon EC2 SSH key that provides access for SSH communication with the
    # worker nodes in the managed node group.
    keyPair: <string>
    # The security groups that are allowed SSH access (port 22) to the worker nodes.
    sourceSecurityGroups: <[]string>

  resources:
    # The Auto Scaling group names associated with the node group.
    autoScalingGroups: <[]string>
    # The remote access security group associated with the node group.
    remoteAccessSecurityGroup: <string>

  # Fields representing the scaling configuration details for the Auto Scaling
  # group that is associated with your node group
  desiredSize: <int64>
  maxSize: <int64>
  minSize: <int64>

  # The subnets allowed for the Auto Scaling group that is associated with your node group.
  subnets: []string

  # Common tags applied
  tags: []Tag

  # The Kubernetes version of the managed node group.
  version: string
```

**Comment by rajalokan** [comment]
## FargateProfile API Type
```yaml
---
apiVersion: compute.aws.crossplane.io/v1beta1
kind: FargateProfile
metadata:
  name: example-fargate-profile
spec:
  providerRef:
    name: aws-provider

  # ??? Question
  # Since we are using clusterName, no need to do do referencing and resolving
  # eks cluster ID.
  #
  # The name of the Amazon EKS cluster that the Fargate profile belongs to.
  clusterName: <string>

  # The Unix epoch timestamp in seconds for when the Fargate profile was created.
  createdAt: <time.time>

  # The full Amazon Resource Name (ARN) of the Fargate profile.
  fargateProfileArn: <string>

  # The name of the Fargate profile.
  fargateProfileName: <string>

  # The Amazon Resource Name (ARN) of the pod execution role to use for pods
  # that match the selectors in the Fargate profile.
  podExecutionRoleArn: <string>

  # The selectors to match for pods to use this Fargate profile.
  # This will be a list of labels + namespace combination.
  selectors:
      # The Kubernetes labels that the selector should match.
    - labels: map[string]string
      # The Kubernetes namespace that the selector should match.
      namespace: string
    - labels: ""
      namespace: ""

  # The IDs of subnets to launch pods into. An array of subnet IDs
  subnets: []string

  # An arry of Custom Tags.
  tags: []Tag
```
