### ISSUE TITLE
Custom Endpoints

### ISSUE THREAD

**Issue by Promaethius** [crossplane/provider-aws#199]
### What problem are you facing?
Deploying a Crossplane enabled Kubernetes in Private AWS VPCs that has custom service endpoints.

### How could Crossplane help solve your problem?
The AWS Golang SDK supports resolution for custom endpoints:

https://github.com/aws/aws-sdk-go/blob/9c9db07028aeb7d607e54b2b5aa97bbbbebcbbfd/service/s3/endpoint.go#L102
https://github.com/aws/aws-sdk-go/blob/4b8b821e1bcd8466b496d1856ea11b735e549e4c/models/endpoints/endpoints.json
https://github.com/aws/aws-sdk-go/blob/f26268b77ea9619d95b1d04b6f3e3c5a03b61110/example/aws/endpoints/customEndpoint/customEndpoint.go

Does provider-aws already support custom endpoints for services? If not, where would be a good entry-point for implementation?

**Comment by hasheddan** [comment]
Hi @Promaethius! Thanks for opening this issue :) I wanted to confirm I am following your desired feature here. Are you talking about private VPC endpoints? (ref: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html)

**Comment by Promaethius** [comment]
@hasheddan yes!

**Comment by hasheddan** [comment]
@Promaethius Nice! We do not currently support this, but one way to add this functionality would be to add an annotation to objects that indicate a private endpoint to use instead of the service default. Does that sound like a viable solution for your use-case? An example may look like:

```yaml
apiVersion: storage.aws.crossplane.io/v1alpha3
kind: S3Bucket
metadata:
  name: s3bucket-standard
  annotations:
    aws.crossplane.io/customendpoint: "my-custom-url.com"
spec:
  writeConnectionSecretsToRef:
    name: conn
    namespace: crossplane-system
  versioning: false
  cannedACL: private
  region: us-east-1
  localPermission: ReadWrite
  providerRef:
    name: example
  reclaimPolicy: Delete
```

**Comment by yogeek** [comment]
Hi @hasheddan , if it can be useful, here is my use case for VPC Endpoint / Endpoint Service :

I have a K8S cluster with Istio and 2 Istio ingress gateways : one is meant to be avalaible from internet for external customers, the other is only for internal services, not exposed externally but only for corporate access.
Today, to implement the second case, the ingress gateway istio k8s service is creating an AWS Network LoadBalancer when it is deployed, and then, I use terraform to create a VPC endpoint Service linked to this NLB, and a VPC Endpoint in a "corporate routed" VPC to be able to access the NLB with private IP from the corporate network.
Here is a schema :

```
Corporate Network ---> Route53 ---> Endpoint in VPC Corpo ---> EndpointService in K8S VPC ---> NLB ---> Istio ingress gateway service ---> Istio Gateway ---> Istio Virtual Service ---> Internal application k8s service
``` 

And it would be useful in this case to manage the "terraform" part with only K8S resources as crossplane does. And so to be able to create network resources like VPC Endpoints and EndpointServices with crossplane.

**Comment by davidmitchell2019** [comment]
Is it possible to use Crossplane AWS inside a VPC with no internet access? or is it possible to use it with a PROXY inside another VPC using a private link?

**Comment by muvaf** [comment]
> And it would be useful in this case to manage the "terraform" part with only K8S resources as crossplane does. And so to be able to create network resources like VPC Endpoints and EndpointServices with crossplane.

I believe we need two managed resources to be implemented, `VPCEndpoint` and `VPCEndpointService`. @yogeek @Promaethius  Are you interested in contributing? I haven't looked into them very deeply but I can tell their complexity is similar to PubSub Topic we [implemented during a TBS](https://www.youtube.com/watch?v=rvQ8N0u3rkE). Also, [Managed Resource Developer Guide](https://crossplane.io/docs/master/contributing/services_developer_guide.html) is a good document for starters. You can ask your questions in Crossplane Slack and we'd be happy to help.

> Is it possible to use Crossplane AWS inside a VPC with no internet access? or is it possible to use it with a PROXY inside another VPC using a private link? No internet access from the cluster where Crossplane is running except through a proxy in another VPC, that is linked using private link.

@davidmitchell2019 The internet connection is needed only to call cloud provider APIs. I believe it should work as long as the proxy environment variables are defined. For example, looking at [AWS SDK doc](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html), I see that the only requirement is to define `HTTP_PROXY` environment variable. However, the caveat is that Crossplane package manager doesn't support supplying arbitrary env vars AFAIK @hasheddan could confirm. So I opened https://github.com/crossplane/crossplane/issues/1638 as feature request to be incorporated into the ongoing [package manager refactor design](https://github.com/crossplane/crossplane/pull/1616).

**Comment by muvaf** [comment]
@yogeek @Promaethius feel free to open separate issues for `VPCEndpoint` and `VPCEndpointService` resources and assign to yourself if you'd like to.

**Comment by hasheddan** [comment]
@muvaf it is possible to add environment variables when building a package, but not at install time. For instance, we could do the following:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-aws
  labels:
    core.crossplane.io/name: "provider-aws"
spec:
  selector:
    matchLabels:
      core.crossplane.io/name: "provider-aws"
  replicas: 1
  template:
    metadata:
      name: "provider-aws-controller"
      labels:
        core.crossplane.io/name: "provider-aws"
    spec:
      securityContext:
        # TODO(hasheddan): this can be removed when there is no desire
        # to support pre-v1.19 Kubernetes clusters
        # https://github.com/kubernetes/enhancements/pull/1598
        # https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8
        fsGroup: 65534
      containers:
      - name: "provider-aws-controller"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
         # Added HTTP
        - name: HTTP_PROXY
          value: my.cool.proxy
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

This is definitely something we should consider as part of the design for packages. We will need some sort of pass through configuration, but this will also make updates and dependency resolution potentially more complicated.
