### ISSUE TITLE
improve user experience for IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#212]
### What problem are you facing?
Currently IAM Roles for Service Accounts (IRSA) require quite some manual tinkering: https://github.com/crossplane/provider-aws/blob/master/AUTHENTICATION.md#steps

The steps are probably ok for setting up `provider-aws` itself, but for `KubernetesApplications` or applications directly installed into the target cluster it would be nice to make the provisioning easier.

Examples: 
- argocd (to connect to EKS)
- velero (S3, EBS)
- aws ebs-csi-driver (EBS)

### How could Crossplane help solve your problem?
Crossplane can enable the OIDC provider for an EKS cluster and create the corresponding IAM role with the trust relationship (if it knows about SERVICE_ACCOUNT_NAMESPACE and SERVICE_ACCOUNT_NAME)

**Comment by janwillies** [comment]
Now that eks-v1beta1 support has arrived (thanks @hasheddan!) there's is an OIDC field available which helps a lot. 

IRSA Setup is described here: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

One solution might be to write an `irsa-controller` which does the following:
1. Watch for new CRs of type `EKSCluster`
4. Create `IAMRole` with `assumeRolePolicyDocument` trust relationship
2. Create `IAMPolicy` with whatever AWS permissions the target app needs
3. Create `IAMRolePolicyAttachment` and reference `IAMRole` and `IAMPolicy` (#232)
5. Create `KubernetesApplication` with Namespace and KSA (including annotations) to be scheduled to target EKS Cluster

Some information is needed in advance and is used in different places:
- OIDC URL from target EKS Cluster
  - obtainable from: `EKSCluster` CR
  - used in:
    - AWS Trust Relationship policy
- AWS Account ID
  - obtainable from: `EKSCluster` CR (but could also be cross-account)
  - used in:
    - AWS Trust Relationship policy
    - KSA Annotation in target EKS Cluster (`eks.amazonaws.com/role-arn=arn:aws:iam::$AWS_ACCOUNT_ID:role/$IAM_ROLE_NAME`)
- IAM Role Name
  - created by proposed `irsa-controller` (but could be deterministic naming, e.g `<EKSCluster>-<Namespace>-<KSA>`)
  - used in:
    - KSA Annotation in target EKS Cluster (`eks.amazonaws.com/role-arn=arn:aws:iam::$AWS_ACCOUNT_ID:role/$IAM_ROLE_NAME`)
- Kubernetes Service Account Name in target EKS Cluster
  - depends on the application (e.g. `thanos`, `velero`, `argocd`, ...)
  - obtainable from: 
  - used in:
    - AWS Trust Relationship policy
- Kubernetes Namespace of the KSA in target EKS Cluster
  - depends on the application (e.g. `logging`, `monitoring`, `backup`, ...)
  - obtainable from:
  - used in:
    - AWS Trust Relationship policy

Some thoughts:
- how to obtain the names of Namespaces and KSAs. Environment CRD? 
- how to keep the actual IAM permissions out of the irsa-controller. crossplane classes and instances (soon to be deprecated)?

**Comment by muvaf** [comment]
> 1. Watch for new CRs of type `EKSCluster`
> 2. Create `IAMRole` with `assumeRolePolicyDocument` trust relationship
> 3. Create `IAMPolicy` with whatever AWS permissions the target app needs
> 4. Create `IAMRolePolicyAttachment` and reference `IAMRole` and `IAMPolicy` (#232)
> 5. Create `KubernetesApplication` with Namespace and KSA (including annotations) to be scheduled to target EKS Cluster

I think the first 4 can be achieved with composition. You'd create a `Composition` with `EKSCluster`, `IAMPolicy`, `IAMRole` and `IAMRolePolicyAttachment` that refer to each other.

I see that the `ServiceAccount` that needs to be created in the `EKSCluster` is something like this:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$AWS_ACCOUNT_ID:role/$IAM_ROLE_NAME
```

And composition doesn't support templating like Helm where you can get a value from one of the resources and put it into another one via in-place template like `{{ .FromThatResource.IAMRoleName }}`. Maybe we can open an issue saying that we should be able to refer to other resources in the composition in a way that allows raw string propagation. Current cross-resource reference relies on selectors to choose the one that belongs to the same composition.

**Comment by janwillies** [comment]
thanks, I'll take a closer look at composition!

Re templating: I think `IAMRole` needs a value from `EKSCluster` too ( namely `status.atProvider.identity.oidc.issuer` for the trust policy)

**Comment by muvaf** [comment]
@janwillies We were talking about propagation of values from the composed resources to the composite (https://github.com/crossplane/crossplane/issues/1639) status or annotations/labels with @negz . I think when we get that feature landed, then these raw templating will be much easier. For example, you could have a patch where you send `status.atProvider.identity.oidc.issuer` of EKSCluster to `status`, `labels` or `annotations`, actually even `spec`. Then in the `IAMRole` patches you could have something like:
```yaml
- fromFieldPath: "status.issuer" # this value in composite resource is actually filled by EKSCluster through a reverse patch.
  toFieldPath: "spec.theFieldThatNeedsIssuer"
  transforms:
  - type: string
    string:
      fmt: "some-special-%s-string"
```

Essentially, composite resource keeps to be the source of truth and common ground for all composed resources but with back propagation, composed resources will be able to contribute to that source of truth alongside the user.

**Comment by Smana** [comment]
Looking forward to testing this as we're heavy users of IRSA for our apps. Currently, we're using this [terraform module](https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-assumable-role-with-oidc) and we're looking for a better user experience, preferably with Crossplane but there's also the ongoing project [aws-controllers-k8s/iam-controller](https://github.com/aws-controllers-k8s/iam-controller).

**Comment by Smana** [comment]
@janwillies Hi, were you able to build an IRSA for an application ?

**Comment by janwillies** [comment]
Yes, with crossplane-1.6 it will be possible. However the application needs to be part of the eks composition. At least until generic referencers are implemented: https://github.com/crossplane/crossplane/issues/1770

**Comment by Smana** [comment]
> Yes, with crossplane-1.6 it will be possible. However the application needs to be part of the eks composition. At least until generic referencers are implemented: [crossplane/crossplane#1770](https://github.com/crossplane/crossplane/issues/1770)

Ok thank you, I wanted to avoid having to put it in the EKS composition. My goal was to start using Crossplane for IRSA only at the beginning in order to convince everyone in my company, then progressively migrate a few things out from Terraform.

**Comment by Smana** [comment]
Hi @janwillies ,

Could you please provide an example on how you build IRSA on your side ?
I'm struggling with a formatting issue like:

```yaml
        - type: CombineToComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.OIDCProvider
              - fromFieldPath: spec.parameters.OIDCProvider
              - fromFieldPath: spec.metadata.namespace
              - fromFieldPath: spec.parameters.serviceAccountName
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement":
                    [
                      {
                        "Effect": "Allow",
                        "Principal":
                          {
                            "Federated": "arn:aws:iam::xx:oidc-provider/%s",
                          },
                        "Action": "sts:AssumeRoleWithWebIdentity",
                        "Condition":
                          {
                            "StringLike":
                              {
                                "%s:sub": "system:serviceaccount:%s:%s",
                              },
                          },
                      },
                    ],
                }
          toFieldPath: spec.forProvider.assumeRolePolicyDocument
```

I probably did something wrong because I get an error.

```console
failed to create the IAMRole resource: api error ValidationError: The specified value for assumeRolePolicyDocument is invalid. It must contain only printable ASCII characters
```

Note that for a first step, it doesn't matter for me to hardcode the OIDC provider because I will start with a crossplane instance per cluster.
Thank you

**Comment by haarchri** [comment]
in eks Cluster resource we using `TrimPrefix` to remove leading `https://`

```yaml
    - name: EKS-Cluster
      base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
[...]
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.identity.oidc.issuer
          toFieldPath: status.eks.iamoidc
          transforms:
            - type: string
              string:
                type: TrimPrefix
                trim: 'https://'
          policy:
            fromFieldPath: Optional
[...]
```


```yaml
    - name: IAM-Role
      base:
        apiVersion: identity.aws.crossplane.io/v1beta1
        kind: IAMRole
        spec:
          forProvider:
[...]
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.labels[tags.crossplane.io/account]
              - fromFieldPath: status.eks.iamoidc
              - fromFieldPath: status.eks.iamoidc
              - fromFieldPath: spec.metadata.namespace
              - fromFieldPath: spec.parameters.serviceAccountName
            strategy: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::%s:oidc-provider/%s"
                      },
                      "Action": "sts:AssumeRoleWithWebIdentity",
                      "Condition": {
                        "StringLike": {
                          "%s:sub": "system:serviceaccount:%s:%s"
                        }
                      }
                    }
                  ]
                }
          toFieldPath: spec.forProvider.assumeRolePolicyDocument
          policy:
            fromFieldPath: Required
```
