### ISSUE TITLE
AWSServiceRoleForAmazonEKS, could not be assumed because it does not exist or the trusted entity is not correct

### ISSUE THREAD

**Issue by prasek** [crossplane/provider-aws#218]
### Problem
`EKSCluster` fails to provision with 
```
status:
  conditions:
    - lastTransitionTime: '2020-05-12T19:28:58Z'
      message: "InvalidParameterException: Role with arn: arn:aws:iam::609897127049:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS, could not be assumed because it does not exist or the trusted entity is not correct\n\tstatus code: 400, request id: efc63924-3e8b-4f30-b6b2-0809a614918c"
      reason: Encountered an error during resource reconciliation
      status: 'False'
      type: Synced
```

Using:
- Wordpress v0.5.0-rc.6.g7ac7d7a
- AWS Provider v0.10.0-rc.2.g5ee25e7
- AWS Sample Stack v0.6.0-rc.2.g83df171 
- Crossplane 0.10.0

<details><summary>EKSCluster resoure</summary>
apiVersion: compute.aws.crossplane.io/v1alpha3
kind: EKSCluster
metadata:
  annotations:
    crossplane.io/external-name: cy-wp70757
  creationTimestamp: '2020-05-12T17:43:17Z'
  finalizers:
    - finalizer.eks.compute.aws.crossplane.io
  generateName: cy-wrk70757-cy-wp70757-cluster-
  generation: 2060
  name: cy-wrk70757-cy-wp70757-cluster-bvfqw
  resourceVersion: '435088'
  selfLink: >-
    /apis/compute.aws.crossplane.io/v1alpha3/eksclusters/cy-wrk70757-cy-wp70757-cluster-bvfqw
  uid: 56360feb-dca8-46a0-8e07-c16e9915b82f
spec:
  claimRef:
    apiVersion: compute.crossplane.io/v1alpha1
    kind: KubernetesCluster
    name: cy-wp70757-cluster
    namespace: cy-wrk70757
    uid: 869598c2-ae66-49bb-8e61-e8209c19c97c
  classRef:
    apiVersion: compute.aws.crossplane.io/v1alpha3
    kind: EKSClusterClass
    name: cy-aws70757-ekscluster
    uid: 705461d3-b509-46fd-a8ff-31dfb5091595
  providerRef:
    name: cy-aws70757-aws-provider
  reclaimPolicy: Delete
  region: us-east-1
  roleARN: 'arn:aws:iam::609897127049:role/cy-aws70757-iamrole'
  roleARNRef:
    name: cy-aws70757-iamrole
  securityGroupIdRefs:
    - name: cy-aws70757-eks-security-group
  securityGroupIds:
    - sg-0d5d5ee790ecf0033
  subnetIdRefs:
    - name: cy-aws70757-subnet-a
    - name: cy-aws70757-subnet-b
    - name: cy-aws70757-subnet-c
  subnetIds:
    - subnet-08c9df6cd390f750c
    - subnet-05c901daf121eae7c
    - subnet-063b0c72fc82b8a7c
  vpcId: vpc-0c6bcd6b9ffa659c9
  vpcIdRef:
    name: cy-aws70757-vpc
  workerNodes:
    clusterControlPlaneSecurityGroup: sg-0d5d5ee790ecf0033
    clusterControlPlaneSecurityGroupRef:
      name: cy-aws70757-eks-security-group
    nodeAutoScalingGroupMaxSize: 1
    nodeAutoScalingGroupMinSize: 1
    nodeGroupName: nodegroup
    nodeInstanceType: t3.small
  writeConnectionSecretToRef:
    name: 869598c2-ae66-49bb-8e61-e8209c19c97c
    namespace: crossplane-system
status:
  conditions:
    - lastTransitionTime: '2020-05-12T19:28:58Z'
      message: "InvalidParameterException: Role with arn: arn:aws:iam::609897127049:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS, could not be assumed because it does not exist or the trusted entity is not correct\n\tstatus code: 400, request id: efc63924-3e8b-4f30-b6b2-0809a614918c"
      reason: Encountered an error during resource reconciliation
      status: 'False'
      type: Synced
    - lastTransitionTime: '2020-05-12T18:14:58Z'
      reason: Resource is being created
      status: 'False'
      type: Ready
</details>
