### ISSUE TITLE
Creating an aurora-postgresql RDSInstance fails with MasterUsername missing

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#246]
### What happened?
Applying an RDSInstance manifest with engine `aurora-postgresql` leads to weird issues:
```
cannot create RDS instance: InvalidParameterValue: The parameter MasterUsername must be provided and must not be blank.
```
According to the docs, the setting does not apply to aurora (https://github.com/aws/aws-sdk-go-v2/blob/v0.18.0/service/rds/api_op_CreateDBInstance.go#L478-L482)

When I supply the masterUsername, it complains about other missing values, which should not be necessary (according to the docs).

```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: foo-rds-aurora
spec:
  forProvider:
    dbName: foo
    dbInstanceClass: db.t3.medium
    dbSubnetGroupName: abc
    engine: aurora-postgresql
    licenseModel: postgresql-license
    publiclyAccessible: false
    port: 5432
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    name: foo-rds-aurora
    namespace: crossplane-system
```

When I try to create an aurora-postgres instance via the AWS Management Console, I need to input all the values (which according to the docs should not be necessary)
