### ISSUE TITLE
Creating an aurora-mysql RDSInstance fails with allocatedStorage, dbInstanceClass missing bug

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#267]
### What happened?
Crossplane throwing an error when spinning aurora based DB, basically I would like to spin up DB that has read replicas and that is why I am chossing engine type aurora and aurora-mysql. 

According to the provider-aws RDSInstance api doc, those field such as allocateStorage and dbInstanceClass is not required for aurora based DB.

So i did try without putting any of these 2 fields and i am hitting into parameters validation issue mentioning that those fields are required

And the i put in those variables to test and i am running into another issue:

```
Warning  CannotCreateExternalResource  27s (x15 over 34s)  managed/rdsinstance.database.aws.crossplane.io  (combined from similar eve
nts): cannot create RDS instance: InvalidParameterCombination: Invalid storage size for engine name oscar and storage type aurora: 20
           status code: 400, request id: af92dcd3-3d74-42ac-985c-606cb8976c33
```

**Wierd thing is the log showing engine name transform to oscar, and storage type is aurora which is not defined anywhere in my manifests**

### How can we reproduce it?

- Just a snippet of what are the Composition file:

```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: mysqlinstances.crd.aws.mydomain.com
  labels:
    provider: aws
    tier: default
    vpc: dev
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: crd.aws.mydomain.com/v1alpha1
    kind: MySQLInstance
  to:
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            masterUsername: masteruser
            engine: aurora
            allocatedStorage: 20
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: true
            deletionProtection: false
            dbClusterParameterGroupName: "mydbclusterparametergroup" 
          writeConnectionSecretToRef:
            namespace: crossplane-system
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-mysql"
        - fromFieldPath: "spec.parameters.size"
          toFieldPath: "spec.forProvider.dbInstanceClass"
        - fromFieldPath: "spec.parameters.version"
          toFieldPath: "spec.forProvider.engineVersion"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
```

- Requirement file:

```
apiVersion: crd.aws.mydomain.com/v1alpha1
kind: MySQLInstanceRequirement
metadata:
  name: mysql-db1
  namespace: crossplane-tenant
spec:
  parameters:
    size: db.t2.small
    version: "5.6.10a"
    secretName: mydb-secret 
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: dev
      tier: default
  writeConnectionSecretToRef:
    name: mydb-conn
```

### What environment did it happen in?
Crossplane version: 0.11.1

* Cloud provider or hardware configuration: AWS EKS
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c301
66b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z"
, GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCo
mmit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-2
7T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
