### ISSUE TITLE
Redis ReplicationGroup never finishes

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#277]
### What happened?

I created a composition for launching redis in a replication group using the ReplicationGroup kind. Everything was created except for the final secret which would be propagated to the namespace of the requirement. The reason seems to be the ReplicationGroup is stuck in a modifying state even though in the AWS console the ReplicationGroup is completely provisioned and ready to roll. 

### How can we reproduce it?

Create a replication group using a composition. 

### What environment did it happen in?
Crossplane version: v0.12.0

Here is the status it is stuck in:
```yaml
status:
  atProvider:
    automaticFailoverStatus: enabled
    configurationEndpoint: {}
    memberClusters:
    - redis-8687w-001
    - redis-8687w-002
    - redis-8687w-003
    nodeGroups:
    - nodeGroupMembers:
      - cacheClusterId: redis-8687w-001
        cacheNodeId: "0001"
        currentRole: primary
        preferredAvailabilityZone: us-west-2c
        readEndpoint:
          address: redis-789.foo.usw2.cache.amazonaws.com
          port: 6379
      - cacheClusterId: redis-8687w-002
        cacheNodeId: "0001"
        currentRole: replica
        preferredAvailabilityZone: us-west-2b
        readEndpoint:
          address: redis-456.bar.usw2.cache.amazonaws.com
          port: 6379
      - cacheClusterId: redis-8687w-003
        cacheNodeId: "0001"
        currentRole: replica
        preferredAvailabilityZone: us-west-2a
        readEndpoint:
          address: redis-123.baz.usw2.cache.amazonaws.com
          port: 6379
      port: "0001"
      primaryEndpoint: {}
      status: available
    pendingModifiedValues:
      resharding:
        slotMigration:
          progressPercentage: 0
    status: modifying
  bindingPhase: Unbound
  conditions:
  - lastTransitionTime: "2020-07-10T19:06:29Z"
    reason: Successfully reconciled resource
    status: "True"
    type: Synced
  - lastTransitionTime: "2020-07-10T19:25:48Z"
    reason: Resource is not available for use
    status: "False"
    type: Ready
```

**Comment by kferrone** [comment]
I'm getting a similar issue with RDS now.
This happens after MySQL has been up for a while:
```yaml
conditions:
  - lastTransitionTime: "2020-07-13T15:02:15Z"
    message: "update failed: cannot modify RDS instance: InvalidParameterCombination:
      No modifications were requested\n\tstatus code: 400, request id: 5b3cc217-58ad-45bb-9482-1b13f59d8aae"
    reason: Encountered an error during resource reconciliation
    status: "False"
    type: Synced
  - lastTransitionTime: "2020-07-10T16:09:28Z"
    reason: Resource is available for use
    status: "True"
    type: Ready
```

**Comment by kferrone** [comment]
Here is my exact setup to recreate:
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: redisinstances.foo.bar
  labels:
    category: cache
    provider: aws
    stack: foo
spec:
  from:
    apiVersion: foo.bar/v1alpha1
    kind: RedisInstance
  reclaimPolicy: Delete
  writeConnectionSecretsToNamespace: ci
  to:
  - base:
      apiVersion: cache.aws.crossplane.io/v1beta1
      kind: ReplicationGroup
      metadata: {}
      spec:
        forProvider:
          replicationGroupDescription: A custom made redis
          applyModificationsImmediately: true
          cacheNodeType: cache.t3.medium
          engine: redis
          engineVersion: 5.0.6
          numCacheClusters: 3
          # numNodeGroups: 2
          # replicasPerNodeGroup: 2
          port: 6379
          securityGroupIdRefs:
          - name: ""
          cacheSubnetGroupName: ""
          automaticFailoverEnabled: true
          cacheParameterGroupName: default.redis5.0
        providerRef:
          name: crossplane-aws-provider
        reclaimPolicy: Delete
    connectionDetails:
    - fromConnectionSecretKey: endpoint
      # name: REDIS_HOST
    - fromConnectionSecretKey: port
      # name: REDIS_PORT
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name

    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
      - type: string
        string:
          fmt: "%s-redis"

    - fromFieldPath: spec.writeConnectionSecretToRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace

    - fromFieldPath: spec.parameters.instanceClass
      toFieldPath: spec.forProvider.cacheNodeType

    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.securityGroupIdRefs[0].name

    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.cacheSubnetGroupName

    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.forProvider.engineVersion

    - fromFieldPath: spec.parameters.numNodeGroups
      toFieldPath: spec.forProvider.numNodeGroups
  - base:
      apiVersion: cache.aws.crossplane.io/v1alpha1
      kind: CacheSubnetGroup
      metadata: {}
      spec:
        forProvider:
          description: The isolated subnets for redis
          subnetIdSelector:
            matchLabels:
              stack: foo
              type: isolated
        providerRef:
          name: crossplane-aws-provider
        reclaimPolicy: Delete
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: SecurityGroup
      metadata: {}
      spec:
        description: The isolated security group for redis
        egress:
        - cidrBlocks:
          - cidrIp: 0.0.0.0/0
            description: Any IP address.
          fromPort: -1
          protocol: "-1"
          toPort: -1
        groupName: ""
        ingress:
        - cidrBlocks:
          - cidrIp: 10.101.0.0/16
            description: The cidr from the vpc only.
          fromPort: 6379
          protocol: tcp
          toPort: 6379
        providerRef:
          name: crossplane-aws-provider
        reclaimPolicy: Delete
        vpcIdRef:
          name: foo-vpc
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
    - fromFieldPath: metadata.name
      toFieldPath: spec.groupName
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: redisinstances.foo.bar
  labels:
    category: cache
    provider: aws
    stack: foo
spec:
  connectionSecretKeys:
  - endpoint
  - port
  crdSpecTemplate:
    group: foo.bar
    version: v1alpha1
    names:
      kind: RedisInstance
      listKind: RedisInstanceList
      plural: redisinstances
      singular: redisinstance
    validation:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              parameters:
                properties:
                  instanceClass:
                    type: string
                  numNodeGroups:
                    type: integer
                  version:
                    type: string
                required: []
                type: object
            type: object
        type: object
  defaultCompositionRef:
    name: redisinstances.foo.bar
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: redisinstances.foo.bar
  labels:
    category: cache
    provider: aws
    stack: foo
spec:
  infrastructureDefinitionRef:
    name: redisinstances.foo.bar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisinstances.foo.bar
  labels:
    category: cache
    provider: aws
    stack: foo
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - foo.bar
  resources:
  - redisinstances
  - redisinstances/status
  - redisinstancerequirements
  - redisinstancerequirements/status
  verbs:
  - '*'
```

**Comment by muvaf** [comment]
Hi @kferrone ! I was able to reproduce the issue for `ReplicationGroup` and opened a PR to address the problem https://github.com/crossplane/provider-aws/pull/284

Could you post your `RDSInstance` YAML so that I try to reproduce the problem?

**Comment by kferrone** [comment]
Here is my instance I have running at the moment:
```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/external-name: mysql-123456
  name: mysql-123456
spec:
  forProvider:
    FinalDBSnapshotIdentifier: ""
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    availabilityZone: us-west-2b
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t3.medium
    dbSubnetGroupName: mysql-123456
    dbSubnetGroupNameRef:
      name: mysql-123456
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mysql
    engineVersion: 5.6.35
    finalDBSnapshotIdentifier: mysql-123456
    licenseModel: general-public-license
    masterUsername: admin
    monitoringInterval: 5
    monitoringRoleArn: arn:aws:iam::123456789:role/mysql-123456
    monitoringRoleArnRef:
      name: mysql-123456
    multiAZ: true
    port: 3306
    preferredBackupWindow: 06:15-06:45
    preferredMaintenanceWindow: sat:09:21-sat:09:51
    publiclyAccessible: false
    storageEncrypted: false
    storageType: gp2
    tags:
    - key: crossplane-kind
      value: rdsinstance.database.aws.crossplane.io
    - key: crossplane-name
      value: mysql-123456
    - key: crossplane-provider
      value: crossplane-aws-provider
    vpcSecurityGroupIDRefs:
    - name: mysql-123456
    vpcSecurityGroupIds:
    - sg-someid
  providerRef:
    name: crossplane-aws-provider
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    name: 66258c8a-24ad-45e6-a79e-1d54c19d908c-mysqlserver
    namespace: ci
status:
  atProvider:
    dbInstanceArn: arn:aws:rds:us-west-2:123456789:db:mysql-123456
    dbInstanceStatus: available
    dbParameterGroups:
    - dbParameterGroupName: default.mysql5.6
      parameterApplyStatus: in-sync
    dbResourceId: db-someid
    dbSubnetGroup:
      dbSubnetGroupDescription: Selects the isolated subnets for RDS.
      dbSubnetGroupName: mysql-123456
      subnetGroupStatus: Complete
      subnets:
      - subnetAvailabilityZone:
          name: us-west-2c
        subnetIdentifier: subnet-someid
        subnetStatus: Active
      - subnetAvailabilityZone:
          name: us-west-2a
        subnetIdentifier: subnet-someid
        subnetStatus: Active
      - subnetAvailabilityZone:
          name: us-west-2b
        subnetIdentifier: subnet-someid
        subnetStatus: Active
      vpcId: vpc-someid
    endpoint:
      address: mysql-123456.someid.us-west-2.rds.amazonaws.com
      hostedZoneId: someid
      port: 3306
    enhancedMonitoringResourceArn: arn:aws:logs:us-west-2:123456789:log-group:RDSOSMetrics:log-stream:db-bigid
    instanceCreateTime: "2020-07-10T15:57:43Z"
    optionGroupMemberships:
    - optionGroupName: default:mysql-5-6
      status: in-sync
    pendingModifiedValues:
      pendingCloudwatchLogsExports: {}
    secondaryAvailabilityZone: us-west-2a
    vpcSecurityGroups:
    - status: active
      vpcSecurityGroupId: sg-someid
  bindingPhase: Unbound
  conditions:
  - lastTransitionTime: "2020-07-13T20:00:49Z"
    message: "update failed: cannot modify RDS instance: InvalidParameterCombination:
      No modifications were requested\n\tstatus code: 400, request id: someid"
    reason: Encountered an error during resource reconciliation
    status: "False"
    type: Synced
  - lastTransitionTime: "2020-07-10T16:09:28Z"
    reason: Resource is available for use
    status: "True"
    type: Ready
```
