### ISSUE TITLE
VPC doesn't populate name tag when used in composition

### ISSUE THREAD

**Issue by enderv** [crossplane/provider-aws#283]
## What happened?
Expected the name for vpc to be populated with the composition resource name the same way other resources get the composition resource name.
### How can we reproduce it?
Edited the yaml to remove alot of specific information but this should be good to reproduce.

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: vpc.example.com
spec:
  crdSpecTemplate:
    group: example.com
    version: v1alpha1
    names:
      kind: VPC
      listKind: VPClist
      plural: vpcs
      singular: vpc
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  provider:
                    type: string
                  vpccidr:
                    type: string
                required:
                  - provider
            required:
              - parameters
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpc.example.com
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - cloud.ea.com
  resources:
  - cfvpcs
  - cfvpcs/status
  - cfvpcrequirements
  - cfvpcrequirements/status
  verbs:
  - "*"
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: vpc-use1
  labels:
    purpose: example
    provider: aws
    region: us-east-1
spec:
  # matches def
  from:
    apiVersion: example.com/v1alpha1
    kind: vpc
  to:
  - base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: VPC
      metadata:
        labels:
          region: us-east-1
      spec:
        forProvider:
          tags:
            - key: composition
              value: cfvpc
          cidrBlock: 172.16.0.0/16
          enableDnsSupport: true
          enableDnsHostNames: true
          reclaimPolicy: Delete
    patches:
    - fromFieldPath: "metadata.labels"
      toFieldPath: "metadata.labels"
    - fromFieldPath: "metadata.annotations"
      toFieldPath: "metadata.annotations"
    - fromFieldPath: "spec.parameters.provider"
      toFieldPath: "spec.providerRef.name"   
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  # InfrastructurePublications must use the same name as the
  # InfrastructureDefinition that defines the resource they publish.
  name:  vpcs.example.com
spec:
  infrastructureDefinitionRef:
    name:  vpcs.example.com
---
apiVersion: example.com/v1alpha1
kind: VPCRequirement
metadata:
  name: test-vpc
spec:
  parameters:
    provider: aws-provider-use1
  compositionRef:
    name: vpc-use1
```

### What environment did it happen in?
Crossplane version: 0.12.0
AWS Provider version was from node group PR branch as I was experimenting with that at the time(https://github.com/crossplane/provider-aws/pull/254)

**Comment by muvaf** [comment]
Hi @enderv ! I couldn't get what you were expecting exactly? Do you mean you were expecting the name of the `VPC` resource to be `test-vpc`, i.e. same name as the requirement type?

**Comment by enderv** [comment]
Yeah I didn't do a good job of explaining. So say VPC resource `test-vpc-64pww` gets created. I would expect to be able to go into the AWS console and see a VPC with name `test-vpc-64pww`. Right now the VPC will show as unnamed but has the tag `crossplane-name: test-vpc-64pww`.

**Comment by muvaf** [comment]
Oh, got it. AWS VPC menu shows a column called `Name` but that's actually just a tag on the resource, i.e. the actual VPC object doesn't have a `name` field. For example, if you look at AWS CLI [vpc creation method](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpc.html), there is no name. But if you add a tag with key `Name` then it'll fill up that column.

As you see, we populate a few tags automatically but there is no hard-coded mechanism specific for `Name` tag. However, you can propagate it down from the composite resource, like:
```
tags:
- key: Name
  value: ""
...
patches:
- fromFieldPath: metadata.name
  toFieldPath: spec.forProvider.tags[0].value
```
