### ISSUE TITLE
AWS RDS keeps saying "no modifications were requested"

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#285]
### What happened?

AWS RDS resource gets into a state where its status condition always says `no modifications were requested`, which is an indicator of unnecessary update request. Original bug report: https://github.com/crossplane/provider-aws/issues/277#issuecomment-657764312

### How can we reproduce it?

Following is the YAML with many parts borrowed from @kferrone 's YAML in https://github.com/crossplane/provider-aws/issues/277#issuecomment-657764312:
```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: muvaf-test-1
spec:
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t3.medium
    dbSubnetGroupNameRef:
      name: test-dbsubnetgroup
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mysql
    engineVersion: 5.6.35
    finalDBSnapshotIdentifier: muvaf-test
    licenseModel: general-public-license
    masterUsername: admin
    monitoringInterval: 5
    monitoringRoleArnRef:
      name: test-iamrole
    multiAZ: true
    port: 3306
    preferredBackupWindow: 06:15-06:45
    preferredMaintenanceWindow: sat:09:21-sat:09:51
    publiclyAccessible: false
    storageEncrypted: false
    storageType: gp2
    vpcSecurityGroupIDRefs:
      - name: test-rds-security-group
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  writeConnectionSecretToRef:
    name: 66258c8a-24ad-45e6-a79e-1d54c19d908c-mysqlserver
    namespace: crossplane-system
```

### What environment did it happen in?
Crossplane version: v0.12.0
Provider AWS: v0.10.0
