### ISSUE TITLE
Not possible to delete SecurityGroup

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#301]
### What happened?
I created a `SecurityGroup` successfully but I am not able to delete it. It disappears from crossplane, but the `SecurityGroup` is still present at AWS

### How can we reproduce it?
Create the following `SecurityGroup` and then try do delete it:
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: f00bar
spec:
  forProvider:
    description: allow access to eks control plane
    groupName: f00bar
    ingress:
    - fromPort: 443
      toPort: 443
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 192.168.0.0/24
        description: f00bar
    vpcId: vpc-123456
  providerRef:
    name: provider-aws
```
### What environment did it happen in?
Crossplane version: 
crossplane: v0.12.0-6.g47acf6f
provider-aws: 778a71cc241103b48ea4ff3d12bf0aea7a92bfb7

**Comment by hasheddan** [comment]
@janwillies thanks for opening this? Have you just started observing this behavior in recent commits? There was a recent fix merged that is included at the commit hash you reference above. However, it did not touch the delete logic so I would not expect it to affect this.

**Comment by janwillies** [comment]
Indeed this is new behaviour. I'm not sure when it was introduced, but it definitely worked before.

**Comment by janwillies** [comment]
We noticed first with the latest release, and then updated to master to verify if it was actually fixed by the commit from @muvaf (but it wasn't)

**Comment by hasheddan** [comment]
@janwillies thanks :+1: Could you try creating again and making sure that the external name annotation is set? My immediate suspicion is that it is somehow making the `Delete` call with the wrong value, and then ignoring the "not found" error, but I am not certain:

https://github.com/crossplane/provider-aws/blob/778a71cc241103b48ea4ff3d12bf0aea7a92bfb7/pkg/controller/ec2/securitygroup/controller.go#L271

**Comment by janwillies** [comment]
The kubernetes object has the external-name annotation set correctly as far as I can tell:

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    crossplane.io/external-name: sg-04c4eaec188a4bb5e
[...]
```
