### ISSUE TITLE
Integrate AWS Identity with EKS Auth

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#302]
### What problem are you facing?
There is no declarative way of mapping IAM resources to the EKS aws-auth ConfigMap. When creating any of the resources from `identity.aws.crossplane.io`, you would still have to manually update the `aws-auth` configmap. 

### How could Crossplane help solve your problem?
Maybe there could be an optional feature on the `identity.aws.crossplane.io` resources which could integrate with the EKS `aws-auth` ConfigMap. 

The resource could look like so:
```yaml
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMUser
metadata:
  name: admin-user
spec:
  reclaimPolicy: Retain
  providerRef:
    name: aws-provider
  forProvider:
    path: /
    eksGroups:
    - system:masters
```
Then in the `aws-auth` ConfigMap, there would be a new entry for the user like so:
```yaml
mapUsers: |
  - userarn: arn:aws:iam::555555555555:user/admin-user
    username: admin-user
    groups:
      - system:masters
```

Here are the docs to how to map IAM to k8s for OIDC/Oath2: https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

**Comment by janwillies** [comment]
This is connected to https://github.com/crossplane/crossplane/issues/1641

Some prior art:

- https://github.com/TierMobility/aws-auth-operator 
- https://github.com/jicowan/group-operator 
- https://github.com/keikoproj/aws-auth 
- https://github.com/ygrene/iam-eks-user-mapper 
- https://github.com/keikoproj/iam-manager

**Comment by cdenneen** [comment]
This would also need to provide adding `mapRoles` to the configMap.

**Comment by kferrone** [comment]
I've actually solved this issue long time ago. 
The compositions have the combine string strategy on the patches. 
From the composition which creates my cluster, it creates the aws-auth for me.

**Comment by kferrone** [comment]
Sure. Here is the item in the resources array within the composition:

```yaml
name: eks-aws-auth-config
base:
  apiVersion: kubernetes.crossplane.io/v1alpha1
  kind: Object
  spec:
    deletionPolicy: Orphan
    forProvider:
      manifest:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: aws-auth
          namespace: kube-system
        data:
          mapRoles: ""
          mapUsers: ""
patches:
- &lbls
  type: PatchSet
  patchSetName: labels
- fromFieldPath: &name metadata.name
  transforms:
  - type: string
    string:
      fmt: "%s-aws-auth"
- fromFieldPath: *name
  toFieldPath: spec.providerConfigRef.name

- fromFieldPath: spec.parameters.awsAuth.mapAccounts
  toFieldPath: spec.forProvider.manifest.data.mapAccounts
- fromFieldPath: spec.parameters.awsAuth.mapUsers
  toFieldPath: spec.forProvider.manifest.data.mapUsers

# now add the data
- type: CombineFromComposite
  toFieldPath: spec.forProvider.manifest.data.mapRoles
  combine:
    variables:
    - fromFieldPath: status.ngRoleArn
    - fromFieldPath: spec.parameters.awsAuth.mapRoles
    strategy: string
    string:
      fmt: |
        - rolearn: %s
          username: system:node:{{EC2PrivateDNSName}}
          groups:
          - system:bootstrappers
          - system:nodes
        %s
```

I'm currently writing a Python webhook to select the Roles based on certain labels. It's not high priority for me so it may take a while.
