### ISSUE TITLE
SecurityGroup does not allow to include ingress source from another SG

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#304]
### What happened?

Trying to add ingress source from another security group but it returns error:

```
message: "update failed: failed to authorize ingress rules: InvalidParameterValue:
CIDR block sg-xxxxxx is malformed\n\tstatus code: 400, request id:
6733d531-97d7-43d1-b23c-5df88444fe4d"
```

Tested from AWS UI console to entry ingress record as security group is ok

example:

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: mysql.secgrp.abc.com
  labels:
    provider: aws
    tier: default
    vpc: dev
spec:
  forProvider:
    description: Created by crossplane
    groupName: crossplane-mysql-sg
    ingress:
      - fromPort: 3306
        toPort: 3306
        ipProtocol: TCP
        ipRanges:
          - cidrIp: "sg-xxxxxxxxx"
            description: "Access from EKS nodes"
    vpcId: vpc-xxxxxxxxx
  providerRef:
    name: aws-provider
```

### How can we reproduce it?
See the above sample manifest for SG

### What environment did it happen in?
Crossplane version: 0.11.1
provider-aws: master (most recent)

**Comment by hasheddan** [comment]
Hi @kelvinwijaya! Thanks for opening this. I believe to specify a source security group you need to include it in the [`userIdGroupPairs` block](https://doc.crds.dev/github.com/crossplane/provider-aws/ec2.aws.crossplane.io/SecurityGroup/v1beta1#spec-forProvider-ingress-userIdGroupPairs). This mirrors the [shape of the AWS SDK](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.24.0/service/ec2?tab=doc#AuthorizeSecurityGroupIngressInput). Could you let me know if this addresses your issue?

**Comment by hasheddan** [comment]
@kelvinwijaya quick follow up here, even if these values are supplied correctly, I am not certain that we are evaluating them correctly. I am investigating now 👍

**Comment by muvaf** [comment]
@hasheddan I realized that there is a mismatch between what's available and what's used as conversion function, so, as you said that field is not used. Preparing a small PR now.

**Comment by kferrone** [comment]
The SecurityGroups should be able to reference itself as the source as well. I'm assuming this would be possible with referencing another group as a source right?

**Comment by kelvinwijaya** [comment]
Have oversight this ticket and now have i have chance to followup

Thanks @hasheddan @muvaf for the fix to add sg into the ingress rules. I verified with following input parameters and it works like charm

```
#Adding by SG Group using aws security group object
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: mysql-secgrp
  labels:
    provider: aws
    tier: default
    vpc: dev
spec:
  forProvider:
    description: Created by crossplane
    groupName: dev-crossplane-mysql-sg
    ingress:
      - fromPort: 3306
        toPort: 3306
        ipProtocol: TCP
        userIdGroupPairs:
          - groupId: "sg-xxxxxxxxxxxxxxx"
            description: "Access from Web"
    vpcId: vpc-xxxxxxxxxxxx
  providerRef:
    name: aws-provider
```
