### ISSUE TITLE
Support for NAT Gateways (and others) and Reference them with RouteTable

### ISSUE THREAD

**Issue by kferrone** [crossplane/provider-aws#308]
### What problem are you facing?
I am unable to create a NAT Gateway and add it as a route to my RouteTables. The RouteTable Should be able to reference a NAT Gateway as a route just like how a RouteTable can route to an InternetGateway. AWS provides quite a bit of targets to route to, Crossplane only provides one, Internet Gateway.

### How could Crossplane help solve your problem?
The route tables routes have these properties: `gatewayId`, `gatewayIdRef`, and a `gatewayIdSelector`. I believe the naming should change from `gateway` to `target`. 
```
gatewayId = targetId
gatewayIdRef = targetIdRef
gatewayIdSelector = targetIdSelector
```

There should be one more field added to define what kind of Target you are selecting. 

```yaml
kind: RouteTable
metadata:
  name: private-us-west-2a
spec:
  forProvider:
    routes:
    - destinationCidrBlock: 10.101.0.0/16
      targetKind: NATGateway # or InternetGateway
      targetIdRef:
         name: my-cool-nat
```

Ultimately the following targetKinds are missing in Crossplane for a full featured experience:
 - Local
 - Egress Only Gateway
 - Instance
 - Network Interface
 - Outpost Local Gateway
 - Peering Connection
 - Transit Gateway
 - Virtual Private Gateway

Even if Crossplane were to omit one of the above targets as a Crossplane resource kind, it should still be available as a target option so one could at least manually set the `targetId`. 

Lastly, if the `targetKind` is not set then the selectors should not do anything and the value for the target should simply default to `local`. 
e.g. If I only set the `destinationCidrBlock` then the target in the AWS console should say `local`.
