### ISSUE TITLE
aws subnet reconciliation fails

### ISSUE THREAD

**Issue by frezbo** [crossplane/provider-aws#332]
### What happened?

When an AWS subnet managed by Crossplane is deleted and when the controller reconciles it fails with an error.

### How can we reproduce it?

* Apply the below YAML spec

YAML spec:

```yaml
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: frezbo-vpc
spec:
  forProvider:
    cidrBlock: 10.16.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags:
      - key: Name
        value: frezbo-vpc
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: frezbo-pub
spec:
  forProvider:
    cidrBlock: 10.16.1.0/24
    tags:
      - key: Name
        value: frezbo-pub
    vpcIdRef:
      name: frezbo-vpc
    mapPublicIPOnLaunch: true
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
```

* Wait for the subnet to be created
* Delete the subnet from the AWS console

Error:

```bash
❯ k describe subnet frezbo-pub
Name:         frezbo-pub
Namespace:
Labels:       <none>
Annotations:  crossplane.io/external-name: subnet-04632929ad60075a9
API Version:  ec2.aws.crossplane.io/v1beta1
Kind:         Subnet
Metadata:
  Creation Timestamp:  2020-09-09T16:11:48Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  3
  Managed Fields:
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:forProvider:
          .:
          f:cidrBlock:
          f:mapPublicIPOnLaunch:
          f:vpcIdRef:
            .:
            f:name:
        f:providerRef:
          .:
          f:name:
        f:reclaimPolicy:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2020-09-09T16:11:48Z
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:assignIpv6AddressOnCreation:
          f:availabilityZone:
          f:availabilityZoneId:
          f:tags:
          f:vpcId:
      f:status:
        .:
        f:atProvider:
          .:
          f:availableIpAddressCount:
          f:subnetId:
          f:subnetState:
        f:conditions:
    Manager:         crossplane-aws-provider
    Operation:       Update
    Time:            2020-09-09T16:15:39Z
  Resource Version:  65529
  Self Link:         /apis/ec2.aws.crossplane.io/v1beta1/subnets/frezbo-pub
  UID:               543e5d76-0a20-47b9-94d5-1ce15e209f52
Spec:
  For Provider:
    assignIpv6AddressOnCreation:  false
    Availability Zone:            us-east-1e
    Availability Zone Id:         use1-az3
    Cidr Block:                   10.16.1.0/24
    Map Public IP On Launch:      true
    Tags:
      Key:    Name
      Value:  frezbo-pub
    Vpc Id:   vpc-03218d0c7d6f9e6c7
    Vpc Id Ref:
      Name:  frezbo-vpc
  Provider Ref:
    Name:          aws-provider
  Reclaim Policy:  Delete
Status:
  At Provider:
    Available Ip Address Count:  251
    Subnet Id:                   subnet-04632929ad60075a9
    Subnet State:                available
  Conditions:
    Last Transition Time:  2020-09-09T16:15:39Z
    Message:               create failed: failed to create the Subnet resource: InvalidParameterCombination: The parameter availabilityZone cannot be used with the parameter availabilityZoneId
                           status code: 400, request id: 96acc599-75fa-4092-8141-b90d0e54ac31
    Reason:                Encountered an error during resource reconciliation
    Status:                False
    Type:                  Synced
    Last Transition Time:  2020-09-09T16:14:42Z
    Reason:                Resource is being created
    Status:                False
    Type:                  Ready
```
