### ISSUE TITLE
ProviderConfig does not have region but this is required by some services 

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#336]
### What happened?

When you try to create a `VPC` with `master` branch, you'll get the following error:
```yaml
  - lastTransitionTime: "2020-09-10T13:25:59Z"
    message: 'create failed: failed to create the VPC resource: unknown endpoint,
      could not resolve endpoint, partition: "aws", service: "ec2", region: "", known:
      [af-south-1 ap-northeast-2 eu-central-1 eu-west-1 fips-us-east-2 fips-us-west-1
      me-south-1 us-west-2 ap-southeast-2 eu-north-1 fips-ca-central-1 sa-east-1 us-east-1
      ap-south-1 ap-southeast-1 ca-central-1 eu-west-2 us-east-2 ap-east-1 ap-northeast-1
      eu-south-1 eu-west-3 fips-us-east-1 fips-us-west-2 us-west-1]'
    reason: Encountered an error during resource reconciliation
    status: "False"
    type: Synced
```

The reason is that client has to be configured with region so that it can construct the endpoint. However, a random endpoint doesn't suffice - it determines in which region the resource should be created. That's pretty different than other providers in the sense that a configuration parameter is included in client config instead of creation request.

### How can we reproduce it?

Create `VPC`

### What environment did it happen in?
Crossplane version: master
Provider-aws:  master
