### ISSUE TITLE
SecurityGroup with egress defined never reaches 'READY' state (continuous polling: UpdatedExternalResource)

### ISSUE THREAD

**Issue by comjf** [crossplane/provider-aws#352]
### What happened?
Creating a SecurityGroup with an egress defined causes continuous "external resource" update requests. The SG seems to be created properly and usable, however crossplane continues to poll aws requesting an update that never comes.

When I create an AWS SG *without* egress defined, everything is fine as shown here:
```
Name:         ingress-sg-hb-pulse-ops-dev
Namespace:    
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  crossplane.io/external-name: <REMOVED>
              meta.helm.sh/release-name: aws-ops-dev-resources
              meta.helm.sh/release-namespace: ops-dev-hb-pulse
API Version:  ec2.aws.crossplane.io/v1beta1
Kind:         SecurityGroup
Metadata:
  Creation Timestamp:  2020-09-29T01:52:56Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        1
  Resource Version:  3213
  Self Link:         /apis/ec2.aws.crossplane.io/v1beta1/securitygroups/ingress-sg-hb-pulse-ops-dev
  UID:               <REMOVED>
Spec:
  For Provider:
    Description:  Inbound Access for hb-pulse-ops-dev
    Group Name:   ingress-sg-hb-pulse-ops-dev
    Ingress:
      From Port:    80
      Ip Protocol:  tcp
      Ip Ranges:
        Cidr Ip:      10.4.0.0/16
        Description:  HTTP ingress
      To Port:        80
      From Port:      443
      Ip Protocol:    tcp
      Ip Ranges:
        Cidr Ip:      10.4.0.0/16
        Description:  HTTPS ingress
      To Port:        443
    Tags:
      Key:    managed_by
      Value:  crossplane
      Key:    namespace
      Value:  ops-dev-hb-pulse
    Vpc Id:   <REMOVED>
  Provider Ref:
    Name:          aws-provider
  Reclaim Policy:  Delete
Status:
  At Provider:
    Owner Id:           <REMOVED>
    Security Group ID:  <REMOVED>
  Conditions:
    Last Transition Time:  2020-09-29T01:52:57Z
    Reason:                Resource is available for use
    Status:                True
    Type:                  Ready
    Last Transition Time:  2020-09-29T01:52:57Z
    Reason:                Successfully reconciled resource
    Status:                True
    Type:                  Synced
Events:
  Type    Reason                   Age   From                                         Message
  ----    ------                   ----  ----                                         -------
  Normal  CreatedExternalResource  109s  managed/securitygroup.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Normal  UpdatedExternalResource  109s  managed/securitygroup.ec2.aws.crossplane.io  Successfully requested update of external resource
```

### How can we reproduce it?
Define an egress in your SecurityGroup spec and apply. Example below (kubectl describe securitygroup.ec2.aws.crossplane.io):
```
Name:         ingress-sg-hb-pulse-ops-dev
Namespace:    
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  crossplane.io/external-name: <REMOVED>
              meta.helm.sh/release-name: aws-ops-dev-resources
              meta.helm.sh/release-namespace: ops-dev-hb-pulse
API Version:  ec2.aws.crossplane.io/v1beta1
Kind:         SecurityGroup
Metadata:
  Creation Timestamp:  2020-09-29T01:57:07Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:        2
  Resource Version:  3649
  Self Link:         /apis/ec2.aws.crossplane.io/v1beta1/securitygroups/ingress-sg-hb-pulse-ops-dev
  UID:               <REMOVED>
Spec:
  For Provider:
    Description:  Inbound Access for hb-pulse-ops-dev
    Egress:
      From Port:    0
      Ip Protocol:  -1
      Ip Ranges:
        Cidr Ip:      0.0.0.0/0
        Description:  ALL egress allowed
      To Port:        0
    Group Name:       ingress-sg-hb-pulse-ops-dev
    Ingress:
      From Port:    80
      Ip Protocol:  tcp
      Ip Ranges:
        Cidr Ip:      10.4.0.0/16
        Description:  HTTP ingress
      To Port:        80
      From Port:      443
      Ip Protocol:    tcp
      Ip Ranges:
        Cidr Ip:      10.4.0.0/16
        Description:  HTTPS ingress
      To Port:        443
    Tags:
      Key:    managed_by
      Value:  crossplane
      Key:    namespace
      Value:  ops-dev-hb-pulse
    Vpc Id:   <REMOVED>
  Provider Ref:
    Name:          aws-provider
  Reclaim Policy:  Delete
Status:
  At Provider:
    Owner Id:           <REMOVED>
    Security Group ID:  <REMOVED>
  Conditions:
    Last Transition Time:  2020-09-29T01:57:07Z
    Reason:                Resource is being created
    Status:                False
    Type:                  Ready
    Last Transition Time:  2020-09-29T01:57:07Z
    Reason:                Successfully reconciled resource
    Status:                True
    Type:                  Synced
Events:
  Type    Reason                   Age                  From                                         Message
  ----    ------                   ----                 ----                                         -------
  Normal  CreatedExternalResource  7m12s                managed/securitygroup.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Normal  UpdatedExternalResource  1s (x11 over 7m11s)  managed/securitygroup.ec2.aws.crossplane.io  Successfully requested update of external resource
```

### What environment did it happen in?
```
helm install crossplane --namespace crossplane-system crossplane-master/crossplane --version 0.13.0-rc.114.g20493ac --devel
kubectl crossplane package install --cluster --namespace crossplane-system crossplane/provider-aws:v0.11.1 provider-aws
```

**Comment by comjf** [comment]
Upon reviewing my above post, feared this might just be user error as the above "fromPort" and "toPort" are both 0 for my egress (In the output above)

However, upon reviewing my source file, this is what I'm uploading:
```
# Source: crossplane/templates/securitygroup.yml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: ingress-sg-hb-pulse-ops-dev
  namespace: ops-dev-hb-pulse
spec:
  forProvider:
    vpcId: vpc-REMOVED
    groupName: ingress-sg-hb-pulse-ops-dev
    description: Inbound Access for hb-pulse-ops-dev
    egress:
      - fromPort: 0
        ipProtocol: "-1"
        ipRanges:
        - cidrIp: 0.0.0.0/0
          description: ALL egress allowed
        toPort: 65535
    ingress:
      - fromPort: 80
        ipProtocol: tcp
        ipRanges:
        - cidrIp: 10.4.0.0/16
          description: HTTP ingress
        toPort: 80
      - fromPort: 443
        ipProtocol: tcp
        ipRanges:
        - cidrIp: 10.4.0.0/16
          description: HTTPS ingress
        toPort: 443
    tags:
      - key: managed_by
        value: "crossplane"
      - key: namespace
        value: ops-dev-hb-pulse
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
```
Just stabbing at the dark, but perhaps the issue is here? https://github.com/crossplane/provider-aws/blob/master/pkg/clients/ec2/securitygroup.go#L202
