### ISSUE TITLE
Route53 ResourceRecordSet with AilasTarget is not working

### ISSUE THREAD

**Issue by YasukeXXX** [crossplane/provider-aws#372]
### What happened?

I tried to manage record set with crossplane, but I got an error.

error messsage:  
```
   Warning  CannotCreateExternalResource  4s (x3 over 6s)  managed/resourcerecordset.route53.aws.crossplane.io  failed to create the ResourceRecordSet resource: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ChangeResourceRecordSetsInput.ChangeBatch.Changes[0].ResourceRecordSet.ResourceRecords.
```

manifest:
```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: test
  annotations:
    crossplane.io/external-name: test.xxxxxxx.com.
spec:
  forProvider:
    type: A
    zoneId: XXXXXXXXXXXXX
    aliasTarget:
      dnsName: xxxxx.region.elb.amazonaws.com
      evaluateTargetHealth: true
      hostedZoneId: XXXXXXXXXXXXX
  reclaimPolicy: Orphan
  providerConfigRef:
    name: aws-provider

```
Is there something wrong?

### How can we reproduce it?

Fill `xxx` values and apply above manifest.

### What environment did it happen in?
Crossplane version: 0.12.0
