### ISSUE TITLE
SecurityGroup in Composition is created twice

### ISSUE THREAD

**Issue by janwillies** [crossplane/provider-aws#378]
### What happened?
A security group in a crossplane composition is created twice:
> CannotCreateExternalResource  24s  managed/securitygroup.ec2.aws.crossplane.io  failed to create the SecurityGroup resource: InvalidGroup.Duplicate: The security group 'cnp-test-1-7blj8' already exists for VPC 'vpc-abcdef'  

Manual creation works fine (outside of a composition).

### How can we reproduce it?
composition.yaml:
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: cnp-sg
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeTypeRef:
    apiVersion: kubernetes.cnp.example.org/v1alpha1
    kind: CompositeControlPlane    
  resources:
  - base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: SecurityGroup
      spec:
        forProvider:
          region: eu-central-1
          description: allow access
          ingress:
          - fromPort: 443
            toPort: 443
            ipProtocol: tcp
            ipRanges:
            - cidrIp: 192.168.0.0/24
              description: test
          vpcId: vpc-abcdef
        reclaimPolicy: Delete
        providerConfigRef:
          name: aws-provider        
    patches:
    - fromFieldPath: "metadata.labels"
      toFieldPath: "metadata.labels"
    - fromFieldPath: "metadata.annotations"
      toFieldPath: "metadata.annotations"
    - fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.groupName"
```
xrd.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: compositecontroleplanes.kubernetes.cnp.example.org
spec:
  defaultCompositionRef:
    name: cnp-sg
  claimNames:
    kind: ControlPlane
    plural: controlplanes
  crdSpecTemplate:
    group: kubernetes.cnp.example.org
    version: v1alpha1
    names:
      kind: CompositeControlPlane
      listKind: CompositeControlPlaneList
      plural: compositecontroleplanes
      singular: compositecontroleplane
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec: {}
```
xrc.yaml
```yaml
apiVersion: kubernetes.cnp.example.org/v1alpha1
kind: ControlPlane
metadata:
  name: cnp-test-1
spec: {}
```

### What environment did it happen in?
Crossplane version: v0.13.0
provider-aws: v0.12.0
