### ISSUE TITLE
S3 v1beta1 sse-s3 encryption error

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#380]
I face issue while enabling SSE-S3 encryption for S3 bucket with the latest S3 API

I believe something to do with the following: 
`This is just the behavior of the S3. When a bucket does not have an encryption, S3 will return a 4x4 HTTP status code back which will always be propagated as an exception in boto3.`

i believe somewhere in the controller logic, there is GET API call to check whether the existing bucket has encryption configuration turned on, and if this is new bucket. it could potentially throw the HTTP 4x4 as response as this is S3 API behavior

https://github.com/boto/boto3/issues/1899

When I apply s3 encryption, _snippet_ of the spec:

```
spec:
          forProvider:
            acl: "private"
            locationConstraint: "us-west-1"
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
```

I have reconcile _error_ as follows:

```
conditions:
  - lastTransitionTime: "2020-10-13T15:01:10Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2020-10-13T15:07:47Z"
    message: "observe failed: cannot get Bucket encryption configuration: ServerSideEncry
ptionConfigurationNotFoundError:
      The server side encryption configuration was not found\n\tstatus code: 404,
      request id: 6F36C163756424A7, host id: UwOOkZWVPUzpeZdPbM7jYCc976ewDe4LLuNu3bUSC3qf
TQDu513hUPo8wzFOOlilzDu+P16Wa6Q="
    reason: ReconcileError
    status: "False"
    type: Synced

```

Crossplane version: `v0.13.0`

This is the second similar error when i tried after the tagging (#379), the error looks pretty similar
