### ISSUE TITLE
S3 Bucket stuck in Ready state

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#385]
Created new S3 Bucket and it stuck in the Creating phase, try to check event logs and everything look normal.

Although the managed resource is created successfully in AWS UI

```
status:
  atProvider:
    arn: arn:aws:s3:::mybucket-1
  conditions:
  - lastTransitionTime: "2020-10-15T08:12:56Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2020-10-15T08:12:58Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

`Spec` as follow:
```
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-west-1
    objectLockEnabledForBucket: false
    serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
    tagging:
      tagSet:
      - key: key1
        value: value1
      - key: key2
        value: value2
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: aws-provider
  writeConnectionSecretToRef:
    name: mybucket-1
    namespace: crossplane-system

```

Crossplane version: provider-aws:v0.12.0-10.g71a09e8

**Comment by krishchow** [comment]
I'm not able to replicate this bug with the current master build, are there any events associated with the resource?

**Comment by kelvinwijaya** [comment]
Hi @krishchow 

Thanks for checking.

I will also investigate from my end, so far i only can see the event is keep looping every few seconds:

```
1s          Normal   ConfigureCompositeResource   csbucket/mybucket-1                 Successf
ully configured composite resource
1s          Normal   BindCompositeResource        csbucket/mybucket-1                    Composit
e resource is not yet ready
1s          Normal   BindCompositeResource        csbucket/mybucket-1                    Composit
e resource is not yet ready
1s          Normal   BindCompositeResource        csbucket/mybucket-1                   Composit
e resource is not yet ready

```

**Comment by kelvinwijaya** [comment]
Hi @krishchow 

I verified, and with composition using tagging and server side encryption options, this issues arise.

When i remove  the below from the spec then it works
```
serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
    tagging:
      tagSet:
      - key: key1
        value: value1
      - key: key2
        value: value2
```

Just to let you know that my testing is using XRD composite object


Thanks,
Kelvin

**Comment by krishchow** [comment]
Hi @kelvinwijaya - still trying to replicate this issue so I can start to work on a fix. I noticed you are creating the buckets in a composition. If you try to use the same spec outside of the composition (i.e., just creating one bucket), does the creation succeed?

**Comment by kelvinwijaya** [comment]
Hi @krishchow 

Yes based on my testing, direct creation of buckets.s3.aws.crossplane.io object also face similar issue

With _serverSideEncryptionConfiguration_  or _tagSet_ , the **READY** state will be `false`. But when i remove those parameters, everything works fine

Thanks,
Kelvin

**Comment by krishchow** [comment]
I did some more testing outside of the AWS provider since I haven't been able to replicate there, and I think I have found the culprit. It seems like AWS _can_ provide the list of tags in an arbitrary order. This can differ from the order of the tags in the tagging configuration, so I am just about to open up a PR that should fix this issue. 

Thanks for your help with narrowing this down @kelvinwijaya :)

**Comment by Promaethius** [comment]
Running into same issue with the given example s3.yaml

**Comment by krishchow** [comment]
@Promaethius @kelvinwijaya - this should be fixed by #390

**Comment by kelvinwijaya** [comment]
Hi @krishchow .

Many thanks and glad that we have found the culprit

**Comment by marcinc** [comment]
Just came across a similar problem @kelvinwijaya noticed (https://github.com/crossplane/provider-aws/issues/385#issuecomment-709874858). 

With bucket configuration containing:
```
forProvider:
   ...
   serverSideEncryptionConfiguration:
   rules: 
     - applyServerSideEncryptionByDefault: 
           sseAlgorithm: AES256
```

I see the following reconciler error message:

```
    Message:               observe failed: cannot get Bucket encryption configuration: ServerSideEncryptionConfigurationNotFoundError: The server side encryption configuration was not found
                           status code: 404, request id: 868D8CA56BF0A080, host id: xxxxxxxxxxxxxx
    Reason:                ReconcileError
```

Bucket gets created in the provider, however managed resource READY status is False.
