### ISSUE TITLE
S3 bucket SSE configuration not found

### ISSUE THREAD

**Issue by marcinc** [crossplane/provider-aws#400]
### What happened?

There seem to be an issues with S3 bucket forProvider fields around server side encryption. This issue is similar to the one already reported in #385. When bucket configuration contains `serverSideEncryptionConfiguration` with sseAlgorithm specified it results in S3 bucket being provisioned with the encryption disabled. Managed resource READY status remains False. The same behaviour observed with both `sseAlgorithm` value options (AES256, aws:kms).

### How can we reproduce it?

With bucket configuration containing:

```
forProvider:
   ...
   serverSideEncryptionConfiguration:
   rules: 
     - applyServerSideEncryptionByDefault: 
           sseAlgorithm: AES256
```

Results in the following reconciler error message:

```
    Message:               observe failed: cannot get Bucket encryption configuration: ServerSideEncryptionConfigurationNotFoundError: The server side encryption configuration was not found
                           status code: 404, request id: 868D8CA56BF0A080, host id: xxxxxxxxxxxxxx
    Reason:                ReconcileError
```

### What environment did it happen in?

Crossplane version: v0.13.0
AWS provider version: v0.12.0
