### ISSUE TITLE
AUTHENTICATION.md needs to be updated

### ISSUE THREAD

**Issue by jasgeo75** [crossplane/provider-aws#402]

**Comment by hasheddan** [comment]
@jasgeo75 thanks for opening this! I will get it updated ASAP :+1:

**Comment by jasgeo75** [comment]
@hasheddan Excellent, looking forward to checking it out.   I tried following the doc and then cross referencing https://doc.crds.dev/github.com/crossplane/provider-aws but I'm not quite there yet.  I'm attempting to deploy a securitygroup just as a test but I receive this error:

```
message: 'connect failed: unable to read web identity token file in pod: open
      : no such file or directory'
```
Does what I have below looks sane?

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${aws_account_id}:oidc-provider/${oidc_provider}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "${oidc_provider}:sub": "system:serviceaccount:${service_account_namespace}:${service_account_name}"
        }
      }
    }
  ]
}
```
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:master
```
```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
spec:
  credentials:
    source: InjectedIdentity
  useServiceAccount: true
  region: ${region}
```
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: sgtest
spec:
  forProvider:
    region: eu-west-1
    vpcId: vpc-00redacted  
    groupName: sgtest
    description: testing crossplane
    ingress:
      - fromPort: 443
        toPort: 443
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 0.0.0.0/0
  providerConfigRef:
    name: aws-provider 
```

Then I tweak the annotation
```bash
sa=$(kubectl get serviceaccounts -n ${service_account_namespace} --no-headers=true | awk '/provider-aws/{print $1}')
kubectl annotate serviceaccount -n ${service_account_namespace} $sa eks.amazonaws.com/role-arn=arn:aws:iam::${aws_account_id}\:role/${iam_role_name}
```
