### ISSUE TITLE
missing CRD - ProviderConfig" 

### ISSUE THREAD

**Issue by shettyjm** [crossplane/provider-aws#406]
Installed v0.12.0 provider-aws.
Seems like missing to create "ProviderConfig" CRD.

Steps create 1. Installl provder-aws using 
```
`kubectl crossplane install provider crossplane/provider-aws:v0.12.0`

```
Step 2. Create aws provider usign following manifest
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-account-creds
      key: credentials

```

Error - error: unable to recognize "my-aws-provider-config.yaml": no matches for kind "ProviderConfig" in version "aws.crossplane.io/v1beta1"
