### ISSUE TITLE
EKS sync fails after being ready

### ISSUE THREAD

**Issue by muvaf** [crossplane/provider-aws#411]
### What happened?

I created a `Cluster.eks` resource using https://github.com/upbound/platform-ref-aws and got the following conditions after a while it's ready:
```yaml
  conditions:
  - lastTransitionTime: "2020-11-02T21:18:45Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-11-02T21:28:08Z"
    message: "update failed: cannot update EKS cluster configuration: InvalidParameterException:
      subnetIds and securityGroupIds cannot be updated.\n\tstatus code: 400, request
      id: d01c974e-95bd-4172-9ebf-aa5309abe86d"
    reason: ReconcileError
    status: "False"
    type: Synced
```

I didn't change anything in spec after creation.

### How can we reproduce it?

Create a `Cluster.eks` using the `subnetIds` and `securityGroupIds` fields.

### What environment did it happen in?
Crossplane version: 0.14.0-rc.115.g6a7731d8
AWS: v0.13.0-2.gd840deb7
