### ISSUE TITLE
S3Bucket external-name annotation not working

### ISSUE THREAD

**Issue by publiusi** [crossplane/provider-aws#424]
When creating a aws Bucket in a composition, using the external-name annotation:
```
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: poc-dev-bucket
          **annotations:
            crossplane.io/external-name: poc-dev-bucket**
          labels:
            name: poc-dev-bucket
```

The bucket is not created and the following error is thrown:
failed to query Bucket: BucketRegionError: incorrect region, the bucket is not in ‘us-west-2’ region status code: 301, request id: AF960CE31F54F2A6, host id: mEymAUMu6Qchg9fB3lUS8pGi0D5hRxumiZm2LzzJ+YYyaFns/L2YorqW1mqWZZpmg6worAMgu20=

### What environment did it happen in?
Crossplane version: 0.14
