### ISSUE TITLE
Issue applying the bucket lifecycle configuration 

### ISSUE THREAD

**Issue by publiusi** [crossplane/provider-aws#430]
Using the following code to create a bucket , the bucket is created in AWS:

```
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: s3bucket-st
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: labs.com/v1alpha1
    kind: CompositeS3BucketInstance
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: poc-dev-bucket
          annotations:
            crossplane.io/external-name: poc-dev-bucket
          labels:
            name: poc-dev-bucket
        spec:
          forProvider:
            locationConstraint: us-west-2
            acl: private
            accelerateConfiguration:
              status: Enabled
            versioningConfiguration:
              status: Enabled
            tagging:
              tagSet:
                - key: key1
                  value: val1
                - key: secondKey
                  value: val2
                - key: key3
                  value: val3
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            corsConfiguration:
              corsRules:
                - allowedMethods:
                    - "GET"
                  allowedOrigins:
                    - "ola"
            lifecycleConfiguration:
              rules:
                - status: Enabled
                  abortIncompleteMultipartUpload:
                    daysAfterInitiation: 7
                  noncurrentVersionTransitions:
                    - noncurrentDays: 45
                      storageClass: "DEEP_ARCHIVE"
                  transitions:
                    - days: 1
                      storageClass: "DEEP_ARCHIVE"
          providerConfigRef:
            name: aws-creds-config
      patches:
        - fromFieldPath: "spec.parameters.prefix"
          toFieldPath: "metadata.annotations[crossplane.io/external-name]"
          transforms:
            - type: string
              string:
                fmt: "%s-converter"
        - fromFieldPath: "spec.parameters.prefix"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-converter"
        - fromFieldPath: "spec.parameters.prefix"
          toFieldPath: "metadata.labels.name"
          transforms:
            - type: string
              string:
                fmt: "%s-converter"
```

### What happened?

The bucket is created in AWS , the following error shows when applying lifecycle configuration.
`
cannot create or update: cannot put Bucket lifecycle configuration: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema status code: 400, request id: 4QBVAP1W8HBJ8N4M, host id: 08VaUDHoNn+9tNZ7krXL41Zv6ZCEh+v1bAFqsRwKAVZ4jEula5sm+8TnNrmPwqpNqeTzAnB8CIY=`

### What environment did it happen in?
Crossplane version:
