### ISSUE TITLE
S3 BucketPolicy not able to put multiple StringEquals conditions

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#455]
### What happened?

While creating s3.aws.crossplane.io/v1alpha2 BucketPolicy conditions for StringEquals. Seem I can only put 1 key-value pair. As for certain scenario, multi key-value pairs are needed

### How can we reproduce it?

Sample manifest:

```
apiVersion: s3.aws.crossplane.io/v1alpha2
kind: BucketPolicy
metadata:
  name: mybucketname.bucketpolicy
spec:
  forProvider:
    version: "2012-10-17"
    bucketName: mybucketname
    region: us-west-1
    statements:
      - sid: DownloadandUpload
        action:
          - "s3:GetObject"
          - "s3:GetObjectAcl"
          - "s3:GetObjectVersion"
          - "s3:PutObject"
          - "s3:PutObjectAcl"
          - "s3:DeleteObject"
          - "s3:DeleteObjectVersion"
        effect: Allow
        principal:
          allowAnon: true
        resource: 
          - "mybucketname"
          - "mybucketname/*"  
        condition:
          StringEquals:
            - key: "aws:Key1"
              stringValue: "value1"
            - key: "aws:Key2"
              stringValue: "value2"
            - key: "aws:Key3"
              stringValue: "value3"
            - key: "aws:Key4"
              stringValue: "value4"
  providerConfigRef:
    name: aws-provider
  deletionPolicy: Delete
```

### What environment did it happen in?
Crossplane version: v0.14.0
Provider-aws version: v0.15.0
