### ISSUE TITLE
Creating an SQS Queue produces api exceptions

### ISSUE THREAD

**Issue by Savasw** [crossplane/provider-aws#457]
### What happened?

Creating an sqs queue resource produces api exceptions when,
1. just the required parameters are provided(region)
```
CannotCreateExternalResource  27s  managed/queue.sqs.aws.crossplane.io  cannot create Queue: MalformedInput: End of list found where not expected
status code: 400, request id: xxxx
```
2. When `fifoQueue` attribute is initialised explicitly with `false` value
```
CannotCreateExternalResource  6s  managed/queue.sqs.aws.crossplane.io  cannot create Queue: InvalidAttributeName: Unknown Attribute FifoQueue.
status code: 400, request id: xxxx
```

### How can we reproduce it?

Use following configs for each scenario
1. 
```
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: test-queue
spec:
  forProvider:
    region: eu-west-1
  providerConfigRef:
    name: aws-provider
```

2. 
```
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: test-queue
spec:
  forProvider:
    region: eu-west-1
    fifoQueue: false
  providerConfigRef:
    name: aws-provider
```
### What environment did it happen in?
Crossplane version: v0.14.0
Provider AWS Controller version: v0.16.0-rc.0

PR https://github.com/crossplane/provider-aws/pull/456 fixes this.
