### ISSUE TITLE
Field doesn't get updated on the managed resource after it was updated on the claim

### ISSUE THREAD

**Issue by bandesz** [crossplane/provider-aws#473]
### What happened?

I've updated an object's field on the claim, but the field wasn't updated on the managed resource.

Opening it here first as it happened with the S3 bucket resource.

When I create the claim with either Suspended/Enabled, it is set correctly, only the update doesn't seem to propagate.

### How can we reproduce it?

Property on the CompositeResourceDefinition:

```
properties:
  name:
    type: string
    minLength: 1
  region:
    type: string
    minLength: 1
  versioningConfiguration:
    type: object
    required:
      - status
    properties:
      status:
        type: string
        enum:
          - Suspended
          - Enabled
        default: Suspended
```

S3 bucket in the Composition:

```
base:
  apiVersion: s3.aws.crossplane.io/v1beta1
  kind: Bucket
  spec:
    [...]
patches:
  - fromFieldPath: "spec.parameters.versioningConfiguration"
    toFieldPath: "spec.forProvider.versioningConfiguration"
```

If I change the versioningConfiguration.status value on the claim, it doesn't get propagated to the S3 bucket object.

### What environment did it happen in?
Crossplane version: 0.14.0
AWS provider version: 0.16.0
