### ISSUE TITLE
EKS NodeGroup scalingConfig.desiredSize can conflict with autoscaler

### ISSUE THREAD

**Issue by enderv** [crossplane/provider-aws#477]
### What happened?
I created a node group for an already existing EKS cluster running cluster autoscaler. I never deployed anything to the nodes and cluster autoscaler adjusted the desired size down to the group minimum but the nodegroup reconciler bumped it back up to what was defined in the spec.

### How can we reproduce it?
Need an already existing EKS cluster with [cluster autoscaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md) installed.

```
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: testgroupb
spec:
  deletionPolicy: Delete
  forProvider:
    amiType: AL2_x86_64
    clusterName: <your_cluster_name>
    diskSize: 20
    instanceTypes:
    - t2.medium
    nodeRole: <node-arn>
    region: us-east-1
    scalingConfig:
      maxSize: 5
      minSize: 1
      desiredSize: 3
    subnets:
    - <your_subnets>
    version: "1.17"
  providerConfigRef:
    name: aws-provider
```

### What environment did it happen in?
Crossplane version: 1.0.0
Provider-aws: v0.16.0
Kubernetes Version: EKS 1.17
Cluster Autoscaler Version:1.17.3

**Comment by hasheddan** [comment]
@enderv would it make sense to omit your `scalingConfig` in this case?

**Comment by muvaf** [comment]
FWIW, Crossplane deems to be the source of truth so it will correct any drift. In this case, I believe autoscaler changes the desired size, but not min/max. From what I can tell, `desiredSize` is optional. So, if you'd like autoscaler to manage that property, leaving `desiredSize` empty might help.

**Comment by enderv** [comment]
@hasheddan - Just tried with no scaling config and ended up with max: 2 min: 1 desired: 2. I'm assuming it wouldn't try to correct desired anymore but can't really do much with a max 2 unfortunately :( 

@muvaf - unfortunately looks like if one value is supplied have to give all of them. Tried with no desiredSize and would get 400 back from AWS saying its a required value. Only docs I could actually find saying that though is the [cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-nodegroup-scalingconfig.html) docs.

**Comment by enderv** [comment]
What are yalls thoughts on adding a flag in scaling config to ignored desired on reconcile short term? Have some time and can work on that if you're ok with it.
Not ideal as think it will come up with other resources and was thinking of opening a ticket for a more generic feature like terraforms lifecycle ignore_changes for a long term solution.

**Comment by mcavoyk** [comment]
> What are yalls thoughts on adding a flag in scaling config to ignored desired on reconcile short term? Have some time and can work on that if you're ok with it.

My thinking is that leaving `desiredSize` nil indicates to the controller to ignore the field, and then to use the current desiredSize value in update requests as the value appears to be [required if scalingConfig is set](https://github.com/aws/aws-sdk-go-v2/blob/v0.31.0/service/eks/types/types.go#L573). 

The problem with the above idea is `desiredSize` will be late initialized even if unset. so this would also need to be changed to work properly with Cluster Autoscaler.

**Comment by muvaf** [comment]
So let's say I have the following configuration:
```yaml
maxSize: 5
minSize: 1
desiredSize: 3
```

When the autoscaler scales the nodegroup down to `1`, does AWS report back that the `desiredSize` is `1` and that causes provider-aws to issue an update? Also does updating `desiredSize` to `3` to a nodegroup that's been scaled-down to `1` cause the nodegroup to get additional 2 nodes even if there is no load?
