### ISSUE TITLE
Security Group doesn't add new ingress rule

### ISSUE THREAD

**Issue by bandesz** [crossplane/provider-aws#503]
### What happened?

I added a new ingress rule to a SecurityGroup but it wasn't applied to the resource.
After the update Ready = True and Sync = True, no errors in events.

### How can we reproduce it?

Create the following security group:

```
cat <<EOF | kubectl apply -f -
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-aws-rds
spec:
  deletionPolicy: Delete
  forProvider:
    description: Security group to allow traffic to databases created by Crossplane
    groupName: example-crossplane-aws-rds
    ingress:
    - fromPort: 5432
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.0.0.0/16
      toPort: 5432
    region: eu-west-2
    vpcId: vpc-xxx
  providerConfigRef:
    name: default
EOF
```

Add a new ingress rule:
```
cat <<EOF | kubectl apply -f -
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-aws-rds
spec:
  deletionPolicy: Delete
  forProvider:
    description: Security group to allow traffic to databases created by Crossplane
    groupName: example-crossplane-aws-rds
    ingress:
    - fromPort: 3306
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.0.0.0/16
      toPort: 3306
    - fromPort: 5432
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.0.0.0/16
      toPort: 5432
    region: eu-west-2
    vpcId: vpc-xxx
  providerConfigRef:
    name: default
EOF
```

### What environment did it happen in?
Crossplane version: 1.0.0
AWS provider: 0.16.0

**Comment by bandesz** [comment]
Also if I update the ipRanges on an existing ingress rule, it won't remove the ipRanges that I removed on the object.

**Comment by RafalMaleska** [comment]
i have encountered the same issue. 

seams like the crossplane provider is looking only for the first ingress entry. going further with @bandesz example if I modify an existing security group and replace the existing ingress entry with a new one: 

```
cat <<EOF | kubectl apply -f -
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-aws-rds
spec:
  deletionPolicy: Delete
  forProvider:
    description: Security group to allow traffic to databases created by Crossplane
    groupName: example-crossplane-aws-rds
    ingress:
    - fromPort: 3306
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.0.0.0/16
      toPort: 3306    region: eu-west-2
    vpcId: vpc-xxx
  providerConfigRef:
    name: default
EOF
```

it will add a new ingress rule next to the previous one. modification is not possible.
