### ISSUE TITLE
SecurityGroup doesn't remove tags

### ISSUE THREAD

**Issue by bandesz** [crossplane/provider-aws#504]
### What happened?

I removed a tag from a SecurityGroup but it wasn't applied to the resource.
After the update Ready = True and Sync = True, no errors in events.

### How can we reproduce it?

Create the following security group:

```
cat <<EOF | kubectl apply -f -
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-aws-rds
spec:
  deletionPolicy: Delete
  forProvider:
    description: Security group to allow traffic to databases created by Crossplane
    groupName: example-crossplane-aws-rds
    ingress:
    - fromPort: 5432
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.0.0.0/16
      toPort: 5432
    region: eu-west-2
    tags:
    - key: aaa
      value: bbb
    - key: ccc
      value: ddd
    vpcId: vpc-xxx
  providerConfigRef:
    name: default
EOF
```

Remove a tag:
```
cat <<EOF | kubectl apply -f -
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-aws-rds
spec:
  deletionPolicy: Delete
  forProvider:
    description: Security group to allow traffic to databases created by Crossplane
    groupName: example-crossplane-aws-rds
    ingress:
    - fromPort: 5432
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.0.0.0/16
      toPort: 5432
    region: eu-west-2
    tags:
    - key: aaa
      value: bbb
    vpcId: vpc-xxx
  providerConfigRef:
    name: default
EOF
```

### What environment did it happen in?
Crossplane version: 1.0.0
AWS provider: 0.16.0
