### ISSUE TITLE
AWS SG: ICMP Rules do not work as expected

### ISSUE THREAD

**Issue by jdfalk** [crossplane/provider-aws#515]
### What happened?

AWS SecurityGroup using Crossplane changes the ICMP toPort, and does not create the rules.

More info:
https://crossplane.slack.com/archives/CEG3T90A1/p1611769007208200

### How can we reproduce it?

Create an AWS SecurityGroup in Crossplane that contains the following:
```yaml
spec:
  forProvider:
    description: group1
    groupName: group1
    ingress:
      - fromPort: 3
        ipProtocol: icmp
        ipRanges:
          - cidrIp: 10.0.0.0/16
        toPort: 4
      - fromPort: 80
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 10.0.0.0/16
        toPort: 80 
      - fromPort: 443
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 10.0.0.0/16
        toPort: 443
```
SecurityGroup will be created but missing the ICMP rules, in addition, the icmp rules will change in the crd:
```yaml
spec:
  forProvider:
    description: group1
    groupName: group1
    ingress:
      - fromPort: 3
        ipProtocol: icmp
        ipRanges:
          - cidrIp: 10.0.0.0/16
        toPort: 3
      - fromPort: 80
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 10.0.0.0/16
        toPort: 80 
      - fromPort: 443
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 10.0.0.0/16
        toPort: 443
```

If you add a rule manually to the SG and pull the SG using the aws command it returns 
```json
                {
                    "FromPort": 3,
                    "IpProtocol": "icmp",
                    "IpRanges": [
                        {
                            "CidrIp": "192.168.0.0/24"
                        }
                    ],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "ToPort": 4,
                    "UserIdGroupPairs": []
                },
```

### What environment did it happen in?
Crossplane version: 
1.0.0
Crossplane Provider Version:
provider-aws:v0.16.0
Cloud hosting environment: AWS/EKS
K8S Server Version: 
```
version.Info{
  Major:"1",  
  Minor:"18+", 
  GitVersion:"v1.18.9-eks-d1db3c", 
  GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", 
  GitTreeState:"clean", 
  BuildDate:"2020-10-20T22:18:07Z", 
  GoVersion:"go1.13.15", 
  Compiler:"gc", 
  Platform:"linux/amd64"
}
```
