### ISSUE TITLE
RDS Instance region should be required

### ISSUE THREAD

**Issue by negz** [crossplane/provider-aws#519]
### What happened?

I tried to create an RDS instance without a region (i.e. without `spec.forProvider.region`) and got the following error:

```console
  Warning  CannotObserveExternalResource  4s (x2 over 4s)   managed/rdsinstance.database.aws.crossplane.io  cannot describe RDS instance: unknown endpoint, could not resolve endpoint, partition: "aws", service: "rds", region: "", known: [eu-south-1 rds-fips.ca-central-1 rds-fips.us-east-1 af-south-1 ap-east-1 ap-northeast-2 ap-southeast-1 eu-north-1 rds-fips.us-west-2 ap-southeast-2 ca-central-1 eu-west-1 me-south-1 rds-fips.us-east-2 ap-northeast-1 ap-south-1 eu-central-1 eu-west-3 us-west-2 us-west-1 eu-west-2 rds-fips.us-west-1 sa-east-1 us-east-1 us-east-2]
```

I believe that since we moved region out of the ProviderConfig it must now be specified on the resource.

### How can we reproduce it?

Create the following RDS instance:

```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rds
spec:
  forProvider:
    dbInstanceClass: db.t3.medium
    engine: mysql
    allocatedStorage: 20
```

### What environment did it happen in?
Crossplane version: `crossplane/provider-aws:v0.16.0 `
