### ISSUE TITLE
Importing SQS resource into crossplane does not add optional fields

### ISSUE THREAD

**Issue by duncaan** [crossplane/provider-aws#532]
### What happened?
Attempted to import a SQS resource into crossplane using this manifest:
```
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  annotations:
    crossplane.io/external-name: event-queue
  name: event-queue
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: aws-provider
```
I expected that the Queue resource would get updated with optional fields that were set when the queue was created.  It was not.

### How can we reproduce it?
Attempt to import an existing SQS resource using the above manifest.

### What environment did it happen in?
Crossplane version: 

crossplane/provider-aws-controller:v0.16.0

Similar to https://github.com/crossplane/provider-aws/issues/507
