### ISSUE TITLE
S3 bucket serverSideEncryption with kmsMasterKeyId makes bucket resource not ready

### ISSUE THREAD

**Issue by yshu2017** [crossplane/provider-aws#540]
### What happened?

Attempted to create S3 bucket with serverSideEncryption settings with kmsMasterKeyId

claim.yaml
```
apiVersion: storage.ccs.test.com/v1alpha1
kind: S3Bucket
metadata:
  name: claimed-s3-test
  namespace: default
spec:
  parameters:
    bucketName: claimed-s3-test
    region: us-east-2
    version_enabled: Enabled
    serverSideEncryptionConfig:
      kmsMasterKeyId: "XXXXXXXfb-b87c-4sfsf1-8ea5-baXXXXcsdfs0e"
      sseAlgorithm: "aws:kms"
  compositionSelector:
    matchLabels:
      provider: aws
 ```

composition.yaml
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composites3buckets.aws.storage.ccs.test.com
  labels:
    guide: s3bucket
    provider: aws
    vpc: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: storage.ccs.test.com/v1alpha1
    kind: CompositeS3Bucket
  patchSets:
    - name: Metadata
      patches:
      - fromFieldPath: metadata.annotations
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: us-west-2
            objectLockEnabledForBucket: false
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
#                    kmsMasterKeyId: ""  #This key is ONLY applicable ONLY if sseAlgorithm is "aws:kms"
                    sseAlgorithm: AES256
      patches:
        - type: PatchSet
          patchSetName: Metadata
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.locationConstraint"
        - fromFieldPath: "spec.parameters.serverSideEncryptionConfig"
          toFieldPath: "spec.forProvider.serverSideEncryptionConfiguration.rules[0].applyServerSideEncryptionByDefault"
```

definition.yaml
```apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: composites3buckets.storage.ccs.test.com
spec:
  group: storage.ccs.test.com
  names:
    kind: CompositeS3Bucket
    plural: composites3buckets
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                    description: "Specifies the Region where the bucket will be created. default to 'us-west-2'."
                  serverSideEncryptionConfig:
                    type: object
                    properties:
                      kmsMasterKeyId:
                        type: string
                        description: "(Optional) AWS Key Management Service (KMS) customer master key ID to use for the default encryption.
                        This parameter is allowed if and only if SSEAlgorithm is set to 'aws:kms'. Must be full arn like 'arn:aws:kms:us-east-2:123456789123:alias/aws/s3'
                        or keyId like 'abcdefg6-22x68-4a39-b07a-9b3dxxxx6c908'. Can't use 'alias/aws/s3'. No default set. "
                      sseAlgorithm:
                        type: string
                        description: "AWS Key Management Service (KMS) customer master key ID to use for the default encryption.
                        The ONLY allowed values are 'AES256' and 'aws:kms'. Default is 'aws:kms'"
                        enum: ["aws:kms", "AES256"]
                  
```
The bucket was created successfully. However, when describing s3Bucket and Bucket, their "READY" status are "false". 

### How can we reproduce it?

Try to create S3 bucket with above manifests

### What environment did it happen in?
Crossplane version: 

crossplane/provider-aws-controller:v0.16.0
