### ISSUE TITLE
S3 bucket replication rules can't be applied when the bucket is being created 

### ISSUE THREAD

**Issue by yshu2017** [crossplane/provider-aws#553]
### What happened?

When we apply the following yaml to create a S3 bucket with replication rules, we found that the replication rules were not applied.  We got the following error when describing the "Bucket"

```
Warning  CannotUpdateExternalResource  4m1s (x32175 over 98m)  managed/bucket.s3.aws.crossplane.io  (combined from similar events): cannot create or update: cannot put Bucket replication: InvalidRequest: Versioning must be 'Enabled' on the bucket to apply a replication configuration
       status code: 400, request id: BDA631A781251CFF, host id: 7U2kQhRheWko/QpJjpabk9hV0UuAsJ/G+W9QdWmWMGU+R5SOlBEiu6x92zDCVnSoMH6SnzWYT2I=
```

However, we do have the "versioning" set to "Enabled" in the yaml file (See below). 

In addition, if we do this in two steps: 
first, create a bucket without replication rules.  
Second, we apply the yaml with replication rules and it did succeed. 

### How can we reproduce it?

Apply the following yaml

```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: xxxx-claimed-crossplane-test-yl
  namespace: warrior
  annotations:
    crossplane.io/external-name: xxxx-claimed-crossplane-test-yl
spec:
  forProvider:
    acl: private
    locationConstraint: us-west-2
    versioningConfiguration:
      status: Enabled
    replicationConfiguration:
      role: "arn:aws:iam::00000000:role/crossplane-s3-test-xxxx"
      rules:
        - destination:
            bucket: arn:aws:s3:::test-bucket-xxxxx-crossplane-yl
            storageClass: "STANDARD_IA" 
          status: Enabled
          priority: 10
          deleteMarkerReplication:
            Status: Disabled
          id: "test"
  providerConfigRef:
    name: aws
```

### What environment did it happen in?
Crossplane version: 
crossplane/provider-aws-controller:v0.16.0
