### ISSUE TITLE
iamRoleArn gets added to spec if iamRoleArnRef is used

### ISSUE THREAD

**Issue by PatTheSilent** [crossplane/provider-aws#555]
### What happened?
Running `kubectl apply` with try to remove `iamRoleArn` in `BucketPolicy` if `iamRoleArnRef` is used.
This isn't a problem "per se" because the policy isn't deleted but the behavior is counter intuitive and will produce false positives in CI/CD tools that display changes between manifests and the resources in the cluster. 
I'm more interested in understanding whether this is intended behavior and/or is this going to change.

### How can we reproduce it?
Create any `IAMRole` resource.
Create any `Bucket` resource.
Create a BucketPolicy resource and reference the role with a `yaml` policy and `iamRoleArnRef`.

```yaml
kind: BucketPolicy
apiVersion: s3.aws.crossplane.io/v1alpha2
metadata:
  name: example-bucket-policy
spec:
  deletionPolicy: Delete
  forProvider:
    bucketName: example-bucket-name
    region: eu-west-1
    statements:
      - action:
          - 's3:GetObject'
          - 's3:GetObjectAcl'
          - 's3:GetObjectVersion'
          - 's3:PutObject'
          - 's3:PutObjectAcl'
          - 's3:DeleteObject'
          - 's3:DeleteObjectVersion'
        effect: Allow
        principal:
          awsPrincipals:
            - iamRoleArnRef:
                name: <some-role>
        resource:
          - 'arn:aws:s3:::*'
        sid: DownloadandUpload
    version: '2012-10-17'
  providerConfigRef:
    name: aws-provider
```
Run `kubectl diff` and notice that it wants to remove `iamRoleArn` from the statement.
```diff
-        - iamRoleArn: arn:aws:iam::9999999999:role/example-role
-          iamRoleArnRef:
+        - iamRoleArnRef:
             name: dev1-development-documents
```

### What environment did it happen in?
Crossplane version: `crossplane/crossplane:v0.14.0` and `crossplane/provider-aws-controller:v0.16.0`

Environment details:

* AWS
* Kubernetes version: v1.18.9-eks-d1db3c
* Kubernetes distribution: EKS
