### ISSUE TITLE
Dynamodb writeConnectionSecretToRef does not write secret data

### ISSUE THREAD

**Issue by timpur** [crossplane/provider-aws#580]
### What happened?

Creaded Dynamobd with
```yaml
    reason: Available
    status: "True"
    type: Ready

    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
but no connection string written to the writeConnectionSecretToRef secret. Its created with no data?

Secret (redacted) :
```yaml
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2021-03-05T03:26:00Z"
  name: dynamodb-my-db
  ownerReferences:
  - apiVersion: dynamodb.aws.crossplane.io/v1alpha1
    controller: true
    kind: Table
type: connection.crossplane.io/v1alpha1
```

### How can we reproduce it?

```yaml
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
#...#
  forProvider:
    attributeDefinitions:
    - attributeName: attribute1
      attributeType: S
    keySchema:
    - attributeName: attribute1
      keyType: HASH
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    region: ap-southeast-2
    streamSpecification:
      streamEnabled: true
      streamViewType: NEW_AND_OLD_IMAGES
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: dynamodb-my-db
    namespace: #...#
```

### What environment did it happen in?
Crossplane version: v0.17.0
