### ISSUE TITLE
Duplicate IAMPolicy collisions when using Composites

### ISSUE THREAD

**Issue by mf-lit** [crossplane/provider-aws#590]
### What happened?
I have a composite and matching XRD and claim that I am using to composite an IAM role with a IAM policy and attachment (code below). Whilst the managed resources are created succesfully when I make a claim, the IAMPolicy never reconciles successfully with the following error:

```
Warning  CannotCreateExternalResource  3s (x12 over 4m17s)  managed/iampolicy.identity.aws.crossplane.io  failed to create the IAM Policy:
EntityAlreadyExists: A policy called mytest-zdhw6 already exists. Duplicate names are not allowed.
```

At first glance this looks like a naming clash on the IAM policy itself (i.e. there was already a policy with the name `mytest-zdhw6`. However prior to making a claim there was no policy with this name.

The policy remains in this state indefinitely and so my claim (and it's XR) never reaches a ready state.

Deleting the policy from AWS sometimes solves this (a new policy is created by the provider and reconciliation completes), or sometimes I have to delete the IAMPolicy Managed Resource too, then reconcilliation completes.

Notably, this always occurs with a XR but never if I create the managed resources directly.

### What environment did it happen in?
Crossplane version: 1.1
Provider: 0.17
Kubernetes: 1.19 (EKS)

<details>
<summary><code>composition.yml</code></summary>

```yaml

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-irsa-composition
  labels: {}
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: CompositeIRSA
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
  resources:
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRole
      spec:
        deletionPolicy: Delete
        forProvider:
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "",
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "arn:aws:iam::1234567890:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/<redacted>"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "oidc.eks.eu-west-1.amazonaws.com/id/<redacted>:aud": [
                        "sts.amazonaws.com"
                      ]
                    }
                  }
                }
              ]
            }
        writeConnectionSecretToRef:
          namespace: kube-system
    patches:
    - type: PatchSet
      patchSetName: Metadata
    - fromFieldPath: "spec.parameters.description"
      toFieldPath: "spec.forProvider.description"
    - fromFieldPath: "spec.parameters.provider"
      toFieldPath: "spec.providerConfigRef.name"
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
        - type: string
          string:
            fmt: "%s-iamrole"
    connectionDetails:
    - name: roleArn
      type: FromFieldPath
      fromFieldPath: "status.atProvider.arn"
  - base:
      apiVersion: identity.aws.crossplane.io/v1alpha1
      kind: IAMPolicy
      spec:
        deletionPolicy: Delete
        writeConnectionSecretToRef:
          namespace: kube-system
    patches:
    - type: PatchSet
      patchSetName: Metadata
    - fromFieldPath: "spec.parameters.description"
      toFieldPath: "spec.forProvider.description"
    - fromFieldPath: "spec.parameters.policydoc"
      toFieldPath: "spec.forProvider.document"    
    - fromFieldPath: "spec.parameters.provider"
      toFieldPath: "spec.providerConfigRef.name"
    - fromFieldPath: "metadata.name"
      toFieldPath: "spec.forProvider.name"  
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
        - type: string
          string:
            fmt: "%s-iampolicy"
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      spec:
        deletionPolicy: Delete
        forProvider: 
          roleNameSelector:
            matchControllerRef: true
          policyArnSelector:
            matchControllerRef: true
        writeConnectionSecretToRef:
          namespace: kube-system
    patches:
    - type: PatchSet
      patchSetName: Metadata
    - fromFieldPath: "spec.parameters.provider"
      toFieldPath: "spec.providerConfigRef.name"
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
        - type: string
          string:
            fmt: "%s-iamattach"

  writeConnectionSecretsToNamespace: kube-system

```

</details>

<details>
<summary><code>xrd.yml</code></summary>

```yaml

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeirsas.platform.example.com
spec:
  connectionSecretKeys:
  - roleArn
  defaultCompositionRef:
    name: example-irsa-composition
  group: platform.example.com
  names:
    kind: CompositeIRSA
    plural: compositeirsas
  claimNames:
    kind: ZaapIRSA
    plural: zaapirsas
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  policydoc:
                    description: Policy Document
                    type: string
                  description:
                    description: "Description for IAM Resources"
                    type: string
                  provider:
                    type: string
                  secretNamespace:
                    type: string
                required:
                - policydoc
                - description
            required:
            - parameters
```

</details>

<details>
<summary><code>claim.yml</code></summary>

```yaml

apiVersion: platform.example.com/v1alpha1
kind: ZaapIRSA
metadata:
  namespace: mytest
  name: mytest
spec:
  parameters:
    provider: crossplane-provider-aws
    description: "Helm IRSA"
    policydoc: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [ 
              "s3:PutObject",
              "s3:GetObjectAcl",
              "s3:GetObject",
              "s3:ListBucket",
              "s3:DeleteObject",
              "s3:PutObjectAcl"
            ],
            "Resource": [
              "arn:aws:s3:::mytest",
              "arn:aws:s3:::mytest/*"
            ]
          }
        ]
      }
  writeConnectionSecretToRef:
    name: mytest-irsa

```

</details>
