### ISSUE TITLE
Reference SecurityGroups from SecurityGroups without hardcoding IDs

### ISSUE THREAD

**Issue by larhauga** [crossplane/provider-aws#592]
### What problem are you facing?
When creating `SecurityGroups` with Crossplane, we are not able to reference other `SecurityGroups` without hardcoding the `SecurityGroupIDs`.

For every application, we want a `SecurityGroup` for only that app. This should be referenced when creating a new AWS service, and service `SecurityGroup`, for example a new CacheCluster.

Reason Zero Trust Networking.

### How could Crossplane help solve your problem?
We would like to be able to reference other SecurityGroups in `userIdGroupPairs` in both `Ingress` and `Egress`.

An example where we create a app SG and a CacheCluster SG and want to link them together. This is _not_ necessary in the same composition.

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: applicationname
  labels:
    app: appname
spec:
  forProvider:
    description: application security group attached to pod
    groupName: applicationname
    egress:
    - ipProtocol: tcp
      securityGroupObjectRef:
      - groupIDSelector:
          matchLabels:
            appservices: applicationname
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: cacheClusterSecurityGroup
  labels:
    appservices: applicationname
spec:
  forProvider:
    description: CacheCluster security group for inbound access from application
    groupName: appCacheCluster
    ingress:
      - ipProtocol: tcp
        userIdGroupPairs:
          - groupIDSelector:
              matchLabels:
                app: appname
               #matchControllerRef: [true|false]
            # or a new object ref would be nice (since we only want one without labels in this specific use-case)
            securityGroupObjectRef:
              namespace: app
              name: applicationname
              kind: SecurityGroup
```

**Comment by muvaf** [comment]
@larhauga It should be possible to add `groupIdRef` and `groupIdSelector` that will resolve to `SecurityGroup`. But there is also `userId` field which expects ID of an AWS account. Does this ID is the one that the security group whose name is given via `groupId` is created? In other words, can we assume that user will always enter the account ID of the security group that they specified in `groupId`?

**Comment by larhauga** [comment]
> @larhauga It should be possible to add `groupIdRef` and `groupIdSelector` that will resolve to `SecurityGroup`. But there is also `userId` field which expects ID of an AWS account. Does this ID is the one that the security group whose name is given via `groupId` is created? In other words, can we assume that user will always enter the account ID of the security group that they specified in `groupId`?

@muvaf that would be very nice indeed!
I think it would make sense that the UserID should be that of the given via groupID if that is possible. I think the userID should be that of the provider if not specified.

**Comment by chlunde** [comment]
Related issue: https://github.com/crossplane/crossplane-runtime/issues/250

**Comment by haarchri** [comment]
> @chlunde let me know when this is ready for another review after manual test.

I will have to find out what happens here, it always produces a diff:
```
  Conditions:
    Last Transition Time:  2021-04-08T12:20:03Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-04-08T12:20:04Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
```

It would be nice if --debug printed cmp.Diff in the log

_Originally posted by @chlunde in https://github.com/crossplane/provider-aws/issues/614#issuecomment-815765792_

think i also see this behavior when using self-reference via ingress - @chlunde would be cool to see your suggestion for fix the diff issue merged ;)

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: self-referential-glue
spec:
  forProvider:
    region: eu-central-1
    vpcIdRef:
      name: sample-vpc
    groupName: self-referential-glue
    description: self-referential glue security group
    ingress:
      - fromPort: 0
        toPort: 65535
        ipProtocol: tcp
        userIdGroupPairs:
          - groupName: self-referential-glue
  providerConfigRef:
    name: default
```

```
  Conditions:
    Last Transition Time:  2021-10-30T19:44:33Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-10-30T19:44:34Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:
  Type    Reason                   Age                  From                                         Message
  ----    ------                   ----                 ----                                         -------
  Normal  CreatedExternalResource  4m22s                managed/securitygroup.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Normal  UpdatedExternalResource  20s (x8 over 4m22s)  managed/securitygroup.ec2.aws.crossplane.io  Successfully requested update of external resource
```
