### ISSUE TITLE
Allow assuming multiple web identity roles

### ISSUE THREAD

**Issue by hasheddan** [crossplane/provider-aws#597]
### What problem are you facing?

A number of `provider-aws` users make use of the [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) authentication [flow](https://github.com/crossplane/provider-aws/blob/master/AUTHENTICATION.md) to allow the provider to authenticate to AWS. This is a useful pattern, but restricts the provider `Pod` to only assuming one role because the [EKS Pod Identity Webhook](https://github.com/aws/amazon-eks-pod-identity-webhook) injects this role based on the `Pod` `ServiceAccount`, and [hardcodes the environment variables](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/599cfe7cfc8c72d48a8870e675e19a8169b3dafe/pkg/handler/handler.go#L226) that point to the volume mount, and we [hardcode](https://github.com/crossplane/provider-aws/blob/8767b03cf54e916dbd9b6ff81b259bbeee20d41d/pkg/clients/aws.go#L236) accessing them.

### How could Crossplane help solve your problem?

Users _can_ choose to [manually specify](https://github.com/aws/amazon-eks-pod-identity-webhook/issues/32#issuecomment-588113740) environment variables with multiple ARNs and specific mount paths. In the linked example, two different containers are making use of the same SA token mount, but using different ARNs. Crossplane users may define additional environment variables on their provider containers using the [`ControllerConfig`](https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/ControllerConfig/v1alpha1@v1.1.0). This means that if we added a field to the `provider-aws` `ProviderConfig` that allowed for the `InjectedIdentity` source to be customized with something like `overrideARNEnvVar`, users could have a single provider `Pod` assume multiple roles using a single SA.

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: InjectedIdentity
    overrideARNEnvVar: AWS_ROLE_ARN_2
```

**Comment by lewismarshall** [comment]
As an alternative to creating multiple web identities to associate with the controller process POD, a new "assume role" capability could be added, see #606.

This would present the advantage that new roles can be created as new resources are enabled without any re-deploy or update to the provider controller pod.

E.g. (repeated here for clarity) a provider config with specific roles:
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: InjectedIdentity
    assumeRoleARN: "arn:aws:iam::xyz:role/my-specific-resource" 
```
