### ISSUE TITLE
EFS FileSystem not writing connection details to secret

### ISSUE THREAD

**Issue by gjacobsatl** [crossplane/provider-aws#600]
### What happened?
When creating an EFS FileSystem, the `writeConnectionSecretToRef` creates an empty secret.
I would have expected it to include the filesystemID and any mount targets (#587)

### How can we reproduce it?
```
apiVersion: efs.aws.crossplane.io/v1alpha1
kind: FileSystem
metadata:
  name: testsecret
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
    tags:
      - key: Name
        value: testsecret
  providerConfigRef:
    name: aws-provider
  writeConnectionSecretToRef:
    namespace: default
    name: testsecret
```
then:
`kubectl describe secret testsecret`

### What environment did it happen in?
Crossplane version: 1.1.0
provider-aws: 0.17.0
Kubernetes version:
```Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}```
Kubernetes distribution: EKS
