### ISSUE TITLE
Enable specific role assumption in ProviderConfig

### ISSUE THREAD

**Issue by lewismarshall** [crossplane/provider-aws#606]
### What problem are you facing?

I would like to use specific and least privileged access roles for provisioning AWS resources without creating additional credentials wherever possible.

### How could Crossplane help solve your problem?
Adding a field e.g. `assumeRoleARN` to the `ProviderConfig` would allow AWS STS role assumption (after initial auth) for any specific AWS resource provisioning in conjunction with `providerConfigRef` on the associated resource instances.

This would work when either the `InjectedIdentity` ([IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/)) option is used OR with credentials and would allow all permissions to be granted to only the specific roles for specific provider resources.

As only a single (IRSA) service account or credential would be required, extra permissions can be added as and when an organisation starts using new resources and crossplane would not need redeploying to use them (just deployment of an additional ProviderConfig).

This could be achieved by simply adding a new field `assumeRoleARN` in the ProviderConfig spec e.g.:

```
apiVersion: aws.crossplane.io/v1beta1
  kind: ProviderConfig
  metadata:
    name: my-specific-resource
  spec:
    credentials:
      source: InjectedIdentity
      assumeRoleARN: "arn:aws:iam::xyz:role/my-specific-resource" 
```
This provides an alternative to associating multiple IRSA AWS roles to a single pod with multiple environment variables as described in this different approach: #597.
