### ISSUE TITLE
ec2.securitygroup: Late init lists mixes lists 

### ISSUE THREAD

**Issue by chlunde** [crossplane/provider-aws#618]
### What happened?
* Create an object with a "late init" field set in an array, such as description in security groups in the yaml
* Remove that field from the keyless array, and add another element at the same time, without that "late init" field set 

The "late init" field might now end up in an unrelated element in the array.

Example:

`kubectl create` this object with description for one IP range:
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: sg-1
spec:
  forProvider:
    description: desc
    groupName: sg1
    region: eu-north-1
    ingress:
    - ipProtocol: "tcp"
      fromPort: 2
      toPort: 2
      ipRanges:
      - cidrIp: 10.0.0.0/8
    - ipProtocol: "tcp"
      fromPort: 1
      toPort: 1
      ipRanges:
      - cidrIp: 10.0.0.0/8
        description: "foo"
    vpcId: vpc-...
```

next, `kubectl apply` with a completely different rule, and without description:

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: sg-1
spec:
  forProvider:
    description: desc
    groupName: sg1
    region: eu-north-1
    ingress:
    - ipProtocol: "tcp"
      fromPort: 2
      toPort: 2
      ipRanges:
      - cidrIp: 10.0.0.0/8
    - ipProtocol: "tcp"
      fromPort: 3
      toPort: 3
      ipRanges:
      - cidrIp: 172.0.0.0/8
    vpcId: vpc-...
```

using `kubectl get -o yaml` we see now that the `description: "foo"` from 10.0.0.0/8:1 is now set in `172.0.0.0/8:3`:

```yaml
    - fromPort: 3
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 172.0.0.0/8
        description: foo
      toPort: 3
```

I believe this is because late init is applied instantly after a change, and the only check is that the array sizes are the same:

https://github.com/crossplane/provider-aws/blob/07b4af13224b32ac298d957a7e949cb33abacbdd/pkg/clients/ec2/securitygroup.go#L178-L185

Some ideas:
* Would it be possible to late init as few fields as possible. For examply, why late init description, is it useful?
* Avoid late init if the CR is changed since the last apply - is it possible?
* Detect mismatches for fields like port number, ip ranges etc and abort late init on mismatch

### How can we reproduce it?
Apply yaml 1
Apply yaml 2
Describe

### What environment did it happen in?
Crossplane version: 1.1.0
provider-aws 0.17

cc @larhauga

**Comment by chlunde** [comment]
I think we must use a different approach to handle this perfectly if we do not create an admission webhook which disallows duplicate port ranges. This is OK I believe for the AWS API:

```yaml
    - ipProtocol: "tcp"
      fromPort: 3
      toPort: 3
      ipRanges:
      - cidrIp: 172.0.0.0/8
    - ipProtocol: "tcp"
      fromPort: 3
      toPort: 3
      ipRanges:
      - cidrIp: 10.0.0.0/8      
```

but I think we wil get this back from AWS:
```yaml
    - ipProtocol: "tcp"
      fromPort: 3
      toPort: 3
      ipRanges:
      - cidrIp: 172.0.0.0/8
      - cidrIp: 10.0.0.0/8      
```

either way, I still think the safe guard here is better than the current behavior.
