### ISSUE TITLE
cache.replicationgroup: Engine version mismatch 6.x vs. 6.0.5, never ready

### ISSUE THREAD

**Issue by chlunde** [crossplane/provider-aws#622]
### What happened?
```yaml
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
...
spec:
  forProvider:
    cacheNodeType: cache.t3.micro
    cacheParameterGroupName: default.redis6.x.cluster.on
    engine: redis
    engineVersion: 6.x
...
```

It looks like it never becomes ready:
```
k get replicationgroup -A
NAME                    READY   SYNCED   STATE       VERSION   AGE
my-redis2-c86xx-m6tbp   False   True     modifying   6.x       71m
```

If we patch the code to log why it needs an update, we can find what the difference is:
```go
func cacheClusterNeedsUpdate(kube v1beta1.ReplicationGroupParameters, cc elasticache.CacheCluster) bool { // nolint:gocyclo
	// AWS will set and return a default version if we don't specify one.
	if !reflect.DeepEqual(kube.EngineVersion, cc.EngineVersion) {
		log.Println("- engine version", aws.StringValue(kube.EngineVersion), aws.StringValue(cc.EngineVersion))
		return true
	}
```

```
crossplane-provider-aws-c2ea9b021877-745c78dbcc-kz6gs provider-aws 2021/04/12 14:13:00 - engine version 6.x 6.0.5
```

### How can we reproduce it?
Create a cluster with `6.x` as version.

See also: https://github.com/hashicorp/terraform-provider-aws/issues/15625

### What environment did it happen in?
provider-aws: 0.17
