### ISSUE TITLE
DynamoDB Table issue with billingMode PAY_PER_REQUEST

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane/provider-aws#637]
### What happened?
While option for Table with option of billingmode PAY_PER_REQUEST

Did encounter error during reconciliation but actual table created

### How can we reproduce it?
Create Table with following manifest

```
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: test-table-ppr
spec:
  forProvider:
    region: us-west-1
    attributeDefinitions:
      - attributeName: attribute1
        attributeType: S
    billingMode: PAY_PER_REQUEST
    keySchema:
      - attributeName: attribute1
        keyType: HASH
  providerConfigRef:
    name: aws-provider
```

Error:
```
conditions:
  - lastTransitionTime: "2021-04-23T02:38:01Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-04-23T02:38:01Z"
    message: 'update failed: pre-update failed: only provisionedThroughput and streamSpecification
      updates are supported'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### What environment did it happen in?
Crossplane version: v1.1
Provider: v0.17.0

**Comment by kelvinwijaya** [comment]
Another issue is `streamSpecification` has to be enabled by default even we don't need them, when setting the value to `false` or remove it completely from spec, reconciler will return error such as:

```
message: 'update failed: cannot update Table in AWS: ValidationException: One
      or more parameter values were invalid: You cannot modify stream status while
      updating table IOPS'
```

or

```
message: 'create failed: cannot create Table in AWS: ValidationException: One
      or more parameter values were invalid: Table is being created with a stream
      disabled, UpdateViewType should not be specified'`
```

or

```
message: 'update failed: pre-update failed: only provisionedThroughput and streamSpecification
```

**Comment by HerrmannHinz** [comment]
any news or feedback on this one? 
@kelvinwijaya  did you got it working? 
we are facing the similar.

**Comment by cookiefission** [comment]
I ran in to this problem as well. It may be of note that even when not specified in the original manifest, `provisionedThroughput` is populated when pulled out of the API server with read and write set to 0. 

i.e, if the manifest in the issue description is applied, `kubectl get tables.dy test-table-prr -oyaml` would be (minus the metadata bumf):

```yaml
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: test-table-ppr
spec:
  forProvider:
    region: us-west-1
    attributeDefinitions:
      - attributeName: attribute1
        attributeType: S
    billingMode: PAY_PER_REQUEST
    provisionedThroughput:
      readCapacityUnits: 0
      writeCapacityUnits: 0
    keySchema:
      - attributeName: attribute1
        keyType: HASH
  providerConfigRef:
    name: aws-provider
```
