### ISSUE TITLE
S3 Website configuration won't work without routingRules

### ISSUE THREAD

**Issue by jack1902** [crossplane/provider-aws#650]
### What happened?

When using the `Bucket` resource which defined a `websiteConfiguration` it didn't work stating it had invalid XML. I believe this to be due to routingRules being passed as `[]` in XML speak even though i never pass any in (you can define just an index and error document and that is enough to create a website from an S3)

### How can we reproduce it?

Create a bucket with the following:

```yaml
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: test-bucket
spec:
  forProvider:
    locationConstraint: us-west-1
    tagging:
      tagSet:
        - key: key1
          value: val1
        - key: secondKey
          value: val2
        - key: key3
          value: val3
    websiteConfiguration:
      errorDocument:
        key: error.html
      indexDocument:
        suffix: index.html
  providerConfigRef:
    name: example
```

To fix, i added the following to the above yaml

```yaml
    routingRules:
      - condition:
          keyPrefixEquals: "docs/"
        redirect:
          replaceKeyPrefixWith: /documents
          protocol: http
```

Looking at the code [HERE](https://github.com/crossplane/provider-aws/blob/62405dfa58860a9e8de9b945afad7e188359ea42/pkg/controller/s3/bucket/websiteConfig.go#L145), i see that this bit adds the routingRules even if they aren't defined which i believe results in the XML error: 
```
Message:               update failed: cannot create or update: cannot put Bucket website configuration: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
```

### What environment did it happen in?
Crossplane version: v18
