### ISSUE TITLE
ability to specify IAM role name when created inside of composition

### ISSUE THREAD

**Issue by martin-ducar-gd** [crossplane/provider-aws#666]
### What problem are you facing?
If I create IAMRole as single object, example:
```yaml
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: local-autoscaller-role
  namespace: crossplane-local
  labels:
    name: local-autoscaller-role
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
```
really the role name is taken from `metadata.name` `arn:aws:iam::<account_id>:role/local-autoscaller-role`. However if I do same but in composition, example snippet:
```yaml
    - base:
        apiVersion: identity.aws.crossplane.io/v1beta1
        kind: IAMRole
        metadata:
          name: local-autoscaller-role
          namespace: crossplane-local
          labels:
            name: local-autoscaller-role
        spec:
          forProvider:
            assumeRolePolicyDocument: ""
      patches:
        - type: PatchSet
          patchSetName: TrustRelationship
```
it now is created as the  composite resource base name + the hash, example: `arn:aws:iam::<account_id>:role/my-iam-gbcns-2mhck`. Compared to IAMPolicy though it has the ability to do it. It might be intended, If so it would be nice to hear why.

### How could Crossplane help solve your problem?
Add the optional `name` field in `forProvider` like in [IAMPolicy](https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMPolicy/v1alpha1@v0.18.0#spec-forProvider-name)
