### ISSUE TITLE
RDSInstance: provider-aws is requesting too many AddTagsToResource to aws rds endpoint

### ISSUE THREAD

**Issue by grassiale** [crossplane/provider-aws#670]
### What happened?

I have installed some managed rdsinstance resources in my kubernetes cluster with crossplane 1.2.1 and crossplane provider aws  v0.18.0. The instances are in the form:
```
napiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/external-name: test-103
    meta.helm.sh/release-name: rds
    meta.helm.sh/release-namespace: "103"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: test-103
spec:
  deletionPolicy: Orphan
  forProvider:
    allocatedStorage: 20
    allowMajorVersionUpgrade: false
    autoMinorVersionUpgrade: false
    availabilityZone: eu-west-1a
    backupRetentionPeriod: 7
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t3.micro
    dbName: master
    dbParameterGroupName: default.postgres12
    dbSubnetGroupName: rds-subnet-group
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: postgres
    engineVersion: "12.5"
    kmsKeyId: arn:aws:kms:eu-west-1:XXXXXXXXX:alias/keyname
    licenseModel: postgresql-license
    masterPasswordSecretRef:
      key: masterPassword
      name: rds-instance
      namespace: "103"
    masterUsername: masteruser
    monitoringInterval: 0
    multiAZ: false
    port: 5432
    preferredBackupWindow: 14:00-15:00
    preferredMaintenanceWindow: Sun:15:00-Sun:16:00
    publiclyAccessible: false
    region: eu-west-1
    storageEncrypted: true
    storageType: gp2
    tags:
    - key: crossplane-kind
      value: rdsinstance.database.aws.crossplane.io
    - key: crossplane-name
      value: test-103
    - key: crossplane-providerconfig
      value: crossplane-provider-aws
    vpcSecurityGroupIds:
    - sg-YYYYYYYYYYYY
  providerConfigRef:
    name: crossplane-provider-aws
  writeConnectionSecretToRef:
    name: rds-credentials
    namespace: "103"
 ```
 The instances is created correctly and the status of the k8s resource is:
 ```
 atProvider:
    dbInstanceArn: arn:aws:rds:eu-west-1:XXXXXXXXX:db:test-103
    dbInstanceStatus: available
    dbParameterGroups:
    - dbParameterGroupName: default.postgres12
      parameterApplyStatus: in-sync
    dbResourceId: db-XJZN7XUDHKP6RA6LOKMPZFYCU4
    dbSubnetGroup:
      dbSubnetGroupDescription: rds-subnet-group
      dbSubnetGroupName: rds-subnet-group
      subnetGroupStatus: Complete
      subnets:
      - subnetAvailabilityZone:
          name: eu-west-1a
        subnetIdentifier: subnet-XXXXXXX
        subnetStatus: Active
      - subnetAvailabilityZone:
          name: eu-west-1b
        subnetIdentifier: subnet-YYYYYYY
        subnetStatus: Active
      vpcId: vpc-HHHHHHHHHH
    endpoint:
      address: test-103.FFFFFFFFF.eu-west-1.rds.amazonaws.com
      hostedZoneId: ZZZZZZZZZZZZZZZ
      port: 5432
    instanceCreateTime: "2021-05-12T15:00:00Z"
    latestRestorableTime: "2021-05-17T14:39:07Z"
    optionGroupMemberships:
    - optionGroupName: default:postgres-12
      status: in-sync
    pendingModifiedValues:
      pendingCloudwatchLogsExports: {}
    vpcSecurityGroups:
    - status: active
      vpcSecurityGroupId: sg-YYYYYYYYYYYY
  conditions:
  - lastTransitionTime: "2021-05-17T14:13:45Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-05-17T14:13:46Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
 ```

Despite everything looking normal, we noticed an increase in aws rds endpoints requests of the type `AddTagsToResource` since we installed these rds instances.
By querying our aws audit logs, we noticed many requests containing either this request payload :
```
{
  "resourceName": "arn:aws:rds:eu-west-1:XXXXXXXXX:db:test-103",
  "tags": [
    {
      "key": "crossplane-kind",
      "value": "rdsinstance.database.aws.crossplane.io"
    },
    {
      "key": "crossplane-name",
      "value": "test-103"
    },
    {
      "key": "crossplane-providerconfig",
      "value": "crossplane-provider-aws"
    }
  ],
  "dryRun": false
}
``` 
or 
```
{
  "tags": [
    {
      "value": "rdsinstance.database.aws.crossplane.io",
      "key": "crossplane-kind"
    },
    {
      "value": "test-103",
      "key": "crossplane-name"
    },
    {
      "value": "crossplane-provider-aws",
      "key": "crossplane-providerconfig"
    }
  ],
  "dryRun": false,
  "resourceName": "arn:aws:rds:eu-west-1:XXXXXXXXX:db:test-103"
}
```
That makes me guess there is something wrong on how crossplane provider aws handles tag sorting when checking diffs.

Also, crossplane debug logs show every minute the line:
`2021-05-17T15:43:30.676Z	DEBUG	provider-aws	Successfully requested update of external resource	{"controller": "managed/rdsinstance.database.aws.crossplane.io", "request": "/test-103", "uid": "eae52e28-f6d8-44f5-ae87-e42910d69fed", "version": "402636920", "external-name": "test-103", "requeue-after": "2021-05-17T15:44:30.676Z"}`
That is exactly the same frequency we can see those `AddTagsToResource` requests
### What environment did it happen in?
Crossplane version: 
crossplane 1.2.1 
crossplane provider aws  v0.18.0.
Kubernetes v1.18.9-eks-d1db3c
Kubernetes distribution: EKS
