### ISSUE TITLE
IAM Role Compatibility for aws provider controller

### ISSUE THREAD

**Issue by gvinayakk** [crossplane/provider-aws#674]
### What happened?

Post successfully installing crossplane v1.2 and going through https://github.com/crossplane/provider-aws/issues/110, I was able to successfully provision aws direct/managed resources using IAM role for our kube2iam enabled clusters.

Encountering following issue with direct/managed resources related to v1alpha1 apiVersion, the resource creation fails with following message:
```
EmptyStaticCreds: static credentials are empty
```

### How can we reproduce it?

You can try this for few v1apha1 api version CRDs, I was mainly hitting this for DBCluster & DBClusterParameters CRD
---
apiVersion: v1
kind: Secret
metadata:
  name: testcluster-rds-master-password
type: Opaque
data:
  password: cmFuZG9tcGFzc0AxMjM=

---
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: testcluster-rds-cluster
spec:
  forProvider:
    databaseName: testdatabase
    enableCloudwatchLogsExports:
      - postgresql
    enableIAMDatabaseAuthentication: true
    engine: aurora-postgresql
    engineVersion: "10.14"
    storageEncrypted: true
    finalDBSnapshotIdentifier: final-testcluster-rds-1234
    skipFinalSnapshot: false
    masterUserPasswordSecretRef:
      name: testcluster-rds-master-password
      key: password
      namespace: crossplane-system
    region: us-west-2
    dbSubnetGroupNameRef:
      name: testcluster-subnet
    vpcSecurityGroupIDRefs:
      - name: testcluster-vpc-sg
    tags:
      - key: Owner
        value: ops
      - key: Cluster
        value: testcluster
  writeConnectionSecretToRef:
      name: testcluster-rds-cluster-secret
      namespace: crossplane-system
  providerConfigRef:
    name: aws-provider
  deletionPolicy: Delete

### What environment did it happen in?
Crossplane version: v1.2
Provider: crossplane/provider-aws:master

ProviderConfig:
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
spec:
  credentials:
    source: None

* Cloud provider or hardware configuration: AWS
* Kubernetes version (use `kubectl version`):  Client Version: v1.16.0, Server Version: v1.18.9-eks-d1db3c
*
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS
* OS (e.g. from /etc/os-release): CentOS-7
* Kernel (e.g. `uname -a`): 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eloo** [comment]
Any updates here? 
Looks like i'm running into the same issue

**Comment by chlunde** [comment]
Personally I think it would be best to move from kube2iam to [IRSA/pod identity webhooks](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/).

But I also _suspect_ InjectedIdentity will work once we move to the latest AWS SDK versions, because provider-aws will no longer explicitly use the web identity code, but rely on the code in the SDK. https://github.com/crossplane/provider-aws/blob/0407b637600536044fdec8c1625b99ef7d0c7c02/pkg/clients/aws.go#L214-L222

**Comment by kelvinwijaya** [comment]
Hi @chlunde 

Updating the SDK probably may not solve this issue. Might be due to the newer implementation as the old Resource works (ElastiCache, S3, old RDSInstance, etc).

I am exploring provider-aws controller to use KIAM role through metadata.annotation injection from ControllerConfig Resource.

It seem this error only happen for some resources. e.g. Tables (DynamoDB) but not ReplicationGroup (ElasticCache)

**DynamoDB**
```
conditions:
  - lastTransitionTime: "2021-10-04T15:26:43Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-11-09T06:54:16Z"
    message: 'observe failed: failed to describe Table: EmptyStaticCreds: static credentials
      are empty'
    reason: ReconcileError
    status: "False"
    type: Synced
```

**ElasticCache**
```
conditions:
  - lastTransitionTime: "2021-10-27T09:04:58Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-11-09T06:54:41Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

I noticed that **DynamoDB/Table** is created with the latest codegen, 
https://github.com/crossplane/provider-aws/commit/1972d7317541b03d517f392acd6912102a394e37

How i know this is because my SES resource also have the same Sync issue which build with the same codegen version : `CODE_GENERATOR_COMMIT ?= cac5654b7bb64c8f754ad9af01799ef70d9541b6`

And i suspect this will happen to other new resources that build with the codegen:
so meaning the newer resources may have issues: 
GENERATED_SERVICES="apigatewayv2,cloudfront,dynamodb,efs,glue,kafka,kms,lambda,rds,secretsmanager,servicediscovery,sfn,transfer"

**Comment by kelvinwijaya** [comment]
HI All,

Just to update, the iam role assumption work with the following spec (i tested with KIAM):

```yaml
spec:
  credentials:
    source: InjectedIdentity
```

Apparently if we set `source:None`, this will hit into issue as the code is looking for static credentials *config.WithCredentialsProvider* : https://github.com/crossplane/provider-aws/blob/cb296d7308f7590c1cb88dc4a31ca59ccbb56381/pkg/clients/aws.go#L259


Hope it helps!
