### ISSUE TITLE
Create AWS KMS new key issue

### ISSUE THREAD

**Issue by dimitryvoronov** [crossplane/provider-aws#685]
### What happened?
Hello crossplane community,
An error occurs when a new AWS KMS key is created. 

### How can we reproduce it?

Crossplane installed as k8s operator as replicaset with crossplane pod, aws provider and rbac manager.
I am trying to create a new KMS key, empty one as described below:

file: newkms.yaml
```
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: eks-kms-key-crossplane
  namespace: infra
spec:
  forProvider:
    enabled: true
    customerMasterKeySpec: "SYMMETRIC_DEFAULT"
    description: ksm key for eksvault crossplane
    keyUsage: ENCRYPT_DECRYPT
    region: eu-central-1
```

Once I run kubectl apply -f newkms.yaml
I get Invalid keyID error.

Error description:
[kubectl-output-kms-key.txt](https://github.com/crossplane/provider-aws/files/6570120/kubectl-output-kms-key.txt)

### What environment did it happen in?
AWS environment:
K8s v1.18.9-eks-d1db3c
Crossplane version: 1.2.1

#### 
Am I missing something or this looks like a bug, on slack channel there was a kind of similar issue but also with defining an external-name in annotations.
Any advice or help really appreciated. Thank you.

**Comment by freegn** [comment]
Hello @muvaf apologies for that, I've marked a template I've used for object creation and uploaded an output of kubectl for convience.

**Comment by librannk** [comment]
I am also getting an error while creating not exactly similar, "failed to describe Key: EmptyStaticCreds: static credentials are empty"

`        apiVersion: kms.aws.crossplane.io/v1alpha1
        kind: Key
        metadata:
          name: kms-key-test
          namespace: crossplane-local
        spec:
          writeConnectionSecretToRef:
            name: kms-key-test
            namespace: crossplane-local
          providerConfigRef:
            name: crossplane-provider-aws-local
          forProvider:
            region: us-east-1
            origin: "EXTERNAL"
            enabled: true
            customerMasterKeySpec: "SYMMETRIC_DEFAULT"
            keyUsage: ENCRYPT_DECRYPT
            tags:
              - tagKey: KMS Key
                tagValue: ""`

**Comment by librannk** [comment]
just to add created the sample key from the documentation, even this didn't work.  
```
apiVersion: kms.aws.crossplane.io/v1alpha1kind: Keymetadata:  name: dev-keyspec:  providerConfigRef:    name: example  forProvider:    policy: |-      {        "Version": "2012-10-17",        "Statement": [          {            "Sid": "Enable IAM User Permissions",            "Effect": "Allow",            "Principal": {              "AWS": "arn:aws:iam::123456789012:root"            },            "Action": "kms:*",            "Resource": "*"          }        ]      }    region: eu-central-1    tags:    - tagKey: k1      tagValue: v1
```

a

**Comment by haarchri** [comment]
what is the exception in crossplane when you create the example ?
on my side it is working:

```
➜  kms git:(master) ✗ kubectl get key.kms.aws.crossplane.io/dev-key
NAME      READY   SYNCED   EXTERNAL-NAME
dev-key   True    True     ea87e120-8417-4ade-8499-9e093d5664d7
```

**Comment by librannk** [comment]
thanks for commenting, are you using IRSA for credentials? or directly? .... I am using IRSA ..
![image](https://user-images.githubusercontent.com/33729365/120655163-043f4980-c4a0-11eb-8d77-4644c818104b.png)

**Comment by jwitrick** [comment]
I am similar getting an error when trying to create an AWS KMS key:
`Message:               observe failed: failed to describe Key: NotFoundException: Invalid keyId efskey`

Below is my example:

```
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: efskey
spec:
  deletionPolicy: Delete
  writeConnectionSecretToRef:
    name: efs-key
    namespace: default
  forProvider:
    description: Encryption key used to encrypt EFS resources
    region: ap-southeast-2
    policy: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "Allow access to EFS for all principals in the account that are authorized to use EFS",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:CreateGrant",
                "kms:DescribeKey"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "kms:ViaService": "elasticfilesystem.ap-southeast-2.amazonaws.com",
                    "kms:CallerAccount": "YYYYYYYYYY"
                }
            }
          },
          {
            "Sid": "Allow direct access to key metadata to the account",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::YYYYYYYYYY:root"
            },
            "Action": [
                "kms:Describe*",
                "kms:Get*",
                "kms:List*",
                "kms:RevokeGrant"
            ],
            "Resource": "*"
          }
        ]
      }
    
    tags:
    - tagKey: Name
      tagValue: EFS

**Comment by haarchri** [comment]
today we also have one environment with this issue directly in eks... when we apply the same via a local kind cluster everything is working ...

looks like directly after applied the ressource in k8s - crossplane adds annotation for example:
`crossplane.io/external-name: efs-key` 
but this is wrong because the external-name is
`obj.KeyMetadata.KeyId`

**Comment by Hammond95** [comment]
I have found the same issue still occurs.
I am running on the following versions:

```
crossplane/crossplane:v1.2.1
crossplane/provider-aws-controller:v0.18.1
```

----------

#### manifest-1.yaml - Invalid keyId

```yaml
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: "martin"
  labels:
    purpose: paas-orgs
    provider: aws
spec:
  deletionPolicy: "Delete"
  providerConfigRef:
    name: crossplane-provider-aws
  forProvider:
    bypassPolicyLockoutSafetyCheck: false
    customerMasterKeySpec: "SYMMETRIC_DEFAULT"
    enabled: true
    keyUsage: "ENCRYPT_DECRYPT"
    origin: "AWS_KMS"
    policy: "POLICY JSON"
    region: "eu-west-1"
    tags: 
      - tagKey: author
        tagValue: crossplane-provider-aws
  writeConnectionSecretToRef:
    name: "martin-test-xplane-kms-key-secret"
    namespace: "crossplane-system"
```

**Results:**

- The k8s object is created
```
NAME             READY       SYNCED        EXTERNAL-NAME
martin             False          martin
```
- Getting the error: `failed to describe Key: NotFoundException: Invalid keyId martin`

----------

#### manifest-2.yaml - keyId not found

Using a valid keyId but the key doesn't exist on the account, but my objective is to create a new key.

```yaml
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: "martin"
  annotations:
    crossplane.io/external-name: "55555555-089b-4193-bf05-03f6a3e743c4"
  labels:
    purpose: paas-orgs
    provider: aws
spec:
  deletionPolicy: "Delete"
  providerConfigRef:
    name: crossplane-provider-aws
  forProvider:
    bypassPolicyLockoutSafetyCheck: false
    customerMasterKeySpec: "SYMMETRIC_DEFAULT"
    enabled: true
    keyUsage: "ENCRYPT_DECRYPT"
    origin: "AWS_KMS"
    policy: "... POLICY JSON ..."
    region: "eu-west-1"
    tags: 
      - tagKey: author
        tagValue: crossplane-provider-aws
  writeConnectionSecretToRef:
    name: "martin-test-xplane-kms-key-secret"
    namespace: "crossplane-system"
```

**Results:**

- The k8s object is created
```
NAME             READY       SYNCED        EXTERNAL-NAME
martin             False          martin            55555555-089b-4193-bf05-03f6a3e743c4
```
- Getting the error: `failed to describe Key: NotFoundException: Key 'arn:aws:kms:eu-west-1:**********:key/55555555-089b-4193-bf05-03f6a3e743c4' does not exist`

----------

Using an existing keyId it works as expected attaching the k8s resource to the existing AWS one.

```
NAME                                   READY   SYNCED   EXTERNAL-NAME
7*******-0b**-4ce4-####-7e3d1*******   True    True     7*******-0b**-4ce4-####-7e3d1*******
```
