### ISSUE TITLE
DBCluster generated secret doesn't contain database endpoint

### ISSUE THREAD

**Issue by rguichard** [crossplane/provider-aws#695]
### What happened?

When creating a DBCluster (with Aurora serverless as engine), the Kubernetes Secret generated contains only the username and password of the database. It does not contain the endpoint neither the port.

Since this is an Aurora serverless database, we can't use RDSInstance and the endpoint and the port should be available in the generated Secret.

### How can we reproduce it?

Create a DBCluster :

```
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: aurora
spec:
  forProvider:
    region: eu-west-1
    engineMode: serverless
    engine: aurora-mysql
    masterUsername: admin
    masterUserPasswordSecretRef:
      name: aurora-database
      namespace: default
      key: mysql-root-password
    dbSubnetGroupName: aurora
    vpcSecurityGroupID:
      - aurora-sg
    databaseName: aurora-db
  writeConnectionSecretToRef:
    name: aurora-secrets
    namespace: default
```
```
kubectl describe secrets aurora-secrets
Name:         aurora-secrets
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  connection.crossplane.io/v1alpha1

Data
====
password:  30 bytes
username:  5 bytes
```

### What environment did it happen in?
Crossplane version:  1.2
crossplane/provider-aws@v0.18.1

* Cloud provider : aws
* Kubernetes version (use `kubectl version`) : v1.19.6-eks-49a6c0
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) : EKS
