### ISSUE TITLE
Certificate not synced when using Private CA

### ISSUE THREAD

**Issue by RafalMaleska** [crossplane/provider-aws#735]
### What happened?

When creating certificate which is referencing a private CA, the managed resource is SYNCED=false.
The reason is: "failed to update the Certificate resource: InvalidStateException: The UpdateCertificateOptions command is not permitted for private certificates."  

### How can we reproduce it?
Create certificate which is referencing a private CA with crossplane/provider aws

```
apiVersion: acm.aws.crossplane.io/v1alpha1
kind: Certificate
metadata:
  name: poc-certificate
spec:
  forProvider:
    region: eu-central-1 
    renewCertificate: true
    certificateAuthorityARN: arn:aws:acm-pca:eu-central-1:123456789:certificate-authority/xxxx-yyyy-zzzz
    domainName: "*.mesh-pca.svc.cluster.local"
    certificateTransparencyLoggingPreference: DISABLED
  providerConfigRef:
    name: dev-123456789
```

### What environment did it happen in?
Crossplane version: v1.1.0
Provider AWS: v0.19.0

**Comment by haarchri** [comment]
hi @RafalMaleska  
i added a MR and used the following configuration:

```
apiVersion: acm.aws.crossplane.io/v1alpha1
kind: Certificate
metadata:
  name: poc-certificate
spec:
  forProvider:
    region: eu-central-1 
    certificateAuthorityARN: arn:aws:acm-pca:eu-central-1:255932642927:certificate-authority/e6a6ac34-056a-49b3-802c-3b446580d9a4
    domainName: "*.mesh-pca.svc.cluster.local"
    certificateTransparencyLoggingPreference: DISABLED
    tags:
    - key: Name
      value: example
  providerConfigRef:
    name: default
```

```
NAME                                                DOMAINNAME                     STATUS   READY   SYNCED   AGE
certificate.acm.aws.crossplane.io/poc-certificate   *.mesh-pca.svc.cluster.local   ISSUED   True    True     3m19s
```

![image](https://user-images.githubusercontent.com/21083497/123525212-4a6a8000-d6cf-11eb-975d-4f48fe165998.png)
