### ISSUE TITLE
Mounttarget's securityGroup is not provisioned in AWS EFS

### ISSUE THREAD

**Issue by mithie** [crossplane/provider-aws#836]
### What happened?

Creating a crossplane mounttarget resource doesn't provision the referenced securityGroupId in AWS EFS. Instead the default securityGroupId is being used for the mount target.

### How can we reproduce it?

1. create a securitygroup resource with crossplane
2. create subnet resources for each availability zone with crossplane.
3. create mounttarget resources for each subnet and reference the securitygroup and subnet resources in each mounttarget

``example mounttarget.yaml``

```
---
apiVersion: efs.aws.crossplane.io/v1alpha1
kind: MountTarget
metadata:
  name: efs-mounttarget-1a
spec:
  forProvider:
    region: eu-west-1
    fileSystemIDRef:
      name: sample-efs
    subnetIDRef:
      name: sample-vpc-private-eu-west-1a
    securityGroupsRefs:
      - name: efs-sg
  providerConfigRef:
    name: aws-provider
```

Now, double-check one of the created mounttarget resources:
``kubectl get mounttarget efs-mounttarget-1a -oyaml``

This will return something similiar like this:

```
spec:
  deletionPolicy: Delete
  forProvider:
    fileSystemID: fs-df12f3eb
    fileSystemIDRef:
      name: sample-efs
    region: eu-west-1
    securityGroups:
    - sg-0f771a7a3bf123bef
    securityGroupsRefs:
    - name: efs-sg
    subnetID: subnet-0c1ba23f45e678910
    subnetIDRef:
      name: eks-vpc-private-eu-west-1a
  providerConfigRef:
    name: aws-provider
```

In this output the securityGroups property contains the correct id from the security group created in step 1 above.

Now, if you verify the mount target setup in the AWS EFS console you will see that the security group id is a different one (default security group) and not the one defined in the crossplane resource. The same happens when ``securityGroups`` property is used instead of `securityGroupsRefs ` in the mounttarget resource.

As a result that leads to pods not being able to be created on EKS since the wrong security group is being provisioned with the mounttarget crd.

### What environment did it happen in?
Crossplane version: 1.4.1
Kubernetes version: 1.20
