### ISSUE TITLE
Unable to provision Aurora-mysql RDSInstance -  InvalidParameterValue: The parameter AllocatedStorage must be provided and must not be null

### ISSUE THREAD

**Issue by kiich** [crossplane/provider-aws#842]
### What happened?
Followed the documentation and examples found in the repo to provision RDSInstance using the yaml below:
```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: myaurora
spec:
  deletionPolicy: Delete
  forProvider:
    dbSubnetGroupName: "dbsubnet"
    region: us-west-2
    deletionProtection: false
    masterUsername: admin
    publiclyAccessible: false
    dbInstanceClass: db.t2.medium
    dbName: myaurora
    engine: aurora-mysql
    tags:
      - key: Team
        value: "My Team"
  providerConfigRef:
    name: crossplane-provider-config
  writeConnectionSecretToRef:
    name: rds-conn-string
    namespace: default
```

As you can see, i omitted the `allocatedStorage` setting because the documentation says it is not applicable.
However when i apply the above via crossplane, i am getting:
```
    message: "create failed: cannot create RDS instance: InvalidParameterValue: The
      parameter AllocatedStorage must be provided and must not be null.\n\tstatus
      code: 400, request id: aaaaa"
```

I can't seem to find any example code to do the above for aurora-mysql so either i am missing something or doing it the wrong way?

I have seen some posts about creating the Aurora in the AW console manually and then creating a replicate in Crossplane - but that's not what I am aiming to do.

### How can we reproduce it?
Apply the yaml above

* Cloud provider or hardware configuration - AWS
* Kubernetes version (use `kubectl version`) - v1.19.13-eks-8df270
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) - EKS
* OS (e.g. from /etc/os-release) - Amazon Linux
