### ISSUE TITLE
Unable to DBCluster "aurora-mysql" and assign instances

### ISSUE THREAD

**Issue by eloo** [crossplane/provider-aws#844]
### What happened?
Hi,
i'm currently trying to setup an aurora cluster with "aurora-mysql" engine and add some instances to it.
The creation of the db cluster seems to work  as expected but when i try to assign a rdsinstance to it i'm getting errors. 

The error shown for the rds instance is the following
```
create failed: cannot create RDS instance: InvalidParameterCombination: The requested DB Instance will be a member of a DB Cluster. Set master user password for the DB Cluster.
```

The interesting part is that i have set the `masterUserPasswordSecretRef` in the db cluster but still see this error. 
I have also tried to set the `masterPasswordSecretRef` in the instance but this leads also to the same error.

So currently it seems that its not possible to create a DBCluster with instances.

### How can we reproduce it?
dbcluster.yaml
```
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: example-rdsmysql-aurora
spec:
  forProvider:
    region: eu-central-1
    engine: aurora-mysql
    masterUsername: admin
    masterUserPasswordSecretRef:
      name: dbcluster-pwd
      namespace: crossplane-system
      key: password
    databaseName: auroradb
  writeConnectionSecretToRef:
    name: aurora-secrets
    namespace: default
  providerConfigRef:
    name: aws-provider-config

---
apiVersion: v1
kind: Secret
metadata:
  name: dbcluster-pwd
  namespace: crossplane-system
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123
```

instance.yaml
```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rdsmysql
spec:
  forProvider:
    region: eu-central-1
    dbInstanceClass: db.t3.small
    engine: aurora-mysql
    skipFinalSnapshotBeforeDeletion: true
    dbClusterIdentifier: example-rdsmysql-aurora
  providerConfigRef:
    name: aws-provider-config
```

### What environment did it happen in?
Crossplane version: 1.3.1

Cloud provider or hardware configuration - aws-provider v0.19.0
Kubernetes version (use kubectl version) - v1.21.2-eks-0389ca3
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) - EKS
OS (e.g. from /etc/os-release) - Amazon Linux
