### ISSUE TITLE
Huge number of AWS API calls

### ISSUE THREAD

**Issue by robertgates55** [crossplane/provider-aws#847]
Is there anything that can limit the number of calls being made to the AWS API? Since enabling this provider in a dev cluster our AWS bill jumped noticeably - which turned out to be because of crossplane calls being logged by cloudwatch. We were seeing 70qps hitting the AWS APIs, causing rate limiting!

Is that expected? Is there any way to dial down the chattiness?

**Comment by chlunde** [comment]
@robertgates55 there has been some issues which has triggered frequent reconciles, but you should not see 70 qps. Can you check
* what version you are running
* how many managed resources do you have
* check what service/API call this is in cloud trail. If there is an error message, what is it?
* if one specific object, what does it look like in k8s? Can you show the Update parameters from cloud trail?

You can normally dial down the chattiness with a ControllerConfig, but 70 qps might be a different issue:

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws-config
spec:
  args:
  - --poll=5m
```

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-aws
  namespace: crossplane-system
spec:
...
  controllerConfigRef:
    name: provider-aws-config
```
