### ISSUE TITLE
RDSInstance joining aurora-mysql ClusterDB - "Set master user password for the DB Cluster"

### ISSUE THREAD

**Issue by robertgates55** [crossplane/provider-aws#854]
provider version: `0.19.1`
I'm trying to create a DBCluster (aurora-mysql 5.7) and then have an RDSInstance join that cluster. I've seen https://github.com/crossplane/provider-aws/pull/273 and attempted providing an empty secret - but not having any joy.

My yaml looks like this:

```yaml
apiVersion: v1
data:
  password: UGFzc3dvcmQxMjM=
kind: Secret
metadata:
  name: master-user-password
  namespace: default
---
metadata:
  name: rg-test-dbcluster
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
spec:
  forProvider:
    dbSubnetGroupNameRef:
      name: rg-aurora-cluster-test-rmkt4-mtr45
    engine: aurora-mysql
    engineMode: provisioned
    engineVersion: 5.7.mysql_aurora.2.10.0
    masterUsername: admin
    masterUserPasswordSecretRef:
      namespace: default
      name: master-user-password
      key: password
    port: 3306
    region: eu-west-1
---
apiVersion: v1
kind: Secret
metadata:
  name: empty-secret
  namespace: default
type: Opaque
---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rg-test-dbcluster-instance-0
spec:
  forProvider:
    dbClusterIdentifier: rg-test-dbcluster
    engine: aurora-mysql
    dbInstanceClass: db.t3.micro
    masterPasswordSecretRef:
      namespace: default
      name: empty-secret
      key: password
```

The `DBCluster` is created (I can see it in the AWS Console) but the RDSInstance is failing with:
```
   Conditions:
     Last Transition Time:  2021-10-04T07:38:43Z
     Message:               create failed: cannot create RDS instance: InvalidParameterCombination: The requested DB Instance will be a member of a DB Cluster. Set master user password for the DB Cluster.
     Reason:                ReconcileError
     Status:                False
     Type:                  Synced
```

Could anyone give me any clues?
