### ISSUE TITLE
S3 bucket: connectionDetails.fromFieldPath is not giving back a generated S3 bucket name in a secret

### ISSUE THREAD

**Issue by denist-huma** [crossplane/provider-aws#856]
### What happened?

How to get back a real S3 bucket name in a secret?
After I have a first step forward with custom CompositeBucket, I am struggling to make work 

        connectionDetails.fromFieldPath: "metadata.annotations['bucket-name']"

In my IAMAccessKey I got this annotation visible and populated. But the secret has only the username and password, missing a bucket-name key I want.

The CompositeBucket is working together with a bucket policy, IAM user, access key.

I appreciate @muvaf helping me in [slack](https://crossplane.slack.com/archives/CEG3T90A1/p1633083579223000).
But the problem is not solved. I used all the suggested options.
Not working connectionDetails: 

```yaml
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            acl: private
            locationConstraint: eu-west-2
            accelerateConfiguration:
              status: Enabled
            versioningConfiguration:
              status: Enabled
            serverSideEncryptionConfiguration:
              rules:
                - applyServerSideEncryptionByDefault:
                    sseAlgorithm: AES256
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
      # Patches copy or "overlay" the value of a field path within the composite
      # resource XR to a field path within the composed resource CR.
      patches:
        - fromFieldPath: "status.atProvider.arn"
          toFieldPath: "metadata.annotations['bucket-arn']"
          type: ToCompositeFieldPath
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.annotations['bucket-name']"
          type: ToCompositeFieldPath
      # Tried to get back a real S3 bucket name in a secret
      # connectionDetails:
      #   - fromFieldPath: "metadata.name"
      #     name: bucket-name
      #     type: FromFieldPath
```

```yaml
    - name: access-key
      base:
        apiVersion: identity.aws.crossplane.io/v1alpha1
        kind: IAMAccessKey
        spec:
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        - fromFieldPath: "metadata.annotations['user-name']"
          toFieldPath: "spec.forProvider.userNameRef.name"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-iam-access-key"
        # Tried to get back a real S3 bucket name in a secret
        # - fromFieldPath: "metadata.annotations['bucket-name']"
        #   toFieldPath: "metadata.annotations['bucket-name']"
        #   policy:
        #     fromFieldPath: Required
      # In addition to a base and patches, this composition declares that
      # it can fulfil the connectionSecretKeys contract required by the definition.
      # This resource writes a connection secret
      # with a username and password that may be used to connect to it.
      # These connection details will also be exposed via the composite resource's
      # connection secret. Exactly one composed resource must provide each secret
      # key, but different composed resources may provide different keys.
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        # Tried to get back a real S3 bucket name in a secret
        # - fromFieldPath: "metadata.annotations['bucket-name']"
        #   name: bucket
        #   type: FromFieldPath
 ```

My secret is still the same as the usual IAM access key secret, 2 entries.
 ```sh
$ kubectl get secret my-private-bucket-secret -n operator-sandbox
NAME                       TYPE                                DATA   AGE
my-private-bucket-secret   connection.crossplane.io/v1alpha1   2      41s
```

### How can we reproduce it?

I have my manifests in [my gist](https://gist.github.com/denist-huma/cf6ae14f62dc7d96d74736dbdd5f67e8) 

### What environment did it happen in?
Crossplane version: 1.4.1
crossplane/provider-aws-controller:v0.18.1

* Kubernetes version (use `kubectl version`) v1.19.12-gke.2101
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) GKE
