### ISSUE TITLE
Adopting existing S3 bucket would not reach Available condition

### ISSUE THREAD

**Issue by aylei** [crossplane/provider-aws#874]
### What happened?
I created an `buckets.s3.aws.crossplane.io` object which should adopt an existing S3 bucket, but the CR never reached `Available` condition and the controller was constantly updating the bucket.

### How can we reproduce it?

1. Create an s3 bucket
2. Create an `buckets.s3.aws.crossplane.io` object to adopt the s3 bucket, example:

```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: awesome-name
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-west-2
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
```

### What environment did it happen in?
Crossplane version: `v0.19.0`
