### ISSUE TITLE
Add missing Resource ID to OpenIDConnectProvider

### ISSUE THREAD

**Issue by goober** [crossplane/provider-aws#875]
### What problem are you facing?

We are trying to create a Composition that creates an EKS cluster with Crossplane preconfigured.
However, we are not able to complete the guide described in Step 6 from the documentation https://github.com/crossplane/provider-aws/blob/master/AUTHENTICATION.md#steps

We can create an OpenIdConnectProvider with the information available from the [`status.atProvider.issuer.url`](https://doc.crds.dev/github.com/crossplane/provider-aws/eks.aws.crossplane.io/Cluster/v1beta1@v0.19.1#status-atProvider-identity-oidc-issuer), but we cannot create a corresponding IAMRole for the provider-aws' service-account.

According to the documentation we need to create an IAM role similar to this:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "${OIDC_PROVIDER}:sub": "system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:provider-aws-*"
        }
      }
    }
  ]
}
```

Our attempt was to create the following Composition:
```yaml
- name: iam-crossplane
      base:
        apiVersion: identity.aws.crossplane.io/v1beta1
        kind: IAMRole
        metadata:
          labels:
            role: crossplane
      patches:
        - type: FromCompositeFieldPath
          toFieldPath: spec.forProvider.assumeRolePolicyDocument
          # The oidc-arn annotation comes from the newly created OpenIDConnectProvider's 
          # metadata.annotations[crossplane.io/external-name]
          fromFieldPath: metadata.annotations[example.com/oidc-arn]
          transforms:
            - type: string
              string:
                fmt: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Effect": "Allow",
                        "Principal": {
                          "Federated": "%s"
                        },
                        "Action": "sts:AssumeRoleWithWebIdentity",
                        "Condition": {
                          "StringLike": {
                            "%s:sub": "system:serviceaccount:crossplane-system:provider-aws-*"
                          }
                        }
                      }
                    ]
                  }
```
The problem we are facing is that `"%s:sub": "system:serviceaccount:crossplane-system:provider-aws-*"` expect the `OIDC_PROVIDER` which is the OpenIDConnectProvider's `spec.forProvider.url` value with a stripped prefix of `https://`

### How could Crossplane help solve your problem?

We suggest that the OpenIDConnectProvider is enhanced to provide the ResourceID / Name in its `status.atProvider` object. By adding that there is a way to reference the OIDC provider by its external name.

#### Suggested solution

1. Add a string representation of the OpenIDConnectProviders name at https://github.com/crossplane/provider-aws/blob/master/apis/identity/v1alpha1/openidconnectprovider_types.go#L83-87

```go
...
type OpenIDConnectProviderObservation struct {
	
        // The IAM OIDC provider resource identifier.
	ResourceID string `json:"resourceId,omitempty"`
        ...

```

Populate the value in https://github.com/crossplane/provider-aws/blob/master/pkg/clients/iam/openidconnectprovider.go#L48-L55

```go
...
o.ResourceID = strings.TrimPrefix(*observed.Url, "https://")
...
```
