### ISSUE TITLE
CloudFront Distribution Custom Origin Reconciling Loop

### ISSUE THREAD

**Issue by gstramandinoli** [crossplane/provider-aws#894]
### What happened?

Deploying a cloudfront distribution with a custom origin causes the provider-aws to enter an infinite loop of 

```
2021-10-27T21:22:52.190Z	DEBUG	provider-aws	Successfully requested update of external resource	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution", "uid": "65ef1e28-17dd-48db-a8ae-643fd09f64b2", "version": "53118503", "external-name": "E36PA3AGLMFTIU", "requeue-after": "2021-10-27T21:23:52.190Z"}
2021-10-27T21:22:52.190Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Distribution","name":"broadcast-754467cb5b-s999r-distribution","uid":"65ef1e28-17dd-48db-a8ae-643fd09f64b2","apiVersion":"cloudfront.aws.crossplane.io/v1alpha1","resourceVersion":"53118503"}, "reason": "UpdatedExternalResource", "message": "Successfully requested update of external resource"}
2021-10-27T21:22:52.207Z	DEBUG	provider-aws	Reconciling	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution"}
2021-10-27T21:22:52.792Z	DEBUG	provider-aws	Successfully requested update of external resource	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution", "uid": "65ef1e28-17dd-48db-a8ae-643fd09f64b2", "version": "53118503", "external-name": "E36PA3AGLMFTIU", "requeue-after": "2021-10-27T21:23:52.792Z"}
2021-10-27T21:22:52.792Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Distribution","name":"broadcast-754467cb5b-s999r-distribution","uid":"65ef1e28-17dd-48db-a8ae-643fd09f64b2","apiVersion":"cloudfront.aws.crossplane.io/v1alpha1","resourceVersion":"53118503"}, "reason": "UpdatedExternalResource", "message": "Successfully requested update of external resource"}
2021-10-27T21:22:52.804Z	ERROR	controller-runtime.manager.controller.managed/distribution.cloudfront.aws.crossplane.io	Reconciler error	{"reconciler group": "cloudfront.aws.crossplane.io", "reconciler kind": "Distribution", "name": "broadcast-754467cb5b-s999r-distribution", "namespace": "", "error": "cannot update managed resource status: Operation cannot be fulfilled on distributions.cloudfront.aws.crossplane.io \"broadcast-754467cb5b-s999r-distribution\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214
2021-10-27T21:22:52.804Z	DEBUG	provider-aws	Reconciling	{"controller": "managed/distribution.cloudfront.aws.crossplane.io", "request": "/broadcast-754467cb5b-s999r-distribution"}
```

### How can we reproduce it?

Deploy a distribution with a custom origin

```
# Distribution will not be deleted unless you mark the distribution disabled via
# spec.distributionConfig.enabled.
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: example2-distribution
spec:
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution
      origins:
        items:
          - domainName: exampledomain.example.com
            id: example
            originPath: "/helloworld"
            customHeaders:
              items:
                - headerName: "test"
                  headerValue: "test"
              quantity: 1
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "http-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1
                quantity: 1
      defaultCacheBehavior:
        targetOriginID: example
        viewerProtocolPolicy: allow-all
        minTTL: 0
        forwardedValues:
          cookies:
            forward: none
          queryString: false
  providerConfigRef:
    name: aws-provider
```

### What environment did it happen in?
Crossplane version: crossplane-1.4.1

**Comment by gstramandinoli** [comment]
After digging into this more, It seems like the issue is occurring somewhere in https://github.com/crossplane/provider-aws/blob/master/pkg/controller/cloudfront/lateinit.go#L384 

The customOriginConfig passed in variables actual and desired both have the same values: 
 
```
        CustomOriginConfig: {
          HTTPPort: 1935,
          HTTPSPort: 443,
          OriginKeepaliveTimeout: 5,
          OriginProtocolPolicy: "http-only",
          OriginReadTimeout: 10,
          OriginSslProtocols: {
            Items: ["TLSv1"],
            Quantity: 1
          }
        },
```

However, actualConfig is modified by the method and the customOriginConfig becomes:

```
        "customOriginConfig": {
          "httpPort": 1935,
          "httpSPort": 443,
          "originKeepaliveTimeout": 5,
          "originProtocolPolicy": "http-only",
          "originReadTimeout": 10
        },
```

which is incorrect because its missing the OriginSSLProtocols which is causing the infinite loop. 

I am still digging into this.

**Comment by stevendborrelli** [comment]
@gstramandinoli thank you for your amazing work on this issue!

Do you think you could test PR #922? It tries to fix the issue in the lateInitialization code.

**Comment by jbw976** [comment]
We should consider reopening this issue as some folks are saying they are seeing similar behavior where the reconciliation loop continues endlessly.  I've heard from 2 users that they are both using `aliases` and `viewerCertificate` and running into this similar issue where it endlessly reconciles.  Example:

https://github.com/crossplane/crossplane/discussions/2702

**Comment by stevendborrelli** [comment]
@jbw976 I'm taking a look at it.

**Comment by negz** [comment]
It seems like the issue with `viewerCertificate` is that the CloudFront API (or SDK?) always indicates that `CloudFrontDefaultCertificate` is nil in `GetDistributionOutput`. Below is the diff between the 'actual' state reported by CloudFront and the 'desired' state Crossplane has:

```diff
  &v1alpha1.DistributionConfig{                                                                                                                                                            ... // 12 identical fields                                                                                                                                                 
        PriceClass:   &"PriceClass_All",                                                                                                                                                   Restrictions: &{GeoRestriction: &{Quantity: &0, RestrictionType: &"none"}},                                                                                                
        ViewerCertificate: &v1alpha1.ViewerCertificate{                                                                                                                                            ACMCertificateARN:            &"arn:aws:acm:us-east-1:609897127049:certificate/54fecaf8-299a-401"...,                                                              
                Certificate:                  &"arn:aws:acm:us-east-1:609897127049:certificate/54fecaf8-299a-401"...,                                                                              CertificateSource:            &"acm",                                                                                                                              
-               CloudFrontDefaultCertificate: nil,                                                                                                                                 
+               CloudFrontDefaultCertificate: &false,
                IAMCertificateID:             nil,
                MinimumProtocolVersion:       &"TLSv1.1_2016",
                SSLSupportMethod:             &"sni-only",
        },
        WebACLID: &"",
  }
```

This diff is causing Crossplane to think the distribution needs updating. Normally we'd just tell `cmp` to ignore the `CloudFrontDefaultCertificate` field for IsUpToDate purposes, but all CloudFront resources appear to share a generic reflection based IsUpToDate implementation that makes this tricky to address without a little refactoring.

**Comment by wilhelmi** [comment]
Still seeing this hanging on version 0.22 with an ACM viewer cert, can we reopen?

**Comment by stevendborrelli** [comment]
Yes, I'll reopen the issue.

**Comment by stevendborrelli** [comment]
@wilhelmi can you provide more information on the issue? Perhaps a sample YAML you are seeing with the issue and event logs from the controller?

**Comment by wilhelmi** [comment]
Here is an example to reproduce the problem. I will note that it looks like it does reach ready/deployed but an update look is triggered.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtests.demo.com
spec:
  group: demo.com
  names:
    kind: XTest
    plural: xtests
  claimNames:
    kind: Test
    plural: tests
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  environment:
                    type: string
                  fqdn:
                    type: string
                required:
                  - environment
            required:
              - parameters
          status:
            type: object
            properties:
              certArn:
                type: string
              cloudFront:
                type: object
                properties:
                  domain:
                    type: string
                  originAccessIdentity:
                    type: string
              resourceRecord:
                type: object
                properties:
                  name:
                    type: string
                  value: 
                    type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test.aws.demo.com
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: demo.com/v1
    kind: XTest
  resources:
    - name: site-bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: ""
        spec:
          forProvider:
            locationConstraint: us-east-1
            acl: private
      patches:
        - fromFieldPath: spec.parameters.fqdn
          toFieldPath: spec.forProvider.metadata.nane
    - name: site-certificate
      base:
        apiVersion: acm.aws.crossplane.io/v1beta1
        kind: Certificate
        metadata:
          name: test-acm-cert
        spec:
          forProvider:
            region: us-east-1
            domainName: ""
            validationMethod: DNS
            tags:
              - key: test
                value: cert
      patches:
        - fromFieldPath: spec.parameters.fqdn
          toFieldPath: spec.forProvider.domainName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.resourceRecord.name
          toFieldPath: status.resourceRecord.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.resourceRecord.value
          toFieldPath: status.resourceRecord.value
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.certificateARN
          toFieldPath: status.certArn
    - name: dns-validation-record
      base:
        apiVersion: route53.aws.crossplane.io/v1alpha1
        kind: ResourceRecordSet
        spec:
          providerConfigRef:
            name: aws-dns
          forProvider:
            zoneId: Z0680263Q9Z1ZTQRCPUP
            type: CNAME
            ttl: 300
      patches:
        - fromFieldPath: spec.parameters.zone
          toFieldPath: spec.forProvider.zoneIdRef.name
        - fromFieldPath: status.resourceRecord.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: status.resourceRecord.value
          toFieldPath: spec.forProvider.resourceRecords[0].value
    # CloudFront Distribution to serve content
    - name: cloudfront-oai
      base:
        apiVersion: cloudfront.aws.crossplane.io/v1alpha1
        kind: CloudFrontOriginAccessIdentity
        spec:
          forProvider:
            region: us-east-1
            cloudFrontOriginAccessIdentityConfig:
              comment: Testing
      patches:
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.cloudFrontOriginAccessIdentity.id
          toFieldPath: status.cloudFront.originAccessIdentity
    - name: cloudfront
      base:
        apiVersion: cloudfront.aws.crossplane.io/v1alpha1
        kind: Distribution
        spec:
          forProvider:
            region: us-east-1
            distributionConfig:
              enabled: true
              isIPV6Enabled: true
              defaultRootObject: index.html
              comment: ""
              priceClass: PriceClass_100
              aliases:
                quantity: 1
                items:
                  - ""
              viewerCertificate:
                sslSupportMethod: sni-only
                minimumProtocolVersion: TLSv1.2_2021
                cloudFrontDefaultCertificate: false
                aCMCertificateARN: ""
              origins:
                items:
                  - domainName: ""
                    id: s3Origin
                    s3OriginConfig:
                      originAccessIDentity: ""
              defaultCacheBehavior:
                targetOriginID: s3Origin
                viewerProtocolPolicy: redirect-to-https
                compress: true
                allowedMethods:
                  items: ["GET", "HEAD"]
                  quantity: 2
                  cachedMethods:
                    items: ["GET", "HEAD"]
                    quantity: 2
                cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
              restrictions:
                geoRestriction:
                  restrictionType: none
                  items: []
                  quantity: 0
      patches:
        - fromFieldPath: spec.parameters.fqdn
          toFieldPath: spec.forProvider.distributionConfig.aliases.items[0]
        - fromFieldPath: status.certArn
          toFieldPath: spec.forProvider.distributionConfig.viewerCertificate.aCMCertificateARN
        - fromFieldPath: status.cloudFront.originAccessIdentity
          toFieldPath: spec.forProvider.distributionConfig.origins.items[0].s3OriginConfig.originAccessIdentity
          transforms:
          - type: string
            string:
              fmt: "origin-access-identity/cloudfront/%s"
        - fromFieldPath: spec.parameters.fqdn
          toFieldPath: spec.forProvider.distributionConfig.origins.items[0].domainName
          transforms:
          - type: string
            string:
              fmt: "%s.s3.us-east-1.amazonaws.com"
```

**Comment by wilhelmi** [comment]
@stevendborrelli Is there anything more I can provide on this?

**Comment by jbw976** [comment]
@ezgidemirel was this issue also taken care of along with issue #1108 in PR #1186?

**Comment by wilhelmi** [comment]
@ezgidemirel I am not seeing the reconciliation loops anymore. I ran it with Crossplane 1.6.4 and 0.25 of the provider and I think this resolved the issue I was seeing.

Regarding the syntax errors, the one issue I hit is the following:

```yaml
...
              defaultCacheBehavior:
                targetOriginID: s3Origin
                viewerProtocolPolicy: redirect-to-https
                compress: true
                allowedMethods:
                  items: ["GET", "HEAD"]
                  quantity: 2
                  cachedMethods:
                    items: ["GET", "HEAD"]
                    quantity: 2
                cachePolicyID: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
              restrictions:
                geoRestriction:
                  restrictionType: none
                  items: []
```

Failed with following error:

```
reate failed: cannot create Distribution in AWS: InvalidParameter: 1
        validation error(s) found.

        - missing required field,
        CreateDistributionInput.DistributionConfig.Restrictions.GeoRestriction.Quantity.
```

Which seems to match the CRD definition here: https://doc.crds.dev/github.com/crossplane/provider-aws/cloudfront.aws.crossplane.io/Distribution/v1alpha1@v0.25.0

Changing it to:

```yaml
              restrictions:
                geoRestriction:
                  restrictionType: none
                  items: []
                  quantity: 0
```

Yields the same error, any idea what I am missing here?
