### ISSUE TITLE
S3 bucket would not reach Available condition when set notificationConfiguration

### ISSUE THREAD

**Issue by haarchri** [crossplane/provider-aws#896]
### What happened?

I created an `buckets.s3.aws.crossplane.io` object  but the CR never reached available condition and the controller was constantly updating the bucket.

```
kubectl get bucket
NAME                         READY   SYNCED   AGE
255932642927-lambda-bucket   False   True     17m
```

```
  Normal   CreatedExternalResource          7m27s                  managed/bucket.s3.aws.crossplane.io  Successfully requested creation of external resource
  Normal   UpdatedExternalResource          5m14s (x4 over 7m26s)  managed/bucket.s3.aws.crossplane.io  Successfully requested update of external resource
  Normal   UpdatedExternalResource          74s (x4 over 4m18s)    managed/bucket.s3.aws.crossplane.io  Successfully requested update of external resource
  Normal   UpdatedExternalResource          21s                    managed/bucket.s3.aws.crossplane.io  Successfully requested update of external resource
  Normal   UpdatedExternalResource          5s (x9 over 7m20s)     managed/bucket.s3.aws.crossplane.io  Successfully requested update of external resource
```

### How can we reproduce it?
Create an s3 bucket
Create an buckets.s3.aws.crossplane.io object to adopt the s3 bucket, example:
* full example available here: https://gist.github.com/haarchri/95f72bd6279f42b821082b74d2b149d1
```
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: 255932642927-lambda-bucket
spec:
  forProvider:
    acl: private
    locationConstraint: eu-central-1
    accelerateConfiguration:
      status: Enabled
    versioningConfiguration:
      status: Enabled
    notificationConfiguration:
      lambdaFunctionConfigurations:
        - events: ["s3:ObjectCreated:*"]
          lambdaFunctionArn: arn:aws:lambda:eu-central-1:255932642927:function:lambda
    paymentConfiguration:
      payer: BucketOwner
    tagging:
      tagSet:
        - key: s3-bucket
          value: lambda-bucket
    objectLockEnabledForBucket: false
  providerConfigRef:
    name: default
```

every run the name-id is changed in aws
via debug we can see the following:

```
        NewVersioningConfigurationClient(client),  #### no update needed
        NewAccelerateConfigurationClient(client), #### no update needed
        NewCORSConfigurationClient(client), #### no update needed
        NewLifecycleConfigurationClient(client), #### no update needed
        NewLoggingConfigurationClient(client), #### no update needed

        NewNotificationConfigurationClient(client), #### update needed

####### needsupdate config:  &{[{[s3:ObjectCreated:*] <nil> <nil> arn:aws:lambda:eu-central-1:255932642927:function:lambda}] [] []}
####### needsupdate external:  [{[s3:ObjectCreated:*] 0xc0017c15c0 <nil> 0xc0017c15b0 {}}]


        NewReplicationConfigurationClient(client), #### no update needed
        NewRequestPaymentConfigurationClient(client), #### no update needed
        NewSSEConfigurationClient(client), #### no update needed
        NewTaggingConfigurationClient(client), #### no update needed
        NewWebsiteConfigurationClient(client), #### no update needed
        NewPublicAccessBlockClient(client), #### no update needed
```

first run: 
![image](https://user-images.githubusercontent.com/21083497/139339500-f32eee3b-af48-4212-b2ba-36e6a5c6b1f9.png)

next run:
![image](https://user-images.githubusercontent.com/21083497/139339555-71264691-d8e5-4e65-8f60-0da21a651a72.png)

after every update call the resource for event notification is changed - you can see this at the name field
![image](https://user-images.githubusercontent.com/21083497/139339619-d4f5e4aa-7807-474b-af77-557ee32c0a27.png)

* provider-aws 0.20.0
