### ISSUE TITLE
ReplicationGroup is modifying everytime when used in composition

### ISSUE THREAD

**Issue by eloo** [crossplane/provider-aws#909]
### What happened?
Hi,
we recently have updated our provider-aws and crossplane itself and we are now facing issues with our ReplicationGroups.

This means, now when we create a new claim of our composition the ReplicationGroup will be created in state "Creating" and then switch after a couple of time to "Modifying" and then to "Available". But after a few minutes its going back to "Modifying" then again "Available" and again "Modifying".. And then its stuck in this loop. 

This makes the Claim never come be ready and so its not usable. Related to https://github.com/crossplane/provider-aws/issues/622 

Further this seems NOT to happen when the ReplicationGroup is created using a MR directly. It seems to be only present when used within a Composition. 

The version when we have noticed it was the following:

crossplane 1.4.1 -> crossplane 1.5.0
provider-aws:v0.20.0-rc.0.94.g0ffd2429 -> crossplane/provider-aws:v0.20.0

Currently i'm not sure if this caused by the provider or crossplane itself. But currently we only see this for the ReplicationGroup and not our other resources.

### How can we reproduce it?

Composition: 
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: redis-composition-test
  labels:
    provider: aws
    crossplane.io/xrd: xredisinstancestest.test.cloud.test
spec:
  compositeTypeRef:
    apiVersion: test.cloud.test/v1
    kind: XRedisInstancetest
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - base: 
        apiVersion: cache.aws.crossplane.io/v1beta1
        kind: ReplicationGroup
        metadata:
          name: METADATA_UID
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: aws-provider-config
          forProvider:
            replicationGroupDescription: GROUP_DESCRIPTION
            applyModificationsImmediately: true
            region: eu-central-1
            engine: redis
            engineVersion: 6.x
            atRestEncryptionEnabled: true
            cacheNodeType: cache.t3.micro
            securityGroupIds: 
              - <securityGroupId of the vpc>
            transitEncryptionEnabled: true

            cacheSubnetGroupName: <subnetGroupName>

            numCacheClusters: 1
          writeConnectionSecretToRef:
            name: METADATA_NAME-MR-redis-managed-resource
            namespace: crossplane-system
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-redis-managed-resource"
      connectionDetails:
        - fromConnectionSecretKey: endpoint
          name: REDIS_ENDPOINT
        - fromConnectionSecretKey: port
          name: REDIS_PORT
        - fromConnectionSecretKey: password
          name: REDIS_TOKEN
        - fromFieldPath: metadata.name
          name: REDIS_CLUSTER_NAME

```

Definition: 
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xredisinstancestest.test.cloud.test
spec:
  group: test.cloud.test
  names:
    kind: XRedisInstancetest
    plural: xredisinstancestest
  claimNames:
    kind: RedisInstancetest
    plural: redisinstancestest
  defaultCompositionRef: 
    name: redis-composition-test
  connectionSecretKeys:
  - REDIS_ENDPOINT
  - REDIS_PORT
  - REDIS_TOKEN
  - REDIS_CLUSTER_NAME
  versions:
  - name: v1
    served: true
    referenceable: true
```

Claim:
```
apiVersion: test.cloud.test/v1
kind: RedisInstancetest
metadata:
  name: redis-instance-test
spec: 
  writeConnectionSecretToRef:
    name: redis-instance-test-access  
```

### What environment did it happen in?
Crossplane version: crossplane 1.5.0
crossplane/provider-aws:v0.20.0

Thanks
