### ISSUE TITLE
Crossplane aws CRD is using node instance role instead of the aws providerconfig

### ISSUE THREAD

**Issue by jiezhang0917** [crossplane/provider-aws#928]
### What happened?
I have created an iam role with aws session token built secret. Now that token is expired so I've created a new one and built new secret and provider config. But after replace the provider config ref in the iam role manifest, it still failed to sync with event messages complaning the node instance role does not have permission to perform `iam:GetPolicy`. So seems like the provider config is not being used. Instead, it's using node instance role.

### How can we reproduce it?
1.  build secret and provider config with a sts assumed session info.
2. create a CRD for example iamrole
3. wait for the token to be expired
4. create new secret and provider config with newly assumed sts session info
5. check the events on the CRD you created

### What environment did it happen in?
Crossplane version: 1.5.0
Cloud provider: aws
kubectl version: Client Version: v1.22.2
kubernetes destribution: EKS
OS: Macos Big Sur

**Comment by hasheddan** [comment]
@jiezhang0917 would you mind sharing your manifests so we can ensure everything is configured as expected?

**Comment by jiezhang0917** [comment]
Hi @hasheddan, I'ved created this `creds.conf` file in order to create secret:
```[default]
aws_access_key_id = xxx
aws_secret_access_key = xxx
aws_session_token = xxx
```
Then I run`k create secret generic aws-creds -n crossplane-system --from-file=./creds.conf`

And this is the manifest of provider config:
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
```
