### ISSUE TITLE
Make it possible, to "customize" the output of IAMAccessKey

### ISSUE THREAD

**Issue by janosmiko** [crossplane/provider-aws#943]
I'd like to store AWS IAM Access Key ID and Secret Access Key in a secret in a specific form. I saw it's automatically done by crossplane. However, the secret contains these two fields: `user`, `password`.
Another K8s resource requires these values in a specific form `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`.

Is it possible somehow to update this secret or to create a new one which contains exactly the same resources, but with these new field names?

Example code:
``` yaml
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMAccessKey
metadata:
  name: iam-key-name
spec:
  forProvider:
    userNameRef:
      name: iam-user
  providerConfigRef:
    name: aws-config
  writeConnectionSecretToRef:
    name: secret-name
    namespace: random-namespace
```

Example output:
``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-name
  namespace: random-namespace
data:
  password: ASD_QWE_IN_BASE64
  username: AKIA_12345_IN_BASE64
type: connection.crossplane.io/v1alpha1
```

What I'd like to have:
``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-name or other-secret-name
  namespace: random-namespace
data:
  SECRET_ACCESS_KEY: ASD_QWE_IN_BASE64
  ACCESS_KEY_ID: AKIA_12345_IN_BASE64
type: Opaque
```

**Comment by chlunde** [comment]
@janosmiko you can do this (and much more!) with crossplane compositions:

```
    connectionDetails:
    - name: SECRET_ACCESS_KEY
      fromConnectionSecretKey: password
...
```

https://crossplane.io/docs/v1.5/concepts/composition.html
https://crossplane.io/docs/v1.5/reference/composition.html
