### ISSUE TITLE
PublicDNSNamespace resources are not removed from AWS even with the correct deletionPolicy

### ISSUE THREAD

**Issue by avnes** [crossplane/provider-aws#944]
### What happened?

- I was trying the PublicDNSNamespace resource in the AWS provider, and even though I use "deletionPolicy: Delete" I noticed that the resource was not removed from AWS when doing "kubectl delete -f dns.yaml".

### How can we reproduce it?

I have this manifest called dns.yaml:

```yaml
---
apiVersion: servicediscovery.aws.crossplane.io/v1alpha1
kind: PublicDNSNamespace
metadata:
  name: dns-aunes-leda-1
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-west-3
    name: aunes-leda-1.dfds.cloud
    tags:
      - key: perftest
        value: perftest
  providerConfigRef:
    name: aws-provider-config-aunes
  writeConnectionSecretToRef:
    namespace: perftest
    name: secret-dns-aunes-leda-1
```

1. kubectl apply -f dns.yaml
2. Observe that dns-aunes-leda-1 is created as PublicDNSNamespace in Kubernetes.
3. Observe that aunes-leda-1.dfds.cloud is created in Cloud Map and Route 53 on AWS
4. kubectl delete -f dns.yaml
5. Observe that dns-aunes-leda-1 is deleted as PublicDNSNamespace in Kubernetes.
6. Observe that it is not removed in Cloud Map and Route 53 on AWS. (I have actualy waited up to 16 hours, and the resource is still there on AWS).

### What environment did it happen in?
Crossplane version: 

Crossplane version (installed through Helm): 1.5.0
Crossplane CLI version: v1.5.0
aws-provider version: v0.20.1
Kubernetes version: v1.22.3
Kubernetes distribution: minikube v1.24.0
OS: Darwin 12.0.1 (macOS)
