### ISSUE TITLE
DynamoDB Table Reconciliation Failure

### ISSUE THREAD

**Issue by jbhennin** [crossplane/provider-aws#946]
### What happened?

Received a reconciliation error when created a table with billingMode  PROVISIONED

```
update failed: cannot update Table in AWS: ValidationException: One or more parameter values were invalid: ProvisionedThroughput must be specified when BillingMode is PROVISIONED
status code: 400, request id: 604LFC8D4PLP4MGASL844S7VA3VV4KQNSO5AEMVJF66Q9ASUAAJG
```

### How can we reproduce it?
Create a table using the following yaml.
```yaml
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: jillian-test-table
  namespace: warrior
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    attributeDefinitions:
      - attributeName: "userId"
        attributeType: "S"
    provisionedThroughput:
      readCapacityUnits: 5
      writeCapacityUnits: 5
    keySchema:
      - attributeName: "userId"
        keyType: HASH
    region: us-west-2
    billingMode: PROVISIONED
```

### What environment did it happen in?
Crossplane version: 1.3
AWS Provider: 0.20.3

**Comment by haarchri** [comment]
at the moment you can get it working not set `billingMode: PROVISIONED` when `provisionedThroughput` is set
we need to investigate why this happened

**Comment by RafalMaleska** [comment]
tested with: 

```
kind: Table
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
metadata:
  name: cnp-example
spec:
  deletionPolicy: Delete
  forProvider:
    attributeDefinitions:
    - attributeName: attribute1
      attributeType: S
    globalSecondaryIndexes:
    - indexName: some-name
      keySchema:
      - attributeName: attribute1
        keyType: HASH
      projection:
        nonKeyAttributes:
        - SomeId
        projectionType: INCLUDE
      provisionedThroughput:
        readCapacityUnits: 1
        writeCapacityUnits: 1
    keySchema:
    - attributeName: attribute1
      keyType: HASH
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    region: eu-central-1
    sseSpecification:
      enabled: true
      kmsMasterKeyID: arn:aws:kms:eu-central-1:1234567890:key/7a423d0b-1c47-47d4-a0ae-3592258a0445
      sseType: KMS
    tags:
    - key: CostReference
      value: F-330951-51-05
    - key: crossplane-kind
      value: table.dynamodb.aws.crossplane.io
    - key: crossplane-name
      value: cnp-example
    - key: crossplane-providerconfig
      value: iat-1234567890
  providerConfigRef:
    name: iat-1234567890
  writeConnectionSecretToRef:
    name: dynamodb-cnp-example
    namespace: crossplane-system
```

the workaround seams to work for managed resources 
it's blocking the usage in a composition where users need to set one of the values
