### ISSUE TITLE
DynamoDB SYNC=FALSE when spec.forProvider.streamSpecification.streamEnabled=false

### ISSUE THREAD

**Issue by RafalMaleska** [crossplane/provider-aws#953]
### What happened?

After creation of DynamoDB with: 

`spec.forProvider.streamSpecification.streamEnabled=false`

MR becomes out of sync:

```yaml
  - lastTransitionTime: "2021-11-17T11:01:45Z"
    message: "update failed: cannot update Table in AWS: ValidationException: Table
      has no stream to disable: TableName: cnp-example\n\tstatus code:
      400, request id: 0A8G1RPI2BN6HIEBUJEIHBUV3VVV4KQNSO5AEMVAA229ASUAAJG"
    reason: ReconcileError
    status: "False"
    type: Synced
```

### How can we reproduce it?

After creation of DynamoDB with: 

```yaml
kind: Table
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
metadata:
  name: cnp-example
spec:
  deletionPolicy: Delete
  forProvider:
    attributeDefinitions:
    - attributeName: attribute1
      attributeType: S
    billingMode: PROVISIONED
    globalSecondaryIndexes:
    - indexName: some-name
      keySchema:
      - attributeName: attribute1
        keyType: HASH
      projection:
        nonKeyAttributes:
        - SomeId
        projectionType: INCLUDE
      provisionedThroughput:
        readCapacityUnits: 1
        writeCapacityUnits: 1
    keySchema:
    - attributeName: attribute1
      keyType: HASH
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    region: eu-central-1
    sseSpecification:
      enabled: true
      kmsMasterKeyID: arn:aws:kms:eu-central-1:123456789:key/7a423d0b-1c47-47d4-a0ae-3592258a0445
      sseType: KMS
    streamSpecification:
      streamEnabled: false
    tags:
    - key: CostReference
      value: F-330951-51-05
    - key: crossplane-kind
      value: table.dynamodb.aws.crossplane.io
    - key: crossplane-name
      value: cnp-example
    - key: crossplane-providerconfig
      value: iat-123456789
  providerConfigRef:
    name: iat-123456789
  writeConnectionSecretToRef:
    name: dynamodb-cnp-example
    namespace: crossplane-system
```

got resource out of sync:

```yaml
  - lastTransitionTime: "2021-11-17T11:01:45Z"
    message: "update failed: cannot update Table in AWS: ValidationException: Table
      has no stream to disable: TableName: cnp-example\n\tstatus code:
      400, request id: 0A8G1RPI2BN6HIEBUJEIHBUV3VVV4KQNSO5AEMVAA229ASUAAJG"
    reason: ReconcileError
    status: "False"
    type: Synced
```

this happens because: spec.forProvider.streamSpecification.streamEnabled=false

### What environment did it happen in?
* Crossplane version: 1.5.0
* Kubernetes version: 1.21.2
* Kubernetes distribution: EKS
* provider-aws: v0.20.3

**Comment by haarchri** [comment]
my guess looks very similiar to https://github.com/crossplane/provider-aws/issues/946 if we want to update field which are defaults
@RafalMaleska  what happen if you not set 
```
    streamSpecification:
      streamEnabled: false
```

**Comment by RafalMaleska** [comment]
https://github.com/crossplane/provider-aws/issues/946 is about billingMode, this one is about streamSpecification. 

when i don't specify streamSpecification I'm running into: https://github.com/crossplane/provider-aws/issues/946

i would like to make streamSpecification available over a composition/claim therefore it has to be either streamEnabled=true or streamEnabled=false (using mapping in the composition)

**Comment by RafalMaleska** [comment]
the other observation is that the MR is stuck in deletion: 

```
  conditions:
  - lastTransitionTime: "2021-11-17T16:30:45Z"
    reason: Deleting
    status: "False"
    type: Ready
  - lastTransitionTime: "2021-11-17T16:30:45Z"
    message: 'delete failed: failed to delete Table: ResourceInUseException: Attempt
      to change a resource which is still in use: Table is being deleted: cnp-example-b9dnz'
    reason: ReconcileError
    status: "False"
    type: Synced
```

the resources in aws are deleted 

workaround: remove finalizers
