### ISSUE TITLE
Expose CAData in EKS CRD

### ISSUE THREAD

**Issue by hanlins** [crossplane/provider-aws#955]
### What problem are you facing?

This is the current `EKS` object status:
```golang
// ClusterObservation is the observed state of a cluster.
type ClusterObservation struct {
	// The Amazon Resource Name (ARN) of the cluster.
	Arn string `json:"arn,omitempty"`

	// The Unix epoch timestamp in seconds for when the cluster was created.
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`

	// The endpoint for your Kubernetes API server.
	Endpoint string `json:"endpoint,omitempty"`

	// The identity provider information for the cluster.
	Identity Identity `json:"identity,omitempty"`

	// The platform version of your Amazon EKS cluster. For more information, see
	// Platform Versions (https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html)
	// in the Amazon EKS User Guide .
	PlatformVersion string `json:"platformVersion,omitempty"`

	// The VPC configuration used by the cluster control plane. Amazon EKS VPC resources
	// have specific requirements to work properly with Kubernetes. For more information,
	// see Cluster VPC Considerations (https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html)
	// and Cluster Security Group Considerations (https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html)
	// in the Amazon EKS User Guide.
	ResourcesVpcConfig VpcConfigResponse `json:"resourcesVpcConfig,omitempty"`

	// The current status of the cluster.
	Status ClusterStatusType `json:"status,omitempty"`
}
```
We've generated the bearer token and we want to generate a k8s client based on the observed states in `EKS` object. Currently, `CAData` is missing, and we have to issue a dedicate request to AWS to retrieve the CA data, which is not ideal.

### How could Crossplane help solve your problem?

It would be ideal if `EKS` object can expose a field `CAData` in the struct above https://github.com/crossplane/provider-aws/blob/2fdde09cccaf56a8b0e770d92318d46989704a7b/apis/eks/v1beta1/types.go#L231-L259
, and it can be done by simply exposing the CA data from EKS `DescribeCluster` results https://github.com/crossplane/provider-aws/blob/2fdde09cccaf56a8b0e770d92318d46989704a7b/pkg/clients/eks/eks.go#L218-L223

**Comment by negz** [comment]
@hanlins I believe this CA data is included in the connection secret if you specify `writeConnectionSecretTo` (probably encoded in a kubecfg file). Would that work as an alternative, rather than adding this as a status field?

**Comment by hanlins** [comment]
Hey @negz, thanks for the response! I doubt if there's code persisting EKS CA data into the secret, this is what I found:
```
➜  provider-aws git:(topic/955/expose-eks-cadata) ag -g '!apis' -g '!package' -s WriteConnectionSecretToReference
pkg/controller/rds/dbcluster/setup.go
86:	pw, _, err := rds.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.MasterUserPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
107:	pw, _, err := rds.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.MasterUserPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)

pkg/controller/rds/dbinstance/setup.go
90:	pw, _, err := rds.GetPassword(ctx, e.kube, cr.Spec.ForProvider.MasterUserPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
127:	pw, _, err := rds.GetPassword(ctx, e.kube, cr.Spec.ForProvider.MasterUserPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
149:	pw, pwchanged, err := rds.GetPassword(ctx, e.kube, cr.Spec.ForProvider.MasterUserPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
288:	_, pwChanged, err := rds.GetPassword(ctx, e.kube, cr.Spec.ForProvider.MasterUserPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)

pkg/controller/database/rdsinstance.go
161:	pw, _, err := rds.GetPassword(ctx, e.kube, cr.Spec.ForProvider.MasterPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
210:	pwd, changed, err := rds.GetPassword(ctx, e.kube, cr.Spec.ForProvider.MasterPasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)

pkg/controller/mq/broker/setup.go
84:	pw, _, err := mq.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.CustomUsers[0].PasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
109:	pw, _, err := mq.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.CustomUsers[0].PasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)

pkg/controller/mq/user/setup.go
92:	pw, _, err := mq.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.PasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
124:	pw, _, err := mq.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.PasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
146:	pw, pwchanged, err := mq.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.PasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
161:	pw, _, err := mq.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.PasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)
178:	_, pwChanged, err := mq.GetPassword(ctx, e.kube, &cr.Spec.ForProvider.PasswordSecretRef, cr.Spec.WriteConnectionSecretToReference)

pkg/clients/rds/rds.go
447:	_, pwdChanged, err := GetPassword(ctx, kube, r.Spec.ForProvider.MasterPasswordSecretRef, r.Spec.WriteConnectionSecretToReference)

pkg/clients/rds/rds_test.go
241:							WriteConnectionSecretToReference: &xpv1.SecretReference{
291:							WriteConnectionSecretToReference: &xpv1.SecretReference{
```
Also, seems the secret is used for persisting credentials (_e.g._ passwords), I'm not sure if CACert is something we should dump into secrets? It would be straightforward if it can be part of the `Cluster` status cuz it's the `aws eks describe-cluster` command output.

**Comment by hanlins** [comment]
@negz I see. Came across a [demo](https://github.com/Piotr1215/crossplane-demo#deploy-eks-cluster) and it seems the kubeconfig is persisted in the secret you mentioned above. Technically yes, we can retrieve the CA data there in the secret, but it's not ideal for our use case. In my team's use case, we don't use the kubeconfig from EKS directly, and instead, we construct our own kubeconfig file using a bearer token (EKS's kubeconfig is using [credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) that has a dependency on `aws` binary, we don't want that). It would be nice to access the CA data directly from the `Cluster` object status rather than reference the secret, and then parse the whole kubeconfig just to extract the CAData.

I think it's reasonable to expose the CA data in `Cluster` status since 1). it's endpoint's property and it's not really a credential, 2). it's part of `aws eks describe-cluster`'s response so it's natural to reflect it in the `Cluster` CRD. Let me know your concerns for this change :D

**Comment by janwillies** [comment]
While technically the CA data is encoded in the kubeconfig in `writeConnectionSecretTo`, it's not possible to extract it from crossplane for further use.

Our usecase is to write a Kubernetes `secret` for ArgoCD:
```yaml
    - name: argocd-cluster
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          # deletionPolicy: Orphan
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                name: # patched
                namespace: argocd
                labels:
                  argocd.argoproj.io/secret-type: cluster
              type: Opaque
              stringData:
                config: # patched
                name: # patched
                server: # patched
      patches:
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: | 
                { 
                  "awsAuthConfig": {
                    "clusterName": "%s",
                    "roleARN": "arn:aws:iam::111122223333:role/%s"
                  },
                  "tlsClientConfig": {
                    "insecure": false,
                    "caData": "<base64 encoded certificate>"
                  }
                }
          toFieldPath: spec.forProvider.manifest.stringData.config
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "https://%s.%s.svc"
          toFieldPath: spec.forProvider.manifest.stringData.server
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.manifest.stringData.name
```
