### ISSUE TITLE
matchLabels unable to match vpc in hostedzone

### ISSUE THREAD

**Issue by jjsadek** [crossplane/provider-aws#972]
I am trying to create a private hosted zone:

- when using vpcId to match vpc, it is working properly
- when using matchLabels, it is not working and i am getting the message: 'cannot resolve references: spec.forProvider.vpc.vpcId: no resources matched selector'. I confirm that the label is correctly matching the vpc tag.
- tried vpcIdRef where if my understanding is correct it should match the vpc name, it's also not working

Following is the resource config:

```
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  name: test-hostedzone
  namespace: crossplane-system
spec:
  forProvider:
    config:
      comment: 'test creating hosted zone using crossplane'
      privateZone: true
    name: 'internal.domain'
    vpc:
      vpcIdSelector:
        matchLabels:
          name: 'vpc-name'
      vpcRegion: 'us-west-1'
```

**Comment by haarchri** [comment]
it is working on our side 
which provider-aws you have running ?

```
spec:
  deletionPolicy: Delete
  forProvider:
    config:
      privateZone: true
    name: poc-cluster.crossplane.io
    vpc:
      vpcIdSelector:
        matchLabels:
          networks.aws.platformref.crossplane.io/network-id: poc-cluster-network
      vpcRegion: eu-central-1
  providerConfigRef:
    name: aws-provider
[...]
  conditions:
  - lastTransitionTime: "2021-11-22T11:14:25Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-11-22T11:14:22Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

in compositions the block looks like:

```
    - name: route53-hostedzone
      base:
        apiVersion: route53.aws.crossplane.io/v1alpha1
        kind: HostedZone
        spec:
          forProvider:
            config:
              privateZone: true
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.forProvider.dnsZone
          toFieldPath: spec.forProvider.name
        - fromFieldPath: spec.forProvider.networkRef.id
          toFieldPath: spec.forProvider.vpc.vpcIdSelector.matchLabels[networks.aws.platformref.crossplane.io/network-id]
        - fromFieldPath: "spec.forProvider.region"
          toFieldPath: "spec.forProvider.vpc.vpcRegion"
        - type: ToCompositeFieldPath
          fromFieldPath: spec.forProvider.name
          toFieldPath: status.eks.clusterDnsZone.name
          policy:
            fromFieldPath: Optional
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.hostedZone.id
          toFieldPath: status.eks.clusterDnsZone.id
          transforms:
            - type: string
              string:
                type: TrimPrefix ## working with crossplane >= 1.6.0
                trim: '/hostedzone/'
          policy:
            fromFieldPath: Optional
```
