### ISSUE TITLE
NodeGroup fails to update when unchanged labels exist

### ISSUE THREAD

**Issue by kurtb** [crossplane/provider-aws#975]
### What happened?

I updated the `desiredSize/minSize` `scalingConfig` properties in a `NodeGroup` but the operation failed with the error message

> cannot update EKS node group configuration: InvalidParameterException: Both or either addOrUpdateLabels or removeLabels must not be empty

My `NodeGroup` has the following config

```
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: g4dn-xlarge
spec:
  forProvider:
    region: us-west-2
    amiType: AL2_x86_64_GPU
    instanceTypes:
      - g4dn.xlarge
    clusterNameRef:
      name: cluster
    diskSize: 256
    subnetRefs:
      - name: vpc-subnet-1
      - name: vpc-subnet-2
      - name: vpc-subnet-3
    nodeRoleRef:
      name: node-role
    labels:
      gpu: nvidia
      accelerator: nvidia-t4
    scalingConfig:
      desiredSize: 2
      maxSize: 3
      minSize: 2
```

As a workaround, if I add a new label as part of the update - i.e. `zzzworkaround: "3"` then the operation completes as expected without error.

My guess is the bug is related to this line https://github.com/crossplane/provider-aws/blob/82e7f3f02baf949e2217ef76045786ad8b0700ce/pkg/clients/eks/nodegroup.go#L99. If both `addOrModify` and `remove` are empty then the line should likely be skipped.

If it does end up being the above I'm more than happy to help fix.  Just wanted to open the issue first.

### How can we reproduce it?

Create a `NodeGroup` with labels. Then update the `NodeGroup`'s scalingConfig.

### What environment did it happen in?
Crossplane version:  v1.5
Provider-aws: v0.21.0
Kubernetes: 1.21
