### ISSUE TITLE
subnetIdSelector: matchLabels: CannotResolveResourceReferences cannot resolve references: no resources matched selector

### ISSUE THREAD

**Issue by sqerison** [crossplane/provider-aws#976]
### What happened?
Hi team.
I'm trying to integrate Crossplane with an existed AWS resource that was created outside Crossplane using `subnetIdSelector`, but I'm receiving an error `cannot resolve references: no resources matched selector`.

I haven't found any documentation with the correct use cases and examples for the subnetIdSelector/securitygroupSelector feature.
Maybe I'm using this in the wrong way?
Maybe I need to add additional annotations to the Crossplane controller?

### How can we reproduce it?
```yaml
apiVersion: cache.aws.crossplane.io/v1alpha1
kind: CacheSubnetGroup
metadata:
  name: service-cachesubnet
spec:
  forProvider:
    description: Server Subnet Group
    region: us-west-2
    subnetIdSelector:
      matchLabels:
        networks.aws.platformref.crossplane.io/network-id: poc-cluster-network # unique label which has only subnets what I need to be discovered
  providerConfigRef:
    name: provider-aws
  providerRef:
    name: provider-aws
```
### Here is my provider config:
```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<roleName>
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:alpha
  controllerConfigRef:
    name: aws-config
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws
spec:
  credentials:
    source: InjectedIdentity
```

### What environment did it happen in?
Crossplane version: 
1.5

Include at least the version or commit of Crossplane you were running. Consider
also including your:

* Cloud provider or hardware configuration: aws provider
* Kubernetes version (use `kubectl version`): 1.22
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS
