### ISSUE TITLE
ReplicationGroup stuck in modifying loop

### ISSUE THREAD

**Issue by JaimeHolland** [crossplane/provider-aws#985]
### What happened?

When I create a ReplicationGroup, it is never marked as `Ready` - it seems to get in a loop of trying to modify something on the AWS side.  Below is the output of a `kubectl describe` on a test ReplicationGroup - I don't know if the `Pending Modified Values` section is hinting at the cause?:

<details>
  <summary>output</summary>
  
  ```txt
Name:         test-replication-group-qwdll
Namespace:
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2021-12-03T09:51:27Z
              crossplane.io/external-create-succeeded: 2021-12-03T09:51:28Z
              crossplane.io/external-name: test-replication-group-qwdll
API Version:  cache.aws.crossplane.io/v1beta1
Kind:         ReplicationGroup
Metadata:
  Creation Timestamp:  2021-12-03T09:51:27Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generate Name:  test-replication-group-
  Generation:     3
  Managed Fields:
    API Version:  cache.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:applyModificationsImmediately:
          f:atRestEncryptionEnabled:
          f:authEnabled:
          f:automaticFailoverEnabled:
          f:cacheNodeType:
          f:cacheParameterGroupName:
          f:cacheSubnetGroupName:
          f:engine:
          f:engineVersion:
          f:numNodeGroups:
          f:region:
          f:replicasPerNodeGroup:
          f:replicationGroupDescription:
          f:securityGroupIds:
          f:transitEncryptionEnabled:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl-create
    Operation:    Update
    Time:         2021-12-03T09:51:27Z
    API Version:  cache.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:preferredMaintenanceWindow:
          f:snapshotWindow:
          f:tags:
      f:status:
        .:
        f:atProvider:
          .:
          f:automaticFailoverStatus:
          f:configurationEndpoint:
          f:memberClusters:
          f:nodeGroups:
          f:pendingModifiedValues:
            .:
            f:resharding:
              .:
              f:slotMigration:
                .:
                f:progressPercentage:
          f:status:
        f:conditions:
    Manager:         crossplane-aws-provider
    Operation:       Update
    Time:            2021-12-03T09:57:32Z
  Resource Version:  82376803
  UID:               9a381784-71c1-41d6-921c-502234427381
Spec:
  Deletion Policy:  Delete
  For Provider:
    Apply Modifications Immediately:  true
    At Rest Encryption Enabled:       true
    Auth Enabled:                     false
    Automatic Failover Enabled:       false
    Cache Node Type:                  cache.r6g.large
    Cache Parameter Group Name:       default.redis6.x
    Cache Subnet Group Name:          my-redis-vj6qv-qk6fj
    Engine:                           redis
    Engine Version:                   6.2
    Num Node Groups:                  1
    Preferred Maintenance Window:     sat:05:00-sat:06:00
    Region:                           eu-west-1
    Replicas Per Node Group:          2
    Replication Group Description:    testing creation via crossplane
    Security Group Ids:
      sg-0b317014d0a616616
    Snapshot Window:  00:00-01:00
    Tags:
      Key:                       crossplane-kind
      Value:                     replicationgroup.cache.aws.crossplane.io
      Key:                       crossplane-name
      Value:                     test-replication-group-qwdll
      Key:                       crossplane-providerconfig
      Value:                     crossplane-provider-aws
      Key:                       managed_by
      Value:                     crossplane
    Transit Encryption Enabled:  true
  Provider Config Ref:
    Name:  crossplane-provider-aws
Status:
  At Provider:
    Automatic Failover Status:  disabled
    Configuration Endpoint:
    Member Clusters:
      test-replication-group-qwdll-001
      test-replication-group-qwdll-002
      test-replication-group-qwdll-003
    Node Groups:
      Node Group Members:
        Cache Cluster Id:             test-replication-group-qwdll-001
        Cache Node Id:                0001
        Current Role:                 primary
        Preferred Availability Zone:  eu-west-1b
        Read Endpoint:
          Address:                    test-replication-group-qwdll-001.test-replication-group-qwdll.lwho2g.euw1.cache.amazonaws.com
          Port:                       6379
        Cache Cluster Id:             test-replication-group-qwdll-002
        Cache Node Id:                0001
        Current Role:                 replica
        Preferred Availability Zone:  eu-west-1a
        Read Endpoint:
          Address:                    test-replication-group-qwdll-002.test-replication-group-qwdll.lwho2g.euw1.cache.amazonaws.com
          Port:                       6379
        Cache Cluster Id:             test-replication-group-qwdll-003
        Cache Node Id:                0001
        Current Role:                 replica
        Preferred Availability Zone:  eu-west-1b
        Read Endpoint:
          Address:  test-replication-group-qwdll-003.test-replication-group-qwdll.lwho2g.euw1.cache.amazonaws.com
          Port:     6379
      Port:         0001
      Primary Endpoint:
      Status:  available
    Pending Modified Values:
      Resharding:
        Slot Migration:
          Progress Percentage:  0
    Status:                     modifying
  Conditions:
    Last Transition Time:  2021-12-03T14:17:33Z
    Reason:                Unavailable
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-12-03T09:51:28Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:
  Type    Reason                   Age                   From                                              Message
  ----    ------                   ----                  ----                                              -------
  Normal  UpdatedExternalResource  68s (x355 over 121m)  managed/replicationgroup.cache.aws.crossplane.io  Successfully requested update of external resource
  ```
</details>

### How can we reproduce it?

Here is the yaml I used to create the test ReplicationGroup:

<details>
  <summary>yaml</summary>
  
  ```yaml
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
metadata:
  generateName: test-replication-group-
spec:
  providerConfigRef:
    name: crossplane-provider-aws
  deletionPolicy: Delete
  forProvider:
    replicationGroupDescription: "testing creation via crossplane"
    applyModificationsImmediately: true
    atRestEncryptionEnabled: true
    transitEncryptionEnabled: true
    authEnabled: false
    automaticFailoverEnabled: false
    cacheNodeType: cache.r6g.large
    cacheParameterGroupName: default.redis6.x
    securityGroupIds:
      - sg-0b317014d0a616616
    cacheSubnetGroupName: my-redis-vj6qv-qk6fj
    engine: redis
    engineVersion: "6.2"
    replicasPerNodeGroup: 2
    region: eu-west-1
    numNodeGroups: 1
    tags:
      - key: managed_by
        value: crossplane
  ```
</details>

### What environment did it happen in?
Crossplane version: 1.5.0
AWS provider version: v0.21.2
